### ISSUE TITLE
Batch script that installs everything

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1207]
I have been thinking about writing a .bat file that the "lazy" (no offense) windows user can double click in order to install the full Spine 'suite'. They would just need to select a folder in their system, and the script would go through all the steps in both Spine Toolbox and SpineOpt READMEs, namely:

- Download the right miniconda and install it
- Create the spinetoolbox env
- Clone the spinetoolbox repo
- `pip install` spinetoolbox requirements
- Install julia using python's `jill`
- Install SpineOpt
- Create a couple of .bat files, one to launch spinetoolbox (in the right conda env) and another to update everything (`git pull`, `Pkg.up()`, etc)
- All the above would be done in the folder that the user provided at the beginning so the installation is 'self-contained' (if that means something)

Any comments? Would that be something useful?

**Comment by soininen** [comment]
Those 'lazy' Windows users might also appreciate an uninstall option. Would that be possible with the script?

**Comment by manuelma** [comment]
> Those 'lazy' Windows users might also appreciate an uninstall option. Would that be possible with the script?

I think so. The idea is to put everything in one folder and don't mess with any env variables..., so In principle uninstalling would be equivalent to removing the folder.

**Comment by manuelma** [comment]
There is a working version in master https://github.com/Spine-project/Spine-Toolbox/blob/master/bin/install_spinetoolbox.bat

**Comment by ererkka** [comment]
Nice improvement. Did you add about this to README as well?

**Comment by manuelma** [comment]
> Nice improvement. Did you add about this to README as well?

Thanks. I want to try it in different Windows versions before advertising it too much. What do you think?

I also want to make sure that installing a new miniconda on Windows doesn't mess with existing ones. The script at the moment doesn't try to find conda in the local machine, it just downloads miniconda and installs it with the most non-intrusive settings. Is that nice?

**Comment by jkiviluo** [comment]
Is this still working and do we want to maintain it?

**Comment by manuelma** [comment]
I don't think we want, will remove it and close this issue.
