### ISSUE TITLE
Tool item becomes non-responsive

### ISSUE THREAD

**Issue by tltoni** [Spine-project/Spine-Toolbox#1208]
In the below video we show the steps to bring spine toolbox into a state where the tool bar item Tool does not work properly. More exactly, clicking the small triangle that should give the menu with item "Create new Tool Specification..." becomes non-responsive.

 https://screencast-o-matic.com/watch/crnjDbSVHo

The password to see the video is:
spinesupport

Reporter 
Toni Lastusilta (VTT)

**Comment by PekkaSavolainen** [comment]
Confirmed! But you have to do it exactly like in the video. I'm trying to find out the minimum steps to recreate this. Or do you (@tltoni) already have a simpler set of steps for this?

**Comment by tltoni** [comment]
Pekka, I have not tried to find the minimum steps to reproduce the issue.

**Comment by PekkaSavolainen** [comment]
Here's a simpler way to reproduce this.

1. Start Spine Toolbox without a project
2. Create a new project
3. Create a new Tool spec (e.g. Python or Julia). Give the Tool spec an empty file e.g. `a.py`.
4. Make a Tool with this Tool spec by dragging it from the Tool spec drop-down menu onto Design View
5. Make a Data Store
6. Link Data Store -> Tool
7. Go to Data Store properties and create a new (sqlite) spine db
8. Tool drop-down menu button does not work anymore

Sometimes the Tool button drop-down menu breaks after step 4, sometimes after step 5, but most likely after step 7. The reason for this is probably that Python garbage collects the `QMenu` created in `ProjectItemButton` class in very specific cases. @manuelma any idea what is going on here?

**Comment by PekkaSavolainen** [comment]
I think that's it. Will make a commit soon.

**Comment by PekkaSavolainen** [comment]
This was not very easy to find but I'm pretty sure this bug is gone after the commit above. @tltoni you want to check if you still see this.

**Comment by soininen** [comment]
By a quick look it didn't look to me like an instance attribute would be needed here but there is that little signal connected to the Python side menu object's `hide()` slot. I think garbage collecting the menu would make the connection disfunctional. Nice catch!

**Comment by PekkaSavolainen** [comment]
I think you are right @soininen
