### ISSUE TITLE
Open project fails to reset GUI properly

### ISSUE THREAD

**Issue by tltoni** [Spine-project/Spine-Toolbox#1209]
In the below video we show the steps to bring spine toolbox into a state where opening a new project does not reset the GUI properly. More precisely, clicking the small triangle on Tool item that shows "Create new Tool Specification..." shows an additional empty placeholder.

https://screencast-o-matic.com/watch/crnjDgSVP2

The password to see the video is:
spinesupport

Reporter
Toni Lastusilta (VTT)

**Comment by PekkaSavolainen** [comment]
Thanks. Fix coming up after some testing.

**Comment by PekkaSavolainen** [comment]
Fixed by the commit above. In addition to Tool specification drop-down menu, this also affected Data Transformer and Importer specification drop-down menus.
