### ISSUE TITLE
Query the db in another thread

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1210]
This is desirable so the UI is never affected by latency in queries, although we need to pay attention to sqlite requirement that objects created in one thread cannot be used in another thread.

We do all the querying in SpineDBManager which is good.

CC @soininen @jkiviluo

**Comment by manuelma** [comment]
Now all conversation with the db happens in the other thread. It's a bit better but there's still room for improvement. I believe QThread is not perfect, but at the same time some of our stuff can be improved too. At least we need to try to lazy load the pivot table.

Some of the new unittests that @soininen has been writing arrived just in time to help a lot in this little refactoring. Nice job!

**Comment by soininen** [comment]
I believe we are done here.
