### ISSUE TITLE
Disable menu actions depending on current state

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1213]
Re #1137 

I don't think it's too nice to show a menu with options that do nothing. Those options should be disabled, like 'Paste' whenever there's nothing to Paste. I think it can be done with `QMenu.aboutToShow`, we do it plenty in the DB editor but not that much in the main toolbox ui.

**Comment by PekkaSavolainen** [comment]
Yeah, I wasn't sure what was the best way to do that and I've missed the `aboutToShow` signal usage in Spine Db Editor. I'll take a look.

**Comment by manuelma** [comment]
Thanks. While you're at it, can you also try to find shorter names for "Paste project item and duplicate files" and "Duplicate project item and duplicate files"?

**Comment by PekkaSavolainen** [comment]
Any suggestions? I kind of like that they explicitly tell what they do.

**Comment by soininen** [comment]
"Paste item duplicating files"? I've been thinking about a submenu behind "Paste special" but it's probably an overkill since we have only one option there.

**Comment by manuelma** [comment]
I like @soininen suggestion a lot better, explicit but shorter.

**Comment by PekkaSavolainen** [comment]
Like this?
"Paste project item and duplicate files" -> "Paste item(s) duplicating files"
"Duplicate project item and duplicate files" -> "Duplicate item(s) and files"

**Comment by soininen** [comment]
> "Paste project item and duplicate files" -> "Paste item(s) duplicating files"
> "Duplicate project item and duplicate files" -> "Duplicate item(s) and files"

That's what I had in mind. Would be a nice addition if we'd choose between "item" and "items" case by case depending what's on the clipboard instead of the general "item(s)" but that's not a biggie.

**Comment by manuelma** [comment]
We could even remove the word item entirely, it's the only thing that can be pasted or dupe at all.

So in my opinion: "Paste duplicating files", and "Duplicate with files".

**Comment by PekkaSavolainen** [comment]
That was a bit more work than anticipated but I think it's perfect now. See commit message above.

**Comment by PekkaSavolainen** [comment]
> 
> 
> > "Paste project item and duplicate files" -> "Paste item(s) duplicating files"
> > "Duplicate project item and duplicate files" -> "Duplicate item(s) and files"
> 
> That's what I had in mind. Would be a nice addition if we'd choose between "item" and "items" case by case depending what's on the clipboard instead of the general "item(s)" but that's not a biggie.

I think we can leave this as a good first issue for new project members.
