### ISSUE TITLE
Move ReferencesTreeView and DataTreeView classes to spine_items

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1216]
Two Data Connection properties classes are still in `spinetoolbox.widgets.custom_qtreeview.py` when they should be in `spine_items.data_connection.widgets`. Remember to rebuild the UI after the move.

**Comment by manuelma** [comment]
Sure. I think the rationale for keeping them in toolbox was that third-parties could use them to develop their own items. What do you think?

**Comment by soininen** [comment]
Can't third-party project items import `spine_items`?

**Comment by manuelma** [comment]
> Can't third-party project items import `spine_items`?

Right. Also, I guess if they import `spinetoolbox` they'd be getting `spine_items` anyways. So it's good to do the move.

**Comment by PekkaSavolainen** [comment]
I thought this would be easy but it seems that the `ReferencesTreeView` is also used in View Properties. So, if I go with what is in the issue description, the View would import this class from `spine_items.data_connection.widgets`, which does not sound right. An option is that we create a `spine_items.shared` (I think we had some `shared` directory somewhere but now I don't see it anywhere) directory for widgets that are shared among project items. Is this a good idea or should we just drop this whole issue?

**Comment by soininen** [comment]
There are already some `.py` files in `spine_items\` that  contain shared code, e.g. `spine_items\widgets.py` contains shared widgets. We should definitely give a little tought how to share reusable components between items. The new Exporter item, for example, shares a lot of code with GdxExporter. In my branch, I have put some of that stuff into the files in `spine_items\` while more exporter specific stuff is directly in `spine_items\exporter` (home of the new Exporter). Both exporters import code from there. This is a bit messy in my opinion so it would be nice to agree on how to best share such stuff.

I am OK with putting shared stuff in `spine_items\`, `spine_items\widgets\` etc. following the directory structure of Toolbox. A separate `shared` directory is superfluous in my opinion.

**Comment by manuelma** [comment]
I think the policy I've been using is that as soon as it's two items or more that need the stuff, I put it in `spine_items` root. It happens with Tool and Gimlet too. I think definitely one project item shouldn't import from another project item. But any other setup suits me I believe.

**Comment by soininen** [comment]
> I think definitely one project item shouldn't import from another project item.

This sounds like a nice rule of thumb. The current inter-item imports between the exporters is not very clean.

**Comment by PekkaSavolainen** [comment]
Ok, I'll put these TreeView classes to `spine_items/widgets.py`, which I overlooked for some reason because I was looking for the `shared` directory (I agree that we don't need it). There's not that much stuff in spine_items root yet, but at some point we may need to consider a new structure for those.
