### ISSUE TITLE
Let the SpineOpt config assistant do more stuff to help users

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1217]
I have two things in mind:

1. Install julia if not found. This can be done well using the `jill` python pkg.
2. Once SpineOpt is installed, offer to also create a julia system image for it, so it runs faster.

**Comment by manuelma** [comment]
I have done part 1.

There's a new wizard to install Julia, accessible from File->Settings->Tools->Julia. It relies on the jill package.

Next to that wizard, there's another one called 'Add/Update Spine Opt' where the old SpineOpt config assistant has been moved.

**Comment by PekkaSavolainen** [comment]
See #1225 for the second part.
