### ISSUE TITLE
Should uncommitted database data be used during execution?

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1218]
We are currently somewhat inconsistent whether uncommitted data is used during execution or not. For example, filtering in project item links (arrows) exposes uncommitted scenarios and tools while GdxExporter exports committed data only.

Should we make a policy decision? Use uncommitted data where possible or leave that to Database editor only?

**Comment by soininen** [comment]
I don't have a personal preference. On developer side it is merely a choice between `DatabaseMapping` and `DiffDatabaseMapping` in read-only scenarios. I don't know if there is any difference in performance and how much weight we put on that, though.

**Comment by manuelma** [comment]
I think the user is able to select uncommitted scenarios and tools in the arrows, but none of those go into the tool. In general, uncommitted changes can't go into the next project item because all that's advertised is the url, not the DiffDatabaseMapping object. It's actually impossible to advertise the DiffDatabaseMapping object. So I think we're left with only one option which is not to show uncommitted stuff in the arrows. Am I missing something?

**Comment by soininen** [comment]
We *could* have a policy that all our project items use `DiffDatabaseMapping` even for read-only operations so uncommitted data would be used during execution. We don't have control over what Tools may use (except maybe for SpineOpt), though but since we cannot control it we shouldn't be bothered by it.

I feel this is a question of what behavior users expect/is most convenient but maybe there is some technical side I'm not taking into account.

**Comment by jkiviluo** [comment]
Right now I feel like uncommitted changes shouldn't go forward. However, it would be good to see a warning that you have uncommitted changes that are not used.

**Comment by soininen** [comment]
> However, it would be good to see a warning that you have uncommitted changes that are not used.

Would it be enough to have the exclamation on Data stores to notify on this?

**Comment by manuelma** [comment]
> We could have a policy that all our project items use DiffDatabaseMapping even for read-only operations so uncommitted data would be used during execution

Each call to `DiffDatabaseMapping` generates a new set of diff temporary tables. Sessions with `DiffDatabaseMapping` are completely isolated that way. So it's impossible to pass the uncommitted changes just by sharing the url.

**Comment by DillonJ** [comment]
If "committed" is to mean anything at all, then it should never be used in an execution?

I like the idea of the exclamation. Perhaps also there should be a warning at api level?

**Comment by soininen** [comment]
> Each call to DiffDatabaseMapping generates a new set of diff temporary tables. Sessions with DiffDatabaseMapping are completely isolated that way. So it's impossible to expose the uncommitted changes just by sharing the url.

Oh, alright, I did not know that! Then I guess we have no other option than to make sure we use committed data only during execution, at least for the moment.

**Comment by manuelma** [comment]
> Then I guess we have no other option than to make sure we use committed data only during execution, at least for the moment.

I'm pretty sure we already are, because of that "limitation" of DiffDatabaseMapping. What's definitely not correct at this point is that we show uncommitted scenarios and tools in the arrows, as if they were able to go on. They aren't. So that's something we need to fix and I think (unless I'm missing something) we're good to go.

**Comment by soininen** [comment]
I don't think there is much more to discuss here. I'll close this and open separate issues for scenario/tool filters and uncommitted data warning.

**Comment by manuelma** [comment]
Nice catch though.
