### ISSUE TITLE
Support feedback loops in Toolbox workflows

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1221]
The idea is to support running workflows with a single feedback loop. That is to say, the output of one item is communicated back to one of its ancestors, and the workflow is resumed from there. The operation is repeated until a condition is met. Probably, the feedback arrow will provide the interface so the user can define this condition.

This issue supersedes all previous issues on loops. I will try to find them and link them to here (or you can help me with that if you stumble upon one of them).

This will allow us to better support EMLab integration, cc @jimhommes

**Comment by jimhommes** [comment]
Thanks for tagging me. I had found [issue #824](https://github.com/Spine-project/Spine-Toolbox/issues/824) earlier when looking for loop issues.

**Comment by soininen** [comment]
Looping is supported now that PR #1446 has been merged. I am closing this and hope that we open more specific issues once we have more usage experience on what kind of feedback between project items we need to support.
