### ISSUE TITLE
Support for Python 3.8

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1223]
and drop support for Python 3.6.

**Comment by manuelma** [comment]
> and drop support for Python 3.6.

just curious, why?

**Comment by soininen** [comment]
> 
> 
> > and drop support for Python 3.6.
> 
> just curious, why?

I don't know what @PekkaSavolainen had in mind but dropping 3.6 would allow us to use some new functionality that has become available in 3.7. There have been a few cases already where I could have benefited from such. Nothing crucial, though just more convenient ways of getting things done.

**Comment by PekkaSavolainen** [comment]
`capture_output` made a come back to the configuration assistant and that is not yet available in python 3.6. This is just a case of do we want to keep supporting python 3.6 and fix this or just drop it?

**Comment by PekkaSavolainen** [comment]
We now have Python 3.8 support. I did not see any big problems with it, so I just enabled it.

**Comment by manuelma** [comment]
Sorry about `capture_output`! I keep forgetting about that one. Do you want me to remove it, or we just drop 3.6?

**Comment by PekkaSavolainen** [comment]
Up to you. If you want to fix it, then let's keep 3.6

**Comment by manuelma** [comment]
I can change it, but at the same time, do we want to support so many versions? I believe the more versions we support, the harder it gets on us. There're already troubles with getting PySide2 to work across different pythons and OSes, don't you think?

**Comment by PekkaSavolainen** [comment]
Yes, we should just remove support for Python 3.6.

**Comment by PekkaSavolainen** [comment]
@soininen, @manuelma, if you haven't yet, please take a look at the changes in Python 3.8 https://docs.python.org/3/whatsnew/3.8.html. I don't see a lot of things affecting us but I may have missed something. 

One thing I did notice is that we need a small update to our subprocess.POpen() call(s) (see https://docs.python.org/3.8/library/subprocess.html#subprocess.Popen). In Spine Toolbox, there's a new warning message appearing on Python 3.8 when executing a Project Item.

```
C:\Python38\lib\subprocess.py:844: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
```

The cause of this is most likely the `bufsize=1` argument on line 67 in **spine_engine/execution_managers.py**

`self._process = Popen([self._program, *self._args], stdout=PIPE, stderr=PIPE, bufsize=1, cwd=self._workdir)`

**Comment by soininen** [comment]
I had a look at the release notes and it seems we are good to go. Not that we are planning to make any changes but we should keep using `&` as the URL query separator in `spinedb_api` as it will be the only separator accepted in 3.8.

**Comment by PekkaSavolainen** [comment]
I think we should let the dust settle for a while before enabling Python 3.9. There's one more thing to do here. Should I go ahead and remove python 3.6 support from our setup.py files?

**Comment by PekkaSavolainen** [comment]
Fixed the RunTimeWarning by removing the 'bufsize=1' parameter. This only affected the StandardExecutionManager and not the console execution.

**Comment by PekkaSavolainen** [comment]
Done.
