### ISSUE TITLE
Unit tests: QThread: Destroyed while thread is still running

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1224]
It seems that some threads are not terminated properly when running the unit tests. This happens in multiple tests. One example is `test_duplicate_object_in_object_tree_model()` test in `tests/spine_db_editor/widgets/test_SpineDBEditorWithDBMapping.py`.

**Comment by manuelma** [comment]
I noticed. The culprit is `SpineDBManager` constructor that creates and starts a thread, see #1210. We need to call `clean_up()` on all `SpineDBManager` instances that we use in tests. Note that `ToolboxUI` constructor already creates a `SpineDBManager`.

**Comment by soininen** [comment]
Tests seem to be passing now.

**Comment by manuelma** [comment]
Thanks @soininen ! I guess it's unit-tests day?

**Comment by soininen** [comment]
>  I guess it's unit-tests day?

Yep! Hopefully I'll finally get the headless mode working today so I can implement a scripted test that executes an entire project.

**Comment by manuelma** [comment]
That would be an absolute win. Good luck.
