### ISSUE TITLE
Get rid of Process Log and introduce Item Execution Log

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1228]
Edit: The original issue was actually multiple issues. This issue is now just about getting rid of process log (done) and replacing with Item Execution log, which was done by commit https://github.com/Spine-project/Spine-Toolbox/commit/3bb156d4905cf14725160d4d45f373f08b01ede1. Remaining problems are discussed at the end of the chain.

--- OLD TEXT BELOW --- 
I was trying to import something quite simple from Excel, but I ran into unexpected problems. Attached is a Spine Toolbox project that replicates the problems:

- When changing something in the import spec, I often close it by closing the window ('x' in the upper right corner). Toolbox does not warn about losing the made changes and does not tell about it. It only saves if pressing 'ok'. When you press ok, it prints out 'Specification x successfully updated' twice.
- When not using the 'Cancel import on error', Toolbox says Dag 1/1 completed successfully although it does not import the demand.

[TradeRES.zip](https://github.com/Spine-project/Spine-Toolbox/files/5994174/TradeRES.zip)

**Comment by manuelma** [comment]
Thanks. I believe it's best if we take it one issue at a time, For example "Trying to import 'demand' fails. Toolbox doesn't give any error messages and does not offer to open the import log." Can we isolate that? For me it always shows the link to open the error log. Have you selected the Importer execution icon (the circle with a check or a cross) to see the importer output in the event log? Is this a logging problem?

**Comment by jkiviluo** [comment]
I didn't know where the logs had gone. Now that I see it, it's all there as you say. 

Why wouldn't it show the log when the item itself is selected? And really we should have one window where the Toolbox level logging goes and another that shows the log for the currently selected item. Just to make things more apparent for the user. We even have that 'process log' window which appears to be empty nowadays (maybe it shows something when a Python tool is executed, but there is the Python console for that).

**Comment by manuelma** [comment]
Yes, I'm definitely with you on this one. We should get rid of Process log and instead have an 'Item log' that shows everything for the selected item. And never override the main event log.

I think overriding the main log was a bad idea. I tried to make it better by only overriding if you select the Execution icon, so it's less intrusive, but I guess I failed. @PekkaSavolainen was also worried about this and started doing something in another issue.

I can try to clean up my mess again and implement this new idea: Get rid of Process log (always empty nowadays) and introduce Item log that shows everything for the selected item. How does that sound?

**Comment by jkiviluo** [comment]
I like the "Get rid of Process log (always empty nowadays) and introduce Item log that shows everything for the selected item". Let's continue there on that topic. I will edit the original issue here to exclude that part.

**Comment by jkiviluo** [comment]
And you're right, I should've made separate issues from the start.

**Comment by PekkaSavolainen** [comment]
Just a small correction, I think you mean that the 'main' Process Log is always empty. When you execute Python or Julia *without* using the embedded console the tool output goes to the Process Log. Also, GAMS, and executable item's **always** print their output to the Process Log. These are not printed to the 'main' Process Log but to the specific 'item's' Process Log. But even the 'main' Process Log is not always empty. It shows the output of the Configuration Assistant.

I like the idea of getting rid of the whole Process Log widget since it's kind of an extra window that we could do without.

**Comment by manuelma** [comment]
Good points @PekkaSavolainen 

1. I was thinking that the item's event and process log can go to the same document, e.g.:

```
Tool execution started
Copying Files...
Starting Tool instance...
See process log for messages <- Don't show this
   <process log messages>  <- Do this instead, just inline process messages right here
Tool execution finished
```
2. Add a QTextBrowser to the config assistant QDockWdiget that shows the process output for the configuration process.

With this, we can effectively get rid of Process Log, in favor of Item Execution Log. What do you think?

**Comment by jkiviluo** [comment]
Updated the description again, since I realized what I was doing wrong (been there before, but couldn't recall...)

**Comment by manuelma** [comment]
Sounds good then, I will start working on the new Item Execution Log. Thanks for the input!

**Comment by jkiviluo** [comment]
BTW, I would even prefer that pressing 'x' to close the window would automatically save the changes. You can see that it was done in the event log and the user would learn that to cancel you need to press cancel. This way you can save your stuff by doing alt-F4 (which I suppose I have a habit of doing). I leave things open and then when it comes the time to clean up, I just try to get it done quickly.

**Comment by manuelma** [comment]
I did something about the Item Execution Log in master. What do you think @PekkaSavolainen @jkiviluo ?

**Comment by jkiviluo** [comment]
Looks really pretty when running a single scenario. Branching does not seem to work though. The Execution log stays empty and when switching between executions, I get this:

```
Traceback (most recent call last):
  File "c:\data\spinetoolbox\spinetoolbox\ui_main.py", line 1442, in _refresh_execution_list
    self._select_execution(current, None)
  File "c:\data\spinetoolbox\spinetoolbox\ui_main.py", line 1453, in _select_execution
    self._set_override_console(self.ui.dockWidgetContents_python_console, python_console)
TypeError: _set_override_console() missing 1 required positional argument: 'new_title'
```

I suppose the logical place for the 'Executions' would be below the Tool properties tab? I know I can move it there, but just as a default.

**Comment by manuelma** [comment]
Will fix that, thanks.

**Comment by manuelma** [comment]
> When changing something in the import spec, I often close it by closing the window ('x' in the upper right corner). Toolbox does not warn about losing the made changes and does not tell about it. It only saves if pressing 'ok'. When you press ok, it prints out 'Specification x successfully updated' twice.

I will work on this next. I think the X should still be equivalent to Cancel, that's the standard and I feel it would be weird if we don't follow it. But we should prompt the user whenever they press Cancel or the X with a dirty spec, and ask them if they want to save before closing. What do you think?

**Comment by PekkaSavolainen** [comment]
Yes, X and Cancel and whatever else closes the window should do the same thing. Prompting the user if there are changes to the spec is a good improvement (like we already do in the Spine Db Editor).

**Comment by jkiviluo** [comment]
Ok, I yield. Maybe a keyboard shortcut for 'ok'? Is there a de-facto standard?

**Comment by jkiviluo** [comment]
Multiple executions seems to also work now. Very nice!

**Comment by manuelma** [comment]
> Ok, I yield. Maybe a keyboard shortcut for 'ok'? Is there a de-facto standard?

Return/Enter. I can try that.

**Comment by soininen** [comment]
Is Return/Enter a bit problematic if users want to confirm changes in e.g. the mapping table? We have that problem in Database editor's parameter value editors where the dialogs close when you confirm a change by pressing enter.

**Comment by PekkaSavolainen** [comment]
I like the new execution log. There are two small issues I found. The hyperlinks (*work directory*, *Results directory*) in the execution log seem to be broken. Also, If you rename a project item, the execution log (and console) titles still show the previous name.

Should this issue title be "Get rid of Process Log and introduce Item Execution Log" or something? Makes finding this issue easier in the future.

**Comment by manuelma** [comment]
Hmm this issue is also about saving changes in the import editor when closing, so I'm not sure about the renaming. But yeah, there are two issues here in one. I'm open to any solutions.

I can work on fixing those two small issues @PekkaSavolainen

**Comment by jkiviluo** [comment]
> Is Return/Enter a bit problematic if users want to confirm changes in e.g. the mapping table?

Right. Ctrl-enter is used in couple of other places and I find it quite useful. It's also used elsewhere sometimes. Maybe that?

**Comment by jkiviluo** [comment]
Cleaned out this issue and made two separate issues as you can see above.

**Comment by manuelma** [comment]
> The hyperlinks (work directory, Results directory) in the execution log seem to be broken. Also, If you rename a project item, the execution log (and console) titles still show the previous name.

I've fixed this (I think). Please let me know if there's anything else here.

**Comment by manuelma** [comment]
I think the execution list (the one with the multiple parallel executions) might be improved.

**Comment by PekkaSavolainen** [comment]
I believe this issue as described in the title is done.
