### ISSUE TITLE
[Windows & Python 3.8] ImportError: DLL load failed while importing win32api

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1230]
Happens when the app is installed to a conda environment with `pip install -r requirements.txt`. When trying to execute a Tool in either Julia or Python Console, it fails with the following traceback.

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\ttepsa\.julia\conda\3\envs\py38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\ttepsa\.julia\conda\3\envs\py38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ttepsa\.julia\conda\3\envs\py38\lib\site-packages\spine_engine\spine_engine.py", line 390, in _execute_item_filtered
    item_success = item.execute(filtered_forward_resources, filtered_backward_resources)
  File "C:\Users\ttepsa\.julia\conda\3\envs\py38\lib\site-packages\spine_items\tool\executable_item.py", line 403, in execute
    self._tool_instance.prepare(self._cmd_line_args)
  File "C:\Users\ttepsa\.julia\conda\3\envs\py38\lib\site-packages\spine_items\tool\tool_instance.py", line 199, in prepare
    self.exec_mngr = KernelExecutionManager(
  File "C:\Users\ttepsa\.julia\conda\3\envs\py38\lib\site-packages\spine_engine\execution_managers.py", line 200, in __init__
    self._kernel_manager = _kernel_manager_factory.new_kernel_manager(
  File "C:\Users\ttepsa\.julia\conda\3\envs\py38\lib\site-packages\spine_engine\execution_managers.py", line 144, in new_kernel_manager
    km.start_kernel(stdout=blackhole, stderr=blackhole, **kwargs)
  File "C:\Users\ttepsa\.julia\conda\3\envs\py38\lib\site-packages\jupyter_client\manager.py", line 309, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "C:\Users\ttepsa\.julia\conda\3\envs\py38\lib\site-packages\jupyter_client\manager.py", line 258, in pre_start_kernel
    self.write_connection_file()
  File "C:\Users\ttepsa\.julia\conda\3\envs\py38\lib\site-packages\jupyter_client\connect.py", line 468, in write_connection_file
    self.connection_file, cfg = write_connection_file(self.connection_file,
  File "C:\Users\ttepsa\.julia\conda\3\envs\py38\lib\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\ttepsa\.julia\conda\3\envs\py38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Users\ttepsa\.julia\conda\3\envs\py38\lib\site-packages\jupyter_core\paths.py", line 461, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\ttepsa\.julia\conda\3\envs\py38\lib\site-packages\jupyter_core\paths.py", line 387, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed while importing win32api: The specified module could not be found.
```

**Comment by PekkaSavolainen** [comment]
A temporary fix. In the activated conda environment do this:

```
pip uninstall pywin32
```

and then

```
conda install pywin32
```

**Comment by manuelma** [comment]
Which Windows/Python versions?

**Comment by PekkaSavolainen** [comment]
Windows 10 Enterprise, version 1909, OS build 18363.1316. Python 3.8 (does not happen on 3.7)

**Comment by PekkaSavolainen** [comment]
@ererkka, @soininen, @manuelma Is it possible to update requirements.txt so that when users do `pip install -r requirements.txt`, pywin32 is installed using conda **if on conda** or using pip **if not on conda**.

Or what is the alternative here?

**Comment by PekkaSavolainen** [comment]
pywin32 version 225 seems to get the job done. Dagster does not support pywin32 226 and this issue happens on pywin32 227. I'm just going to require pywin32==225 in requirements.txt unless somebody has a better idea.

**Comment by PekkaSavolainen** [comment]
Done. Please reopen if you find a better alternative solution.

**Comment by PekkaSavolainen** [comment]
This also happens on **Windows** system Python 3.8 and pywin32==225. This gets solved there if pywin32 is upgraded to the latest (300) but this pywin32 version does not work with Conda Python 3.8 (the original issue here).

There's an easy way to reproduce this, just do `import win32api` in whatever Python you are on.

Here's a summary about this problem on different setups:

- Python 3.7 and pywin32== 225
No problem

- Conda Python 3.7 and pywin32=225
No problem

- Python 3.7 and pywin32==300
No problem

- Conda Python 3.7 and pywin32==300
No problem

- Python 3.8 and pywin32==225
**ImportError: DLL load failed....**

- Conda Python 3.8 and pywin32==225
No problem

- Python 3.8 and pywin32==300
No problem

- Conda Python 3.8 and pywin32==300
**ImportError: DLL load failed....**

Should we just update the troubleshooting section on readme.md to say that if you are on windows and using the system Python 3.8 and you experience this, just do `pip install --upgrade pywin32`? Or anybody have other ideas?  (@soininen, @ererkka)

**Comment by ererkka** [comment]
In general, if using conda, one should install as many packages using conda as possible and only then using pip. That has worked for me most of the time. This is my development environment:

```yaml
name: spinetoolbox
channels:
  - defaults
dependencies:
  - python <3.9
  - setuptools >=41.0.1
  - pip >=19.1.1
  - pre-commit ==2.0.1
  - PyYAML <5
  - pylint >=2.3.0
  - black ==19.3b0
  - nb_conda_kernels
  - pywin32 ==225
  - numpy >= 1.15.1
  - scipy >= 1.1.0
  - pandas >= 0.24.0
  - pyrsistent <0.17
  - jsonschema ==2.6
  - pip:
    - "-e ../Spine-Database-API"
    - "git+https://github.com/Spine-project/spine-engine.git#egg=spine_engine"
    - "matplotlib !=3.2.1, <3.3.1"
    - "tornado >=6.1"
    - "-e ."
    - "-e ../spine-items"
    - "-r dev-requirements.txt"
```

**Comment by PekkaSavolainen** [comment]
Sure, but the problem here is that our readme.md says that do `pip install -r requirements.txt` and if you do this now on **NOT CONDA** python 3.8, it will install pywin32==225, which causes problems.

As I said above one solution could be to update requirements.txt so that when users do `pip install -r requirements.txt`, pywin32 is installed using conda if on conda or using pip if not on conda. But I have no idea how to do this or is it even possible?

Another possibility is to make two 'requirements` files (I guess it's called an 'environment' file or something like that on conda), the other one for conda and the other one for pip, but maintaining even one requirement file is a lot of work, so I would like to avoid that.

**Comment by manuelma** [comment]
The instructions say do `pip install -r requirements.txt` *on Conda*.

**Comment by manuelma** [comment]
To understand, does the problem happen if users follow the instructions in README to the line? Because if it doesn't, I don't think we should worry.

**Comment by PekkaSavolainen** [comment]
As @ererkka said above, packages that are available on conda should be installed using conda. So, doing `pip install -r requirements.txt` on conda is not 100% correct. If there was something like `conda install -r requirements.txt`, it would solve this problem and I would be happy.

Also, I don't think our GitHub action that runs the unit tests, runs them on conda.

**Comment by manuelma** [comment]
To me, the important thing is that the instructions work with Python 3.8 on Windows. Do they? Also I agree with you that ideally we would avoid pip on Conda. If that's possible, even better.

**Comment by PekkaSavolainen** [comment]
They do, and for that reason this is not a top priority thing but it's still important to me that this works on not conda too. I'll just update the troubleshooting guide for now.

**Comment by ererkka** [comment]
`conda install` supports `-r <file>` option as well. It’s just that sometimes package names are different in PyPI and conda world, so this is not a perfect solution. I experienced problems (still) when I installed PySide2 (or Qt) using conda. The environment file above is tested and working. I think most important is to support pure Python and PyPI because that’s kind of standard. Helping out conda users is a nice addition since even on Windows one can get Python easily nowadays from python.org or even from MS Store.

**Comment by PekkaSavolainen** [comment]
Success! We now add a directory to PATH on [Windows] Python 3.8 when launching the app. As the error message said, it had trouble finding some DLLs and it turns out the DLLs were found in `.../site-packages/pywin32_system32` directory which is not added to PATH automatically. The reason why this does not happen on Python 3.7 has something to do with changes to DLL resolution that were introduced in Python 3.8. I lifted the pywin32==225 restriction in requirements.txt and it's now pywin32>=301 since the newest one should now be working on both pure Python3.8 and Conda Python3.8.

Also, removed the relevant section from readme.md's troubleshooting guide since it may have been confusing now.

Note that if you make a fresh Python 3.8 conda environment, activate it, then do `pip install -r requirements.txt` then do `python -c "import win32api"`, you will still see the ImportError but we don't really care about that since it works when using Spine Toolbox.

**Comment by PekkaSavolainen** [comment]
I should have probably used this one https://docs.python.org/3/library/os.html#os.add_dll_directory but my solution seems to get the job done. If there are still problems, that is the next thing to try.
