### ISSUE TITLE
Optimize README for general public

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1232]
Our README is great, but I think it should be optimized for general public. The more tech-oriented people won't miss anything, but the non-tech ones would appreciate (I think) if we go straight to the point. How to install, run, and upgrade, nothing more.

Recently I've found myself 'translating' the README to students that just want to run a model. I think I can give it a try, what do you think @PekkaSavolainen @jkiviluo ?

**Edit**: Also, I think we should stick with Conda and forget about installation from shell. People who know Python can easily figure that one out, but it distracts the non-experienced people I believe.

**Comment by PekkaSavolainen** [comment]
There's always things to improve here but do you think README is the place to add steps on how to just run a model? I'm curious what you have in mind here but I'm afraid we'll end up with another set of instructions to maintain.

My suggestion is that we add a new section to README after installation sections that says something like this

> How to Run a Model
> After you have installed and started the app successfully. Here are the instructions on how to run your first model.

And then a link to the Getting Started guide on readthedocs.org. Getting Started really needs the update on how to set up Python and Julia and GAMS and then have the simple instructions on how to run your first model.

Also, about the non-tech vs. tech people. Maybe this is a Windows/Linux thing but to me the tech-oriented people use conda and the regular folks just install python from python.org.

By the way, what is the part that needs the most translating?

**Comment by manuelma** [comment]
Sorry I wasn't clear, and thanks for the feedback. I'm not talking about adding any particular instructions on how to **use** Toolbox. The user guide is the place for that, you're right about that.

I'm talking about **installation** instructions in particular. We're too vague, talk about different branches and stuff, that people don't understand. They just want to see the steps to follow to have a running Spine Toolbox. I'm proposing, for example, that instead of having a link to some deep documentation about cloning repositories, we just tell the users to run `git clone https://github.com/Spine-project/Spine-Toolbox.git`.

> tech-oriented people use conda and the regular folks just install python from python.org

I think we need to tell non-tech people the easiest/safest way to get Spine Toolbox running. Is that Conda, or is it Python.org? I'm pretty sure it's the former.

> By the way, what is the part that needs the most translating?

The "Installing Spine Toolbox" section

**Comment by PekkaSavolainen** [comment]
Ok, thanks for the additional info and good luck. 

If/when we get Spine Toolbox to pypi, our installation instructions would be quite simple...

**Comment by manuelma** [comment]
> If/when we get Spine Toolbox to pypi, our installation instructions would be quite simple...

That's right! Do we have any plans for that?

Also, maybe I can create my modified version of the README through a pull request, if you want/have time to review it first?

**Comment by PekkaSavolainen** [comment]
Thanks, it's perfect now.
