### ISSUE TITLE
Event log says 'succesful' completion for the importer even when it has not been.

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1235]
When not using the 'Cancel import on error', Toolbox says Dag 1/1 completed successfully although the import has failed (as shown by the execution log).

Split from the issue #1228.

**Comment by manuelma** [comment]
Has the import really failed? Doesn't Cancel on error mean that the user is ok with the import partially failing? They want to import as much as possible, and they don't want the workflow to fail (and stop) if there are import errors.

**Comment by manuelma** [comment]
I believe the issue here was that we couldn't see the importer log, because it was masked by our poor logging system. Now the logging system is much better and one can see Importer and DAG logs side to side. Which means it's harder to misinterpret the DAG 1/1 completed successfully.

**Comment by PekkaSavolainen** [comment]
I'm pretty sure I fixed the inconsistencies between what is the finished execution state of project items on Design View and what is reported to the Logs (Event and execution) while doing #1374. If not the case, please reopen.
