### ISSUE TITLE
Get rid of notifications in kernel editor

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1239]
We have a QtextBrowser to talk to the user, do we really need the notifications on top of that? It's really just duplicate information, see screenshot

![Screenshot from 2021-02-20 08-50-50](https://user-images.githubusercontent.com/11472756/108588594-70060800-7330-11eb-8619-4b1fc1ab8978.png)

The same I read in the log, I also read as notification.

In addition, sometimes the notification is easy to miss. For example, often times I press Create kernel without entering a name, and it looks like nothing happens. But there's a small notification on the top right that says 'Name missing'. It always takes me two or three times of pressing the button to finally see the notification...

I propose we get rid of all notifications and just use the log to communicate with the user.

**Comment by PekkaSavolainen** [comment]
Yes, the notifications can be removed. What happened is that at the start my plan was to notify user what's going on solely with the notifications. At the end I realized that the subprocess messages cannot be communicated with the notifications, so I added a QTextBrowser there and I never removed the notifications.
