### ISSUE TITLE
Get rid of SpineOpt config assistant?

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1240]
I recently created #1217 which points in the total opposite direction as this one, but...

Has anybody ever used the config assistant successfully?

Here is my case againts it:
1. Installing SpineOpt is quite [easy](https://github.com/Spine-project/SpineOpt.jl#installation) now we don't need to reconfigure PyCall. It was PyCall reconfiguration that was difficult and used to be the main purpose of the config assistant (and even then, I don't think it ever worked well).
2. It obscures something that should be transparent for the users, like installing a new package in their julia.
3. It will never handle some [problems](https://github.com/Spine-project/SpineOpt.jl#troubleshooting) that may appear, particularly on windows, forcing the users to open their julia prompt anyways
4. Maybe it would be more useful if it also installed Julia if not present, as suggested in #1217. But is that a good idea? Messing with the user's system? Lots of corner cases to consider? Trying to do the job of a package manager? Many things can go wrong?

**Comment by DillonJ** [comment]
What we need is an overall deployment strategy that covers Spine Toolbox, Spine Interface and SpineOpt. This is the system promised in the proposal.

I discussed this a little in https://github.com/Spine-project/SpineOpt.jl/issues/147.

There are of course many corner cases which makes this quite challenging - so maybe we need to take the 80/20 approach. Provide a nice solution for the most common 80% of cases with 20% of the effort. Also - the corner cases are possibly more likely when the user is more of an expert so it shouldn't be too much of a problem.

I believe we need a nice deployment solution for the most common use cases - when someone wants to download and install Spine Toolbox and SpineOpt to try it out. 

Also as I mentioned in https://github.com/Spine-project/SpineOpt.jl/issues/147 perhaps the best place to start is a flow chart of the installation steps and options.

I guess I am trying to address the bigger picture issue to see if it brings any more clarity to the need for the configuration assistant.

**Comment by manuelma** [comment]
So we have two installation paths. One is the windows installer, that we're trying hard to make work. Eventually, we might be able to prepackage everything in there, so the user gets a package that has both Spine Toolbox and SpineOpt working out of the box. I have no idea how to accomplish that so I might be a bit optimistic here.

The second installation path is the development versions. What do you think of SpineOpt's [README](https://github.com/Spine-project/SpineOpt.jl). My opinion is those instructions are quite easy follow, and there's no point in trying to automate them. We can of course do it and we have done it. My fear is that in some platforms, the process might fail and leave the user hanging. 80% success in installation of a new tool is not high enough in my opinion, it should be 99%. And to me, the simplest way of achieving that 99% is relying on the user more, provide troubleshooting and support, rather than trying to create an automatic monster.

**Comment by DillonJ** [comment]
In principle I have no problem relying on the user...

We should keep in mind the feedback from the surveys - people were very frustrated trying to get SpineOpt working - we have to, at the very least, improve things... so I guess my question would be - how have things improved for the user since then?

**Comment by manuelma** [comment]
> how have things improved for the user since then?

We have removed the PyCall dependency which now makes installation straight-forward. We have also added a troubleshooting section to our README. We have also added added instructions to setup Spine Toolbox to use Julia, which were missing before.

I have collected a lot of information by guiding two KTH bachelor students, and now all that's in the README. (One of them even has Windows 7.) That's the only way we can improve I believe, by following users closely. I don't know if that survey provides any information on specific issues, concrete reasons of why people were frustrated.

**Comment by DillonJ** [comment]
I just had a look at the README - it does look good. Perhaps this is where we need to direct our efforts. Some ideas:
 - A little more explanation regarding what each step/command is doing
 - A prominent link at the top for where to get support
 - Be a little more explicit for slower users like me - for example, someone new to Julia... will they know what "Run Julia" means - perhaps run "Run the Julia REPL console" (or whatever) (with instructions for windows and linux - or perhaps a link)
 - Instructions for or a link to how to run the examples or a link to "my first project" - here I think it is very important that it is easy for the user to run SpineOpt from toolbox - there should be a SpineOpt tool a user can easily use to run a sample project.

**Comment by manuelma** [comment]
> A little more explanation regarding what each step/command is doing

I guessed users don't want/need to know, but I'll add it.

> A prominent link at the top for where to get support

I can add it, but do we have one such link?

> Be a little more explicit for slower

yes, I can do that too.

> Instructions for or a link to how to run the examples or a link to "my first project" 

This is in Usage. We point them to the Case Study A5 tutorial. It's a start, we can improve in two ways:
1. Shipping example projects with the toolbox installation; in this case we need to instruct the users how to open that project, how to execute it, and how to checkout results
2. Create a smaller tutorial. I believe this was discussed, like how to run a model with three nodes and one demand time-series, or something like that...

**Comment by DillonJ** [comment]
> I can add it, but do we have one such link?
Good point - we need our Support discussion categories created - I will ask @ererkka 

> Create a smaller tutorial.
Yes, we need to do that... I can't remember whose name was against it - maybe it was me?

Let's say I have toolbox installed - then I follow the SpineOpt README instructions... all good. Now I have an SQLITE model file I want to view and run. Right now, I suppose the user would need to configure a Julia Kernel? I.e. there are steps here that are not covered in either the toolbox setup nor in the SpineOpt setup - is this true? It doesn't really come under "usage" it's more configuring toolbox to run SpineOpt?

**Comment by DillonJ** [comment]
Since SpineOpt needs Toolbox to run... we need to start in the Readme by saying that and directing people to the toolbox set up.

Toolbox setup should have a section : configuring toolbox to run Julia tools and SpineOpt...

Then when the user arrives back to the SpineOpt setup - Julia should be installed? Already?

I'm trying to think of a logical flow for how a user that wants everything should be able to go from zero to running a tutorial in the most logical way possible

**Comment by DillonJ** [comment]
By the way, I took the liberty of renaming the Q/A category to Support Q/A - we can link to that?

**Comment by manuelma** [comment]
> Since SpineOpt needs Toolbox to run... perhaps we need to start in the README by saying that and directing people to the toolbox set up.

I like the way it is now. In Usage, we tell people to install toolbox as first step. We can also have that in installation: Step 1, install Toolbox and come back here. Step 2, install SpineOpt.

But I think the flow is better the way it is now.

**Comment by manuelma** [comment]
> By the way, I took the liberty of renaming the Q/A category to Support Q/A - we can link to that?

Sounds good.

**Comment by manuelma** [comment]
> It doesn't really come under "usage" it's more configuring toolbox to run SpineOpt?

In Usage, we tell the people how to configure Spine Toolbox to use the Julia executable. I suppose we can also explain how to use a Kernel, but that's more complicated, and it gets too long for a README. Perhaps all these configuration options can be part of Toolbox user's guide, so we can put a link to that in our README.

**Comment by DillonJ** [comment]
What bothers me about all this is the bit linking Toolbox to SpineOpt - I feel it's not prominent enough. It doesn't feel like "usage" covers it. It feels more like configuration.

Maybe what we need is a higher level guide somewhere, that has the very high level steps + links to the relevant readmes.

E.g. :
 - Install SpineOpt: link
 - Install Toolbox : link
 - Configure toolbox: link
 - Example project: link

**Comment by manuelma** [comment]
You're right, I will move the configuration step right after installation, it makes more sense.

I was also thinking about the one README to bring them all, but I don't know where to put it. Perhaps in http://www.spine-model.org/ ?

**Comment by DillonJ** [comment]
> I was also thinking about the one README to bring them all, but I don't know where to put it. Perhaps in http://www.spine-model.org/ ?

I was thinking that too... but it's a pity not to have it in Github also... perhaps each README could link back to the high-level guide

**Comment by manuelma** [comment]
Maybe we can have a repo called simple Spine that just have one file, the super README. That would be easy to link/update.

**Comment by DillonJ** [comment]
> Maybe we can have a repo called simply Spine that just have one file, the super README. That would be easy to link/update.

Not a bad idea at all... would be good for some of the meta discussions/issues also

**Comment by PekkaSavolainen** [comment]
Would it be better to use the description area of https://github.com/Spine-project for the super 'readme'?

**Comment by manuelma** [comment]
> Would it be better to use the description area of https://github.com/Spine-project for the super 'readme'?

I don't feel there's enough space there, plus I don't seem to have rights to edit it, and it wouldn't be version controlled. Otherwise, it doesn't feel like a bad idea.

**Comment by PekkaSavolainen** [comment]
> I don't feel there's enough space there, plus I don't seem to have rights to edit it, and it wouldn't be version controlled. Otherwise, it doesn't feel like a bad idea.

Sounds like a pretty bad idea then 😄. Still it's a bit of a shame since that is the front page of Spine project in GitHub.

**Comment by manuelma** [comment]
So what about this issue? Can we get rid of the configuration assistant?

**Comment by DillonJ** [comment]
> Sounds like a pretty bad idea then 😄. Still it's a bit of a shame since that is the front page of Spine project in GitHub.

Assuming we have a good Meta README somewhere, we could at least point to it from the description page - but I think you're right in that we should use this, at least to direct people to the right place.

> So what about this issue? Can we get rid of the configuration assistant?

For my part - I'd like to see the high level deployment strategy and how we are going to handle the dependencies across the Spine suite and satisfy the requirement that SpineOpt, as the native model of Spine, is suitably prominent and easy to use. As @mihlema says in https://github.com/Spine-project/SpineOpt.jl/issues/147 a prepackaged SpineOpt plugin might be a nice way to go about it. I think we can certainly park the config assistant and stop working on it it for now until we know what we're doing? I think a good place to start is: the flow chart, a good meta README and good READMEs for each component. Then we might be better able to see how to improve things for the user.

Perhaps it could look something like this for a SpineOpt user:
 - Install SpineOpt (including Julia if required)
 - Install Toolbox
 - The toolbox installation wizard should have an optional step, that can be skipped if desired, asking if the user wishes to use the Toolbox with Spine Opt - and at this point can offer to install Julia or be pointed to an existing Julia
 - Using the above information Toolbox can provide a pre-configured plugin and/or tool. I.e. a user should be able, within toolbox, to run a SpineOpt model (sqlite file) without having to write a main program file.

**Comment by manuelma** [comment]
I agree. But don't you think it is enough to direct people to the SpineOpt README at this point? It has the skeleton you outline, with everything you need to get SpineOpt working in your Toolbox.

The plugin to me is the next phase. I don't see a plugin as installing OS level components or packages for the user. A plugin just provides the right toolbar icons to build a SpineOpt model (or any model), but again, it doesn't install Julia or SpineOpt. SpineOpt is installed through the comprehensive README.

What do you think?

**Comment by DillonJ** [comment]
The bit that bothers me is that a user who may have no intention of touching or even looking at the Julia constraint code, is required to write Julia code to run a basic model...

I think we should provide the interface between toolbox and SpineOpt and not require the user to write it... even though to us, it seems trivial... I know modellers that bang out papers to beat the band and flatly say: "I don't write code".

**Comment by manuelma** [comment]
That's the plugin interface to me, the next phase. I have something I want to merge, but first would like some opinions:

https://github.com/Spine-project/Spine-Toolbox/issues/1056#issuecomment-783292474

**Comment by DillonJ** [comment]
perhaps you are right... that's the plugin phase - I guess what I'm trying to get as is that toolbox should have the capability to run a Julia tool without having to do any further configuration... if this link can be made nicely during installation and the required information gathered...

**Comment by ererkka** [comment]
Config assistant is still mentioned in the docs: https://github.com/Spine-project/Spine-Toolbox/blob/master/docs/source/setting_up.rst

**Comment by PekkaSavolainen** [comment]
> Config assistant is still mentioned in the docs: https://github.com/Spine-project/Spine-Toolbox/blob/master/docs/source/setting_up.rst#setting-up-spineoptjl

@ererkka Not anymore.

Config assistant is gone. Can we close this issue?
