### ISSUE TITLE
Undo/redo for all spec editors

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1244]
Re #1236

**Comment by soininen** [comment]
Undoing an entire specification in Toolbox has always felt a bit off to me so I will not be sad if we drop it once the specification editors ask for confirmation before closing. In the long run it would not hurt if the specification editors' undo stacks would be persistent over a single Toolbox session so you could continue undoing where you left off if you reopened the editor.

**Comment by manuelma** [comment]
> Undoing an entire specification in Toolbox

I already dropped it! But I'm done with undo/redo for tool specs, will do DT next and we'll be fine.

> undo stacks would be persistent over a single Toolbox session

That's a really cool idea, not difficult to achieve I think.

**Comment by manuelma** [comment]
This is done, please reopen or open new issues if you run into trouble.
