### ISSUE TITLE
Tool logging into Python console broken if more than one project is opened

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1245]
With Use embedded Python Console checked in Toolbox settings:

1. Open project with a Python tool
2. Execute. Tool output goes correctly to the Python Console widget
3. Open another project with a Python tool
4. Execute. Tool output should go to Python Console but it does not. The console remains 'closed' and does not show tool execution.

**Comment by manuelma** [comment]
I can look into this.

**Comment by manuelma** [comment]
Are the two tools called the same?

**Comment by manuelma** [comment]
I think it's fixed now, will keep it open in case we need confirmation.

**Comment by soininen** [comment]
Python console works now as expected for the tool in the second project. Thanks for the fix!
