### ISSUE TITLE
Creating new specification from item's properties tab doesn't select that specification

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1246]
Happened with Tool but probably the same issue appears with other specification-aware project items as well.

1. Start with a brand new project
2. Add a pristine Tool to design view
3. Activate the Tool, click Edit specification icon on the Tool's properties tab
4. Set up the specification, save and close the editor
5. Notice that the new specification is selected in the specification combo box on Tool's properties tab. However, the item on the Design view still shows the exclamation mark icon telling that specification is missing. The exclamation icon is right.

We should make sure the newly created specification is really selected on the item it was created on.

**Comment by manuelma** [comment]
Good idea. I know this is the case for Data Transformer, but I'm not sure we ever implemented it for Tool and Importer. I can take a look, probably reuse the Data Transformer's code.

Btw, does it work correctly for Data Transformer? I'm almost sure it does...

**Comment by soininen** [comment]
> Btw, does it work correctly for Data Transformer? I'm almost sure it does...

No, it is similarly broken on DT.

**Comment by manuelma** [comment]
It did something. I looks like it works now. The solution was to pass the item in the constructor whenever needed. The signal approach was more complex since the form is actually open from two different places: from the ProjectItem instance, and from to ItemSpecificationMenu.

**Comment by PekkaSavolainen** [comment]
Thanks @manuelma, looks like this is solved. After step 4, there's no exclamation icon and the new Tool spec is selected in the Specification combobox in Tool properties like it should. Clicked play immediately after step 4 and the Tool (spec) is executed nicely. Also Data Transformer seems to work similarly.
