### ISSUE TITLE
Config assistant QTextBrowser encoding problems

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1247]
Below is the complete output in the config assistant's own QTextBrowser on Windows. It used to show a lot more information when the output was going to the now removed Process Log. The problem is probably somewhere in the subprocess stdout&stderr encoding part.

```
Your Julia setup:
Executable: C:\Julia-1.4.0\bin\julia.exe
Project: C:\Users\ttepsa\OneDrive - Teknologian Tutkimuskeskus VTT\Documents\SpineToolboxProjects\Python Project\Project.toml
[?25l
Fetching: [
>                                        ]
0.0 %
[2K[?25h
[?25l
Fetching: [>                                        ]  0.0 %
[2K[?25h
```

**Comment by manuelma** [comment]
I did notice. Did we do something special in the Process log? The QProcessExecutionManager hasn't changed...

**Comment by PekkaSavolainen** [comment]
I got this. There's a typo...

**Comment by PekkaSavolainen** [comment]
The rest of the process messages were coming from the stderr stream and the config assistant was not actually listening to that.
