### ISSUE TITLE
Missing zoom buttons in View menu

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1248]
Main window View menu (and maybe the Spine db Editor as well) is missing the -, reset, and + buttons. Looking at the code, these should be added by the command `self.ui.menuView.addAction(zoom_action)` command in add_zoom_actions() method in ToolboxUI class but the buttons do not appear into the menu. The only things I have in the View menu are `Toolbars`, `Dock Widgets`, and the separator. @manuelma can you see the buttons on Linux?

**Comment by manuelma** [comment]
Nice catch! I broke it this morning and just fixed it.

**Comment by PekkaSavolainen** [comment]
Great. I just thought that they may have been removed because they are not the most useful buttons to have in the View menu but then I noticed that the code to add them was still there...

Anyway, thanks.
