### ISSUE TITLE
Install Julia button problem

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1250]
This happens when clicking the `Install Julia` button in Settings->Tools

```
Traceback (most recent call last):
  File "C:\Users\ttepsa\OneDrive - Teknologian Tutkimuskeskus VTT\Documents\GIT\SPINETOOLBOX\spinetoolbox\widgets\settings_widget.py", line 256, in _show_install_julia_wizard
    wizard = InstallJuliaWizard(self)
  File "C:\Users\ttepsa\OneDrive - Teknologian Tutkimuskeskus VTT\Documents\GIT\SPINETOOLBOX\spinetoolbox\widgets\install_julia_wizard.py", line 68, in __init__
    self.addPage(JillNotFoundPage(self))
  File "C:\Users\ttepsa\OneDrive - Teknologian Tutkimuskeskus VTT\Documents\GIT\SPINETOOLBOX\spinetoolbox\widgets\install_julia_wizard.py", line 98, in __init__
    conda_env = os.environ['CONDA_DEFAULT_ENV']
  File "C:\Python38\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'CONDA_DEFAULT_ENV'
```

**Comment by manuelma** [comment]
Did you install `jill`?

**Comment by PekkaSavolainen** [comment]
No, but that's unrelated here. Tip: I'm not on conda.

**Comment by manuelma** [comment]
I know, the wizard doesn't support that setup. I don't think it's worth doing it. We shouldn't even support the case where jill is not installed since users should have all requirements up to date when trying this.

**Comment by PekkaSavolainen** [comment]
Ok, I see the jill not installed message box now. I'm just wondering why not just tell people to do `pip install jill` or update all Spine toolbox requirements and leave conda out of it. Or does jill require a conda environment?

**Comment by manuelma** [comment]
Jill does not require an environment. You're welcome to change the instructions. I made them hyper-tailored to the case where the user follows the instructions in the README to begin with. They are super clear too, I wanted them to be foolproof but then again, if you can improve them please go ahead.

**Comment by PekkaSavolainen** [comment]
After installing jill, Julia installation works like a charm. Nice job! I was just wondering, should we let user's select the Julia version because e.g. SpineOpt may not support  (not sure if it does) the latest Julia. Or did I just miss the option of selecting the version?

**Comment by manuelma** [comment]
No, you didn't miss it. I just made it so it installs the latest one.

You raise a good point, I'm not sure what's best here. SpineOpt runs well in 1.5.3 which is the current release, but the future is uncertain. For example, with 1.6 beta I got errors once...

I think we should install the latest one that is compatible with SpineOpt. We can keep that as a constant in our code and call `jill install [version]`

**Comment by PekkaSavolainen** [comment]
Yes, The latest Julia that is compatible is a good idea. I don't think it's wise to spend time on the 'jill package missing' message box. New users won't see the message box anyway and old users should know what to do. The important thing is that the message box is there.
