### ISSUE TITLE
Add/Update SpineOpt Wizard problem

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1251]
On the second page of the SpineOpt install wizard, there's a Browse button for selecting the Julia Executable. However, when clicking the Browse button, and after finding my julia.exe in the 'Select Julia executable' and then clicking Open, the selected julia.exe file path does not appear to the line edit.

But the actual problem here is that, why do I need to select the Julia executable and the project again, when I already have them on the Settings -> Tools page above the `Add/Update SpineOpt` button?

**Comment by manuelma** [comment]
Aren't the line edits pre-filled with your settings?

**Comment by PekkaSavolainen** [comment]
No. Julia executable is blank and the project line edit shows the place holder text.

**Comment by manuelma** [comment]
Can you describe more your setup? Works well for me.

**Comment by manuelma** [comment]
https://user-images.githubusercontent.com/11472756/109794882-b428c080-7bec-11eb-8021-3c5099da4f27.mp4

**Comment by PekkaSavolainen** [comment]
![issue_1251_missing_julia_executable](https://user-images.githubusercontent.com/43600314/109795954-3e3e4c80-7c20-11eb-80bb-af7c5d0ef463.png)

**Comment by PekkaSavolainen** [comment]
When leaving the Julia Executable blank it should use the path in the placeholder text (Julia from Path).

![issue_1251_missing_julia_executable_from_path](https://user-images.githubusercontent.com/43600314/109796759-3a5efa00-7c21-11eb-9504-ddde0523d53a.png)

**Comment by PekkaSavolainen** [comment]
But the Browse button now works. Thanks.

**Comment by manuelma** [comment]
> When leaving the Julia Executable blank it should use the path in the placeholder text (Julia from Path).

That's what it is trying to do, it finds the julia and prefills the line edit, as seen in the screencast above. I don't know what's missing. Maybe you could debug it, since for me it works?

**Comment by PekkaSavolainen** [comment]
Ok, I'll take a look.

**Comment by PekkaSavolainen** [comment]
I took a look and this seems to be fixed now (see commit msg). I'm not sure how it worked on your (@manuelma) system...

**Comment by manuelma** [comment]
Thanks for looking at this. I think we can replace `julia_settings = QSettings()` by `julia_settings = QSettings("AnyName")` and it will work (without messing with the user settings). It may be that linux is more permisive than windows in this respect. I will do the change now.

**Comment by manuelma** [comment]
I think this works well now. Thank you @PekkaSavolainen

**Comment by PekkaSavolainen** [comment]
Well, commit d09d369 is better than my original solution but it still does not work because you are making a "SpineOptWizardSettings/" key into qsettings and the get_julia_env() function is trying to read the "appSettings/" key.

I propose we don't mess with QSettings at all, skip get_julia_env(), and do this:
```python
    def _show_add_up_spine_opt_wizard(self):
        use_emb_julia, julia_exe, julia_project, julia_kernel = self._get_julia_settings()
        if use_emb_julia == "0":
            if julia_exe == "":
                julia_exe = resolve_julia_executable_from_path()
        else:
            kernel_path = find_julia_kernels()[julia_kernel]
            d = KernelEditor.get_kernel_deats(kernel_path)
            julia_exe = d["exe"]
            julia_project = d["project"]
        wizard = AddUpSpineOptWizard(self, julia_exe, julia_project)
        wizard.show()
```

This way we don't clog the registry with unnecessary stuff.

**Comment by manuelma** [comment]
But it's repeating code we already have! It's a pain having to change it in two places.

I think I have a better solution, let me try it out.
