### ISSUE TITLE
Data connection shouldn't use full path as local files' label

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1255]
Since file resources are now identified by the resource's label, Data connection items should not use full paths as labels for files that are in the project folder since this makes the project impossible to transfer between systems (or just move in the local file system). We could use just the file name as label for local files.

**Comment by PekkaSavolainen** [comment]
I'm all for limiting the usage of full paths (in the UI) to only when we absolutely need to e.g. for clarity.

**Comment by soininen** [comment]
Fixed for now. We might come up with even better resource labels in the future.
