### ISSUE TITLE
Exporter: initial mapping, preview table with new specification

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1258]
Small usability imporovements to Exporter specification editor:

- [x] New specification could have an initial object class mapping
- [x] Preview table could load the preview at editor startup if there is at least one database URL available.

**Comment by manuelma** [comment]
> New specification could have an initial object class mapping

Not sure I like this. It may be ok, but what I'd really want to do is disable all impossible actions until they become possible. In this way, whenever the user opens the form for the first time, they will have only an option: Add mapping. And from there, they can start clicking a see what happens. But as it is now, when the form loads, there's plenty of controls that are active and do nothing, which is confusing.

But overall, I think what we have now is already pretty nice.

**Comment by soininen** [comment]
Since the users initially have only one option (click Add mapping), we should do that automatically for them, i.e. create an initial object class mapping. Importer does the same, by the way.

I agree with disabling controls when they are not usable.

**Comment by jkiviluo** [comment]
> i.e. create an initial object class mapping.

Yes, just one would be great to give a hint want to do when you start.

**Comment by soininen** [comment]
Implemented the tasks in description + disable/enable some widgets as needed.
