### ISSUE TITLE
Bring back the 'Base' Python and Julia Consoles

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1264]
At the moment, user's need to create a Tool and then either a Python or a Julia Tool spec and execute it to get a console started. I think we need to add the option to start a 'base' Python and Julia Console back. By base I mean that it's not tied to any Project Item. It's a really cool feature and at the moment IMO it's hidden. The consoles are handy for demonstration, development and testing purposes and why not for regular user's as well.

This can be achieved simply by adding a context-menu into both Python and Julia Console dock widgets. The actions for starting and restarting the consoles are already in SpineConsoleWidget class.

**Comment by manuelma** [comment]
The problem is it gets a little bit confusing? Maybe we could have an action that opens a separate window with a python or julia console. And we keep the dockwidgets in the main window for the Item consoles exclusively.

**Comment by PekkaSavolainen** [comment]
That's probably a good idea.

**Comment by PekkaSavolainen** [comment]
This is done. See commits above.
