### ISSUE TITLE
DB Editor: No Pivot view option under view group in main menu

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1268]
I'm not sure if this is intentional - but I am expecting to be able to choose between the three views via the options in the main menu under the "view" heading - but currently you only see "stacked" and "graph". I know you can switch to pivot-view by selecting one of the pivot options, but it feels like a work-around - particularly if you don't actually want to change the pivot from what is currently selected.

**Comment by manuelma** [comment]
Intentional, @jkiviluo and I felt it's not worth the extra click. You don't need to change the pivot selection I believe, you can just click in the one you want even if it's already the one selected; and the view will switch to pivot.

**Comment by DillonJ** [comment]
I personally feel it's more intuitive having the explicit pivot-view option. The current system feels inconsistent and makes you wonder if it is a bug or not.

A big reason for this is that it looks like there is already something selected in the pivot group. It would help if this wasn't the case - no pivot option selected if you are not in pivot view.

**Comment by manuelma** [comment]
As you prefer. But what about the one extra click?

**Comment by DillonJ** [comment]
There is probably a default pivot, right? So it's only one more click if you want to change from that? Perhaps one more click is an ok price to pay for it being more intuitive - one click to switch view (like for stacked and graph) and one click to choose your pivot.

However, if you both feel it's better as it is currently, then I would deselect everything in the pivot group if you are not in pivot view.
