### ISSUE TITLE
Exporter: Does not execute

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1269]
Trying to export TradeRES table after some modifications. Execution does not finish (hangs, but I can stop). This is the traceback:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'ParameterDefinitionMapping' object has no attribute '_filtered_query'
```

**Comment by jkiviluo** [comment]
Maybe this helps:
![image](https://user-images.githubusercontent.com/40472544/110307239-5db1ec80-8007-11eb-9742-d60fe829c613.png)

**Comment by jkiviluo** [comment]
Removing the last two mappings allowed the exporter to execute.

**Comment by jkiviluo** [comment]
And when trying to reimplement the mapping with the time series, I managed to crash Toolbox.

```
Traceback (most recent call last):
  File "c:\data\spinetoolbox\spinetoolbox\helpers.py", line 100, in new_function
    return func(*args, **kwargs)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\exporter\widgets\preview_updater.py", line 342, in _load_data
    write(db_map, writer, self._mapping)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spinedb_api\spine_io\exporters\writer.py", line 35, in write
    for row in rows(root_mapping, db_map, title_key):
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spinedb_api\export_mapping\generator.py", line 67, in rows
    regularized, value_column, regular_columns, hidden_columns, pivot_columns, root_mapping.group_fn
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spinedb_api\export_mapping\pivot.py", line 142, in make_pivot
    if not last_pivot_row[-1] and pivot_header[-1]:
IndexError: list index out of range
QThread: Destroyed while thread is still running
```

![image](https://user-images.githubusercontent.com/40472544/110308260-93a3a080-8008-11eb-8a6e-6cb6583a44c2.png)

**Comment by manuelma** [comment]
These are two separated issues.

**Comment by manuelma** [comment]
I think I can fix the two of them, will start with the first one.

**Comment by manuelma** [comment]
@soininen is there a reason why we use pickle instead of custom serialization (from_dict/to_dict)?

**Comment by soininen** [comment]
>  is there a reason why we use pickle instead of custom serialization (from_dict/to_dict)?

We don't use pickle explicitly but that's what Python does when it transfers arguments to ReturningProcess. We could serialize Exporter's specification to a dict and let ReturningProcess to pickle that but I don't see the point. Are we having some trouble implementing `__getstate__()` and `__setstate__()` in `ExportMapping`?

**Comment by manuelma** [comment]
I don't see the point in having `__getstate__()` and `__setstate__()` if we already have `from_dict` and `to_dict`? Their implementation is not straitghforward and we need to maintain it every time we add non picklable attributes. We can call to_dict() on the ExporterSpecification before passing it to `do_work`, and then call from_dict in `do_work`, and it works.

**Comment by soininen** [comment]
I guess we can live with ExportMapping being unpicklable, then.

**Comment by manuelma** [comment]
I think it makes our lives easier to rely on `from_dict` and `to_dict`, in terms of what we do with the `Mapping` class.

**Comment by manuelma** [comment]
@jkiviluo can you share the exporter spec .json file that produces the second traceback, please?

**Comment by jkiviluo** [comment]
{"item_type": "Exporter", "output_format": "Excel", "name": "foo", "description": "", "mappings": {"object_classes": {"type": "objects", "mapping": [{"map_type": "ObjectClass", "position": "table_name"}, {"map_type": "Object", "position": 0}], "use_fixed_table_name": false}, "relationship_classes": {"type": "relationships", "mapping": [{"map_type": "RelationshipClass", "position": "table_name"}, {"map_type": "RelationshipClassObjectClass", "position": 0}, {"map_type": "RelationshipClassObjectClass", "position": 1}, {"map_type": "Relationship", "position": "hidden"}, {"map_type": "RelationshipObject", "position": "hidden"}, {"map_type": "RelationshipObject", "position": "hidden"}], "export_objects_flag": true, "use_fixed_table_name": false}, "efficiency": {"type": "object_parameter_values", "mapping": [{"map_type": "ObjectClass", "position": "hidden", "filter_re": "unit"}, {"map_type": "ParameterDefinition", "position": "table_name", "filter_re": "efficiency"}, {"map_type": "ParameterValueList", "position": -1, "ignorable": true}, {"map_type": "Object", "position": 0}, {"map_type": "Alternative", "position": "hidden"}, {"map_type": "ParameterValue", "position": 4}], "use_fixed_table_name": false}, "node_demand": {"type": "object_parameter_values", "mapping": [{"map_type": "ObjectClass", "position": "hidden", "filter_re": "node"}, {"map_type": "ParameterDefinition", "position": "table_name", "filter_re": "demand"}, {"map_type": "ParameterValueList", "position": "hidden", "ignorable": true}, {"map_type": "Object", "position": -1}, {"map_type": "Alternative", "position": "hidden"}, {"map_type": "ParameterValueIndex", "position": -1}, {"map_type": "ExpandedValue", "position": 4}], "use_fixed_table_name": false}}}

**Comment by jkiviluo** [comment]
When you turn on the live preview (and possibly try to select e.g. node_demand), then it crashes on me.

**Comment by manuelma** [comment]
Hmm, it doesn't crash for me.

**Comment by manuelma** [comment]
I think these two issues are now fixed, please reopen if not?
