### ISSUE TITLE
Exporter: link with importer has not been established

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1270]
I'm trying to import the contents from the exported Excel file. This is not currently possible:

```
[8-03-2021 15:19:09] Opening Import editor for specification import_BB
[8-03-2021 15:19:16] Link established. Interaction between a Exporter and a Importer has not been implemented yet.
[8-03-2021 15:19:19] File does not exist yet.
[8-03-2021 15:19:19] Opening Import editor for specification import_BB
[8-03-2021 15:19:42] Project TradeRES saved
```

The file exists, because I've produced it with exporter (actually multiple files exist, since it's there for whole DB as well as for the scenarios.

This is of course not the final way to modify data between two Spine DBs, but it's the way that would currently allow modifying the data structure using Spine Tools. As a workaround, I should be able to use a data connection in-between, but maybe allowing interaction from exporter to importer is just a simple setting?

**Comment by soininen** [comment]
This is a known missing functionality in Exporter. There is currently no easy way of knowing in Toolbox side which files were written during the last execution in case scenario/tool filters were used. While I try to find a solution for this, it is possible to manually load the file into Importer's specification editor from hamburger -> Load file...

**Comment by jkiviluo** [comment]
You're right. I think there are four cases when going exporter-importer (or in the future db-to-db-manipulator):

1. no scenario filtering and no alternatives dimension in Exporter  (ILL DEFINED when more than one alternative)
2. no scenario filtering and alternatives dimensions in the Exporter
3. scenario filtering and no alternatives dimension in Exporter 
4. scenario filtering and alternatives dimensions in the Exporter  (ILL DEFINED)

We could allow the two combinations that are well-defined, but disallow the other two. 

Tool filtering should be fine in any case.

**Comment by soininen** [comment]
The difficulty I mentioned above is more technical: if there are more than one Exporter executing in parallel, how do we inform the project item in Toolbox what files were written? There used to be some heuristics (also used in GdxExporter) which checked the latest modified files in the item's data directory but that approach was not without its problems.

**Comment by soininen** [comment]
I believe I managed to solve the problems associated with output file discovery. You'll need to re-execute exporters to make it effective.

Note, that the output files now go to `<data dir>/output/` folder instead of  `<data dir>\`.
