### ISSUE TITLE
Exporter: Delete is too greedy

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1274]
Pressing delete in exporter deletes the mapping. Usually my intention has been to delete text contents from a specification field. Delete should be aware in which tab the focus is and act accordingly. When Mappings tab is in focus, it should ask do you want to delete the mapping.

**Comment by manuelma** [comment]
If you can undo the operation, then asking confirmation is not good in my opinion.

**Comment by jkiviluo** [comment]
Right. I didn't realize even to try.

**Comment by manuelma** [comment]
In some google web pages, when you do something they immediately show you an 'undo' button. Perhaps we can try that, we have room in the status bar for something like that?

**Comment by manuelma** [comment]
Asking confirmation might be annoying for people who know about undo.

**Comment by jkiviluo** [comment]
Yes, I fully agree. I would be annoyed now that I know.

Toolbar undo is fine, but may not be a sufficient clue. Also flashing a message in the upper right corner like with DB changes could help (it can say that you can undo).

**Comment by jkiviluo** [comment]
Or our event log could have an undo link (with Ctrl-z as a tooltip).

**Comment by manuelma** [comment]
I like flashing a message with an undo button. Maybe I can try that.

**Comment by manuelma** [comment]
I set the context for the delete action shortcut so now it should only work if focus is on the view.
