### ISSUE TITLE
Exporter: Possible to have more than one specification for the same exporter open at once

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1275]
That's the issue (I just overwrote my changes)

**Comment by manuelma** [comment]
This is a great idea for all spec editors, we can use the tab system we have in the Spine DB Editor. There's a class there that does the tabbing job and we should be able to polish it a little bit and then re use it.

**Comment by jkiviluo** [comment]
Actually, I was trying to say that it shouldn't allow that (same spec open twice), since you can overwrite the changes you just made in the second spec window. However, having the possibility to modify multiple different specs would be nice as you suggest.

**Comment by manuelma** [comment]
Ah ok, I get it now. Hmm maybe we can start with your original idea (avoid duplicate spec editor forms) and then open another issue for my idea if needed.

**Comment by jkiviluo** [comment]
The original issue here is done and it seems sufficient. Closing...
