### ISSUE TITLE
Toolbox workflow: Resource gets lost

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1276]
There is a pattern where an item starts to complain that it does not have any resource, although the resource is there. It can be re-gained by removing the arrow between the item and the next item and the inserting the arrow again.

I can repeat this by running Toward_BB exporter in the TradeRES Toolbox project, then BB_Excel resource gets lost and I have to add it by hand. Even after that the resource is not found before I remove and add the arrow.

**Comment by manuelma** [comment]
I can't make that project work, unfortunately. I'm missing some specs, and probably gams, and I can never help with issues that are reproducible using that project. Is it possible to use another project with minimum requirements to illustrate issues? Or just present the steps from a clean toolbox?

**Comment by jkiviluo** [comment]
You wouldn't need to run GAMS to see the problem. I've tried to put all the specs there, but it seems to be hard to keep these projects portable. In any case I will try to reproduce with something more simple.

**Comment by jkiviluo** [comment]
This should be sufficient. Run Toward_BB and see what happens. You need to reconnect the resource by hand (items/toward_bb/exported.xlsx). The crucial point for this issue is that adding that resource does not remove the exclamation marks.

[Break_resource.zip](https://github.com/Spine-project/Spine-Toolbox/files/6103844/Break_resource.zip)

**Comment by soininen** [comment]
This is probably same issue as #1249

**Comment by jkiviluo** [comment]
Yes, it's really just that adding a reference does not remove the exclamation that there is no reference (from the item in question or the precedent if it's waiting for that file).

**Comment by soininen** [comment]
I ended up reimplementing the entire resource passing mechanism on Toolbox side. @jkiviluo can you confirm that the problem here is gone now?

**Comment by soininen** [comment]
This particualr issue has indeed been fixed.
