### ISSUE TITLE
Exporter: hang/crash when changing parameter dimensions too quickly

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1277]
Exporter's specification editor hangs/crashes if you click e.g. the parameter spin box too quickly while live updates on the preview table are enabled.

**Comment by soininen** [comment]
I had forgotten to move preview's worker to its thread so the workers were executing on the main thread. Fixing that seems to fix the crashing issue on me but with parallel processing you never know.... So @manuelma, can you try if the specification editor still crashes on you? Maybe your clicking fingers are faster than mine?

**Comment by manuelma** [comment]
I can still make it crash sort of easily. Obviously users won't be doing this and if they do and it crashes, they'll be more careful next time. But we definitely need to solve this since you lose all your changes when it happens.

**Comment by soininen** [comment]
I am sure user will be doing exactly this. I'll take another look. Thanks for trying it out!

**Comment by manuelma** [comment]
I was having similar problems with the graph view. I remember I solved them by using a lambda when connecting to a slot that might be being executed at the time of making the connection.

**Comment by soininen** [comment]
I can make the editor crash again. Seems to need a specific button clicking technique to do it fast enough.

Thanks for the tip! I'll check that lambda technique. Maybe it is such black magic that is required here?

**Comment by manuelma** [comment]
I haven't used `QThreadPool` so I can't say if there's something wrong. I can't make it crash anymore but I get this every time I press the spinbox
```
QObject::moveToThread: Current thread (0x56221f644310) is not the object's thread (0x56221c0846e0).
Cannot move to target thread (0x56221f644310)
``

**Comment by soininen** [comment]
> I get this every time

Curious. I didn't get that on Windows. Maybe there is something peculiar happening on Linux. I'll investigate.

**Comment by soininen** [comment]
Linux was actually doing the right thing there; one should not move QObjects like that across threads. Anyway, I believe we don't actually need to move the object at all.
