### ISSUE TITLE
Change project name when duplicating a project with File->Project save as...

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1279]
When you save the project with a new name (duplication), the project name stays the same (original name). Also, when you copy paste a project in the file system, the same happens. However, that's awkward, especially when switching between projects from the file menu and there are multiple instances of the same project name (but they are different projects). 

A better approach could be to automatically rename the project name based on the folder name where the project is. You could then rename it to something else, but whenever the underlying folder name changes it should revert to the folder name (the assumption being that the project is copied in order to branch a new project).

**Comment by PekkaSavolainen** [comment]
> when switching between projects from the file menu and there are multiple instances of the same project name (but they are different projects).

Note that there's a tooltip in the recent projects list that tells the path to the project directory. You can then rename the newer project quite quickly from Settings->Project and the recent project list will be updated automatically.

**Comment by jkiviluo** [comment]
Yes, that's possible. I didn't at first realize that I could change project name in the settings. I think it's too hidden there. Project 'settings' should maybe be separate menu item under 'new project'. 

We should also have 'close project' - often that's what you want to do when you want to modify project.json by hand. I know you can just open another project, but I've had to explain that several times (it's not clear for new users).

Maybe these are separate issues or should we have a list of sub-issues here?

**Comment by PekkaSavolainen** [comment]
Well the original issue in the title and description is now done. I'll open a new issue about Close project.

**Comment by PekkaSavolainen** [comment]
> Yes, that's possible. I didn't at first realize that I could change project name in the settings. I think it's too hidden there. Project 'settings' should maybe be separate menu item under 'new project'.

I'm not sure I know what you mean here. The File->New Project opens the `select directory dialog` (provided by the OS). We used to have an additional window there where user's could give the project name and desc. before creating the project but that was dropped to streamline creating a project. People can change the name of the project quite easily later (if they find the Settings->Project page, that is).

> EDIT: We could in future have project tabs, so it would make sense to separate project settings from the general settings. EDITEDIT: or maybe it's enough to be able to have multiple Toolbox instances like we now have. I don't know.

We have had the separation between project settings and generic settings almost from the start. Project settings are saved to project.json and generic settings are saved into registry. In the Settings window, there is the `Project` page that contains the Project settings (just name and description at the moment). These modify project.json file. The other settings on `Generic`, `Tools`, and `Db editor` page are saved to registry. If we make something to be a project setting, e.g. the selected python kernel, the UI to select this should be moved to the `Project` page.

Please make new issue(s) if you have ideas to improve any of these. I'm happy with how it's organized now so it's difficult for me to think of improvements.

**Comment by jkiviluo** [comment]
> (if they find the Settings->Project page, that is).

That's it, finding it is not obvious enough. So, there should be File -> project settings (below e.g. 'new project') and it's own dialog.

I can make it into an issue, if we agree it should be changed.

**Comment by PekkaSavolainen** [comment]
I don't know. Are you looking for something like this maybe

![issue_1279_settings_redefined](https://user-images.githubusercontent.com/43600314/110798423-d53f8000-8282-11eb-9601-2c64dc22673b.png)

**Comment by manuelma** [comment]
Hmm I don't think I like that screenshot. What's the issue we're trying to solve with that? Is it that we have entries with the same name in the 'Recent projects' submenu? I would just add some disambiguation note right there, not in the ToolTip role but directly in the Display role...

**Comment by jkiviluo** [comment]
If I get that right, Pekka is suggesting to have project settings (and also some other settings) as separate sub-items in the file --> settings. I think that still hides the project name change (and other possible project settings) too far. I would have it as a separate item at the higher level (directly under file), e.g. between open recent and save project. 

The original issue, where the project name was to be renamed automatically, is now done for the 'Save as' part and that may well be sufficient. I was also hoping that Toolbox could recognize also when someone has duplicated a project in the file system and then uses Toolbox to open the new copy with a different folder name than before (and then automatically rename based on the new folder name). That's probably too much and is covered well enough by making the project settings more visible (you can change the project name when you want).

I guess, as Manuel is suggesting, the open recent could have more information, like the folder path for the project. That can be sometimes awfully long, but maybe it's ok to show - there should be real estate on the screen for that.

I would keep the other settings as tabs in the 'settings'. I think those are bit easier to use than sub-items in the File --> settings.

**Comment by PekkaSavolainen** [comment]
> Is it that we have entries with the same name in the 'Recent projects' submenu?

Like @jkiviluo said, does not happen anymore when using Project save as...

>  I was also hoping that Toolbox could recognize also when someone has duplicated a project in the file system and then uses Toolbox to open the new copy with a different folder name than before (and then automatically rename based on the new folder name).

Yeah, I don't think this is worth doing (to be honest). To accomplish this we would have to add an entry to project.json to keep some information on when the project is not in it's original directory or something like that. It would be a mess.

About the screenshot above. I don't really like it either. Let's scrap it. So, @jkiviluo is suggesting that we just add a menu item below `Open recent`, called `Rename project...` that would show a dialog where you can type in the new project name. I did not really like the idea first but then I noticed that there is a similar menu item in PyCharm :) **I'll add it**. But I think we have to be careful with these additional ways to accomplish same things. It's always more code to maintain and IMO just confuses users at some point.

**Comment by manuelma** [comment]
If we go with that we should remove the project page in settings, right?

**Comment by jkiviluo** [comment]
> If we go with that we should remove the project page in settings, right?

Yeah, I was also thinking that this is moving project settings away from other settings to the place where we have the other actions related to projects (open project, etc.).

**Comment by PekkaSavolainen** [comment]
I'm just duplicating the rename project setting. You can do it in two places after this. I'm not touching the Settings->Project page because there will be other things coming to the Settings->Project page later. We cannot remove it for this.

**Comment by PekkaSavolainen** [comment]
Done.

@jkiviluo Above you suggested 'project tabs', Please make a new issue about this.
