### ISSUE TITLE
Increase the number of recently opened projects

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1280]
The list of recently opened projects is currently 5 long. It could be something like 20 to be more convenient.

**Comment by PekkaSavolainen** [comment]
How about 10? I think 20 is going to be handy for only a few 'super' users and it kind of feels like it defeats the purpose of this recent projects menu. Makes it harder to find the one you're looking for and there's going to be much 'broken' links after user's move the folders around.

**Comment by PekkaSavolainen** [comment]
Decided to go with 20 like requested. It does not look too crowded after all.
