### ISSUE TITLE
Manage item connection information in a single place

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1281]
The `Connection` class in Engine is used to hold information on project item connections and filters. Additionally, we duplicate the connection information in the DAG handler. This double bookkeeping is not ideal. We should consider merging the filter configurations held by `Connection` objects into the DAG handler and get rid of the connection list altogether.

**Comment by manuelma** [comment]
How about getting rid of the DAG handler? It's a lot of bookkeeping indeed and we don't use it a lot. I believe we could just build dags as needed from the connections' information.

**Comment by soininen** [comment]
👍 I don't really care which we do it as long as the double bookkeeping is gone.

**Comment by manuelma** [comment]
Thank you @soininen I ended up removing the dag handler. Removing `Connection` seemed a lot more difficult and having the `Connection` as a class is quite good and versatile - we have a lot of good methods there and can keep adding more.
