### ISSUE TITLE
SQLITE Export Format

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1284]
This was discussed recently during our weekly SpineOpt calls and the last Toolbox development call.

As we move forwards with Spine and start generating meaningful results datasets, we need more functionality in terms of viewing and and processing results which will most often be timeseries results. The DB editor with it's pivot and plot functionalities are very useful but we need something more convenient that can be used as a basis to query more generically.

The idea we had for that was to produce a db with a flatter structure that can be used to query more easily. @manuelma did something on this which eventually became the basis of the new excel export. What we effectively need is an sqlite version of this that can be queried easily by generic sql query tools or even using MS access via ODBC. 

The specific requirements are as follows : @manuelma please chip in here and correct me where needed
 - Convert a regular SpineFormat output DB to a flat structure SQLITE database
 - Each object/relationship class gets a new table where all outputs are written with timeslice as a row index, involved stochastic scenarios, alternatives,  objects,  parameters as column headings
 - Ideally this could be specified as a default output option when calling run_spineopt, with multiple alternatives/runswritten to the same db

E.g.

`alternative__stochastic_scenario__unit`

| t  | alternative | stochastic_scenario | units_on | units_available | units_started_up | units_invested_available |
|-------------------------------------|-------------|----------------------|-----------|-----------------|--------------------|----------------------------|
| 2020-01-01 00:00 -> 2020-01-01 00:00 | Base | S0 | DB1 | 1 | 1 | 1 | 1 |
| 2020-01-01 01:00 -> 2020-01-01 02:00 | Base | S0 | DB1 | 1 | 1 | 1 | 1 |
| 2020-01-01 02:00 -> 2020-01-01 03:00 | Base | S0 | DB1 | 1 | 1 | 1 | 1 |
...

`alternative__stochastic_scenario__unit__node__direction`

| t | alternative | stochastic_scenario | unit | node | direction | unit_flow | 
|---------------------------------------------|-------------|----------------------|------|-------|-----------|------------|
| 2020-01-01 00:00 -> 2020-01-01 00:00 | Base | S0 | DB1 | elec_node | to_node | 400 |
| 2020-01-01 01:00 -> 2020-01-01 02:00 | Base | S0 | DB1 | elec_node | to_node | 400 |
| 2020-01-01 02:00 -> 2020-01-01 03:00 | Base | S0 | DB1 | elec_node | to_node | 400 |
...

I believe the implementation solution is to provide an SQLITE export format option for the existing exporter tool, but I'll leave that open just in case. In this case, there would be a few additional functionalities required that were discussed on today's call mainly a prepacked default output specification/template

@soininen @manuelma any thoughts?

**Comment by soininen** [comment]
Thanks a lot for everyone sending databases in my way! It is nice to see some real-life data once in a while.

As @manuelma said above, it isn't really much more than subclassing `Writer` if we don't need any modifications to what we already have in `spinedb_api`.

**Comment by soininen** [comment]
There is now initial support for sqlite in Exporter. Note, that the sqlite backend expects certain format from the tables so you cannot build your mappings as freely as when exporting e.g. csv. In particular, pivot tables are a no-go.

What is currently needed to get the backend working:
- Every table must have a name.
- The first row on each table is used as column names. Use the Header field or 'column header' position for all visible data.
- Empty columns don't work so make sure the table is 'compact' by adjusting column positions accordingly.

I am painfully aware we don't have a proper introduction to Exporter in our user guide. Also, Exporter's diagnostics should be improved in the future to inform users if their mappings are not compatible with the chosen format.

**Comment by manuelma** [comment]
Nice job @soininen 

> Empty columns don't work so make sure the table is 'compact' by adjusting column positions accordingly.

In Qt designer, when one is creating a form or grid layout, there's an option called 'optimize layout' to make the layout compact automatically (because one typically leaves spaces). I think we can have something like this here, e.g. a push button that reads 'Optimize mapping' and automatically removes all empty columns?

**Comment by soininen** [comment]
> In Qt designer, when one is creating a form or grid layout, there's an option called 'optimize layout' to make the layout compact automatically (because one typically leaves spaces). I think we can have something like this here, e.g. a push button that reads 'Optimize mapping' and automatically removes all empty columns?

We reshuffle the column already a bit, e.g. you can 'insert' a column between existing columns in Exporter. I have been playing with the idea of having a 'compact' button there or a 'keep compact' checkbox. Maybe even auto-compact the table depending on the chosen output format? Gdx will surely need such functionality, too.

**Comment by DillonJ** [comment]
I'm not sure if this is relevant here - but given that a purpose of this functionality will be to subsequently run further queries on the data - we may have queries expecting a consistent format. It may be that some outputs are empty for a particular run but that might not always be the case - so we might want to be outputting the empty columns - but I guess this isn't an issue because the compact format will be optional?

**Comment by soininen** [comment]
With 'empty columns' I meant columns that don't have any data (object classes, parameter values, etc.) associated with them. Sorry for the confusion.

**Comment by manuelma** [comment]
But @DillonJ point stands. What about writing NULL to those empty fields?

**Comment by soininen** [comment]
> But @DillonJ point stands. What about writing NULL to those empty fields?

Can you give an example? I think I am missing something here.

**Comment by manuelma** [comment]
> Empty columns don't work so make sure the table is 'compact' by adjusting column positions accordingly

> With 'empty columns' I meant columns that don't have any data (object classes, parameter values, etc.) associated with them

To understand, an empty column is a column that's mapped (some mapping component has `position` equal to that column), but there's no data in the db for that element? So that column should be filled with NULLs.

**Comment by DillonJ** [comment]
> To understand, an empty column is a column that's mapped (some mapping component has `position` equal to that column), but there's no data in the db for that element? So that column should be filled with NULLs.

Thanks @manuelma that's what I was getting at

**Comment by soininen** [comment]
Alright, I believe I get it now. We have support for this in `spinedb_api` already (`set_ignorable()`) but the feature is just not yet exposed to users in Exporter. We do use it behind the scenes with parameter value lists, though.

**Comment by soininen** [comment]
Exporter now sets all SQL table columns as nullable and Specification editor has support for ignorable (Nullable) submappings.
