### ISSUE TITLE
Close Project

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1288]
Add a new entry to File menu to close a project.

From a comment in Issue #1279.

**Comment by PekkaSavolainen** [comment]
Done by commit above. Btw, @manuelma I noticed that Spine Db Editor window(s) is not closed when closing the app so the `File->Close project` option does not do it either. Is this by design?

**Comment by manuelma** [comment]
Not sure I can call it "design" but definitely intentional. Opening a different project doesn't close it either. If you prefer to close it at some point I don't mind either.

**Comment by PekkaSavolainen** [comment]
Finishing touch done by commit above.

**Comment by PekkaSavolainen** [comment]
User(s) requested that Spine Db Editors (and other main windows) should not be closed when closing a project. This is done in commit 139b479.

**Comment by jkiviluo** [comment]
When closing the project, you get a dialog that does not let you do that if you have unsaved changes. There should be an option to discard changes. That's often the reason you want to close it - not save your mistakes.

**Comment by PekkaSavolainen** [comment]
Are you talking about 'mistakes' on Design View or in Spine Db Editor or in the other editors? They all have their own separate undo stacks. If we would close all Spine db editors, importer & exporter spec editors when closing the project it would be beautiful. You could select whether to discard or save the changes for each window separately.

If you have unsaved changes e.g. in your spine db editor and in your importer spec editor, closing the project (as it is now implemented) works. The unsaved changes refer to the changes in Design View (e.g an item was moved). We can of course discard the changes in Design View when closing the project but this does not affect the undo stacks in spine db editor and importer & exporter spec editors. This is the consequence of not closing the other windows when closing the project. 

I don't really know what to do here anymore. I'd just like that `Close project` should do what it says (close everything).

**Comment by manuelma** [comment]
Spine DB editor, Importer spec editor, etc, are not attached to any particular project. I don't see why we need to close them with the project, or even with the toolbox. Don't see the advantage, really. Also, the user might really want to keep windows opened and we'd close them in their face?

I understand the problem that @jkiviluo is having. Selecting Close project should show the same dialog we show when switching projects with dirty changes, a dialog that offers to save changes or discard them. Why would we force to save changes when closing project??

**Comment by manuelma** [comment]
I just implemented my idea. Now the behavior of closing the project is aligned with that of closing the app. Depending on 'Save project at exit' setting, we may prompt the user about what to do with dirty changes.

We could rename 'Save project at exit' to 'Save project before closing' or something like that, what do you think?

**Comment by PekkaSavolainen** [comment]
I was just wondering should we close_project() in restore_project() and in create_project()? Probably could save a few lines there and we could have the same 'save or discard' dialog show up. Now it just happily opens another project and discards the changes without asking anything.

**Comment by manuelma** [comment]
You're right, I think we should do it, for consistency.

**Comment by PekkaSavolainen** [comment]
Should be done now but I'll leave this issue open for a while, in case there's something I missed again.

**Comment by jkiviluo** [comment]
Seems to be fine. Thanks!
