### ISSUE TITLE
Relative path of cmd line argument not respected

### ISSUE THREAD

**Issue by ererkka** [Spine-project/Spine-Toolbox#1289]
After just opening a project where there are command line arguments which are relative paths, the app makes the following changes into my *proejct.json*:

```diff
             "cmd_line_args": [
                 {
-                    "type": "path",
-                    "relative": true,
-                    "path": "data/case118.m"
+                    "type": "resource",
+                    "arg": "C:\\Users\\ERERKKA\\OneDrive - Teknologian Tutkimuskeskus VTT\\Projects\\Spine\\Toolbox projects\\reduce_model_demo\\data\\case118.m"
                 }
             ],
```
Saving this it would make the project not portable.

### Expected behaviour

No changes in the *project.json* if not modifying the project, and the path should stay relative.

**Comment by soininen** [comment]
Is this file coming from a data connection?

**Comment by soininen** [comment]
> No changes in the project.json if not modifying the project

We are constantly updating the `project.json` structure so expect changes. Toolbox give a notification in Event log when it upgrades the file and you also get a backup if you need to roll back.

**Comment by jkiviluo** [comment]
> Is this file coming from a data connection?

Looks like it.

It would be helpful to get these working, portability is important. We should also think how to resolve the cases when the file is not portable (e.g. pointing to a tool executable outside of the project). I think I once saw that Toolbox recognized this and asked for a new location in the event log. Should test more...

**Comment by soininen** [comment]
@ererkka Are you using latest Toolbox? If so, could you try the following:

- Open the project
- Activate the tool
- Delete all cmd line argument using the minus icon
- Readd all arguments
- Save the project

How does `project.json` look after that?

**Comment by ererkka** [comment]
It changed to `"resource"` type, it was probably not updated after adding the Data Connection.

```diff
             "cmd_line_args": [
                 {
-                    "type": "path",
-                    "relative": true,
-                    "path": "data/case118.m"
+                    "type": "resource",
+                    "arg": "case118.m"
                 }
             ],
```

**Comment by soininen** [comment]
That is how it is supposed to work. The absolute path was an unfortunate artefact from `project.json` upgrade.

We are nowadays identifying files by their resource *label* rathen than path. If a file is in the project directory, Data Connection will label it by just the file name, in this case `case118.m`. I'm now wondering, though, if we actually want to add the relative path component there, e.g. `data/case118.m` or even `<project>/data/case118.m`.

**Comment by jkiviluo** [comment]
> I'm now wondering, though, if we actually want to add the relative path component there

Probably, since there can be files with the same name but different sub-dir.

**Comment by jkiviluo** [comment]
> or even `<project>/data/case118.m`

This is very interesting. There is a clear need to be sharing stuff between projects (e.g. you may want to maintain separate git repositories for different parts of a larger project where multiple models are running from the same DB as in TradeRES). Is this enough? What problems there would be? At least Toolbox would need to be aware of projects and their locations (I guess that could just be a JSON file).

**Comment by soininen** [comment]
> This is very interesting.

Sorry for not making myself clear here. By `<project>` I literally meant `<project>`, not the project's name (although that would be very cool feature! Very difficult to implement, too).

The idea would of the `<project>` token would be to just tell users that the files is in the project folder. Kind of how `~` referers to user's home dir on some systems.

**Comment by jkiviluo** [comment]
Ok, too bad. Maybe something for another day.

**Comment by soininen** [comment]
I think Data connections labels need a separate discussion, see  #1290.

**Comment by soininen** [comment]
This issue is not a bug but a known effect caused by `project.json` upgrade that needed a user intervention.

**Comment by ererkka** [comment]
Thank you for quick help!

**Comment by soininen** [comment]
> Thank you for quick help!

Glad to be of help! I am afraid, though, that you'll have to reset those command line arguments again if we end up changing Data connections labels. Luckily, things should stabilize again once we've done that.
