### ISSUE TITLE
Data connection resource labels

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1290]
We are nowadays labeling all our resources. The label acts as a permanent reference which allows the underlying file path or URL to change without affecting other project items that use the label to identify a resource. For example, Data stores label database URLs as `db_url@<data store name>`. Labels also allow multiple files to be packed behind a single label which is used in Exporter which may produce a variable number of output files.

I'd like to open a discussion on how Data connection should label its files. Currently:
- references outside project dir are labeled by their full path, e.g. `C:\data\data.csv`
- references inside project dir are labeled by the file name regardless of if the file resides in project root or in a subdirectory, e.g. `data.csv`
- data files are labeled by the file name, i.e. same as references inside project dir, e.g. `data.csv`

Full paths for files outside the project dir are fine but I am wondering if the labels for files inside project dir are confusing?

Some possible improvements for labels for references:
1. Use subdirs for local references, e.g. `subdir/data.csv` instead of `data.csv` (normalize to POSIX path separators for interoperability, too!)
2. Use subdirs and a `<project>` token (literally `<project>`!) to hint that it is a local file, e.g. `<project>/subdir/data.csv`

Some possbile improvements for labels for data files:

3. Use similar naming to Data Stores to hint the file is a data file, e.g. `data.csv@<Data connection name>`

Personally, I prefer options 2 and 3. We can keep the current status quo, too. Any opinions on this? Any other options?

**Comment by jkiviluo** [comment]
I like the explicitness of 2 and 3. They wouldn't hurt (bit of coding though) and may save from pain later.

**Comment by PekkaSavolainen** [comment]
Yes, 2 and 3 would be very good improvements.

**Comment by DillonJ** [comment]
@soininen What are your feelings about this now? Can it be closed or does it need to be addressed?

**Comment by soininen** [comment]
I think we should proceed with this one.

**Comment by ererkka** [comment]
I just recently opened a project (created by another person) with some Data Connection references. The files were not actually there, so it seemed that Toolbox silently removed those references. If I had saved the project those references would have been lost. Would these reference labels help in this kind of situation? I would have expected a warning that a referenced file was not found.

Option 1: Definitely the full (absolute or relative) path should be stored, just file name is not enough as there can be many files with the same name. Absolute paths should be supported as well (shared network drives etc.).
Option 2: Some kind of label to the project root folder could be usable. For example, VS Code has `${workspaceFolder}` (https://code.visualstudio.com/docs/editor/variables-reference). 
Option 3: I did not understand this.

**Comment by soininen** [comment]
> Would these reference labels help in this kind of situation?

The quickest remedy would be to warn users about missing files rather than just silently drop the references. We'd need to push the idea of labels being something like 'project wide variables' to make them really helpful in identifying missing resources.

**Comment by soininen** [comment]
I ended up preprending file paths that are withing the project directory by `<project>` and file paths that are in DC's data directory by `<DC name>`. The `@DC name` felt like too much, at least for now.

Also, Data connections should not drop missing references anymore but instead warn users in several different ways.
