### ISSUE TITLE
Case sensitivity in scenarios and alternatives

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1302]
I had managed to remove Base from my DB and had imported base instead. This led to issues further down in the workflow.

We need to have case sensitivity in classes, entities and parameters, since some tools may require that. However, alternatives and scenarios are used inside Toolbox only (at least so far). Would it make sense to make them case insensitive to avoid the inevitable case misspellings? Or is there some good reason to keep the sensitive? Being consistent is one reason, but maybe not that important in this case?

**Comment by manuelma** [comment]
I'm not a fan of case in-sensitiveness. I think it would make things worse, because now I need to remember what's case sensitive and what's not. I prefer having to remember that my alternative is called Base and not base...

**Comment by jkiviluo** [comment]
I am sympathetic to that point of view. I'm also bad at remembering what case I happened to use. Anyone else has feelings about this?

I could also accept a warning when e.g. an alternative with same letters but different capitalization is entered to the alternative table.

**Comment by manuelma** [comment]
> Another option is a warning when e.g. an alternative with same letters but different capitalization is entered to the alternative table.

I think we can do this at 'Import API level'.

**Comment by soininen** [comment]
I don't have strong feelings either way and since I don't really use databases to anything productive I cannot even view this in user perspective.

If we are unsure we should keep things case sensitive as it is easier to make things case insensitive later than reverting insensitivity. The latter would break a lot of client-side assumptions.

**Comment by DillonJ** [comment]
Looks like a decision is needed here... perhaps you can extract one @soininen ?

**Comment by DillonJ** [comment]
Actually - feels like there is no strong consensus that the behaviour, which is currently consistent with other objects, be changed - so closing this unless @jkiviluo feels like the discussion needs to be reopened.
