### ISSUE TITLE
Unable to launch Tool with DB url as argument

### ISSUE THREAD

**Issue by jimhommes** [Spine-project/Spine-Toolbox#1304]
I'm trying to read a SpineDB using a Python script, but unfortunately I get an error when trying and the program is unable to stop/start the process after trying. To recreate:

1. Create new Project
2. Create a fresh SpineDB
3. Create a Tool box with e.g. the following Python code
```
import sys

print(sys.argv[1])
```
4. Pass `db_url@Data Store 1` as Tool argument
5. Try to execute

For me this Traceback is thrown:
```
Traceback (most recent call last):
  File "e:\dropbox\workspace\spine-toolbox\spinetoolbox\widgets\toolbars.py", line 132, in execute_selected
    self._toolbox.project().execute_selected()
  File "e:\dropbox\workspace\spine-toolbox\spinetoolbox\project.py", line 592, in execute_selected
    self.execute_dags(dags, execution_permit_list, "Executing Selected Directed Acyclic Graphs")
  File "e:\dropbox\workspace\spine-toolbox\spinetoolbox\project.py", line 474, in execute_dags
    self._execute_dags(dags, execution_permits)
  File "e:\dropbox\workspace\spine-toolbox\spinetoolbox\project.py", line 496, in _execute_dags
    worker = self.create_engine_worker(dag, execution_permits, dag_identifier, settings)
  File "e:\dropbox\workspace\spine-toolbox\spinetoolbox\project.py", line 515, in create_engine_worker
    items[name] = project_item.item_dict()
  File "C:\Users\Jimho\AppData\Local\Programs\Python\Python37\lib\site-packages\spine_items\tool\tool.py", line 368, in item_dict
    d["cmd_line_args"] = [arg.to_dict() for arg in self.cmd_line_args]
  File "C:\Users\Jimho\AppData\Local\Programs\Python\Python37\lib\site-packages\spine_items\tool\tool.py", line 368, in <listcomp>
    d["cmd_line_args"] = [arg.to_dict() for arg in self.cmd_line_args]
AttributeError: 'str' object has no attribute 'to_dict'
```

**Comment by soininen** [comment]
I just tried this with the latest Toolbox and it seems to be working fine for me.

Are you trying to open an existing project? `project.json` has changed recently and sometimes you many need to recreate the command line parameters to make it work.

**Comment by soininen** [comment]
Also, could you pull the latest Toolbox, build that test project of yours from scratch and try it? If it fails, could you zip the project and upload it here so I can dissect it?

**Comment by jimhommes** [comment]
I was surprised to see that I wasn't on the most recent commit. However, I tried again with a new project and unfortunately same result. I've attached the test project.
[test.zip](https://github.com/Spine-project/Spine-Toolbox/files/6162301/test.zip)

**Comment by soininen** [comment]
It seems you forgot to save the project and `test.py` file. Can you try again?

**Comment by jimhommes** [comment]
Ah sorry, my mistake. To be more exact: exception also occurs when saving project when the argument line is added. So in this project that line should still be added
[test.zip](https://github.com/Spine-project/Spine-Toolbox/files/6162419/test.zip)

**Comment by soininen** [comment]
How do you exactly add the command line argument? I have a feeling that is the crucial thing here.

**Comment by jimhommes** [comment]
By selecting `db_url@Data Store 1` under `Available resources` and clicking the button on the left just above `Available resources`

**Comment by soininen** [comment]
Alright! Now I can see what is happening. I will fix that button. Meanwhile, please try dragging and dropping `db_url@Data Store 1` from Available resources to Type new arg here... line in Command line arguments box.

**Comment by jimhommes** [comment]
Great, that works! Thanks

**Comment by soininen** [comment]
@jimhommes can you confirm the button works after pulling the latest changes? Sorry for not noticing that the button was broken sooner. I am too used for the drag and drop method it seems.

**Comment by jimhommes** [comment]
Yes, the button now works as well. Thanks for picking it up!
