### ISSUE TITLE
Exporter pivot issue

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1306]
Exporter seems to misinterpret alternative into 'pivot' in this case:

![image](https://user-images.githubusercontent.com/40472544/111589751-ee3db900-87cd-11eb-913c-03ad4664b865.png)

I made it into column 4 and it seems to act that way, but exporter shows that it's in pivot and I cannot change it anymore.

**Comment by soininen** [comment]
I guess it is the extra table name that is not taken into account when declaring the "tail" mapping which in this case should be Parameter values, not Alternatives.

**Comment by soininen** [comment]
It is actually interpreting Alternative correctly as 'in pivot' since Parameter values is 'hidden'. Looks like the preview is not showing the table correctly, though, as the parameter value is not hidden there.

**Comment by jkiviluo** [comment]
Ahh. But I should be able to change alternatives into a column and the parameter values should switch to pivot.

**Comment by soininen** [comment]
> But I should be able to change alternatives into a column and the parameter values should switch to pivot.

Currently it works if you unhide Parameter values: this automatically puts them 'in pivot'.

**Comment by jkiviluo** [comment]
>Currently it works if you unhide Parameter values: this automatically puts them 'in pivot' freeing Alternatives for editing.

Yes. We just need to make it more intuitive for the user.

**Comment by soininen** [comment]
Preview table should be fixed now. Lets return to improving the user experience sometime in the future.

**Comment by soininen** [comment]
I tried to make the Mapping specification table a bit more intuitive and "fluid". Hopefully the experience is a tad bit nicer now.
