### ISSUE TITLE
Specification editors: text focus disappears

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1307]
When renaming things in the specification editors, the focus can suddenly go away from the text editing and I need to refocus with a mouse click. May be related to the undo action. In these cases the widget updates the name and gives the flash tip with undo option even though I'm still in the middle of writing. I'm not sure how to reproduce, but it happens quite often.

**Comment by soininen** [comment]
I think I have noticed this too and I have a feeling it is the undo notification widget that may steal the focus.

**Comment by manuelma** [comment]
I remember noticing this and implementing something so the notification widget would remember who had the focus, and then giving it back. Looks like it's not working... will take a look.

Btw, is the undo notification widget useful or just annoying? I can't make my mind...

**Comment by soininen** [comment]
> Btw, is the undo notification widget useful or just annoying? I can't make my mind...

I find its position quite annoying since it usually blocks the hamburger menu or some other widget. Also, it pops up too often. I wonder if we could rather have a single popup window or some other message appearing once when you open a specification editor reminding about the existence of undo/redo.

**Comment by PekkaSavolainen** [comment]
Does the notification widget need to have the focus ever? setFocusPolicy(Qt.NoFocus)?

**Comment by manuelma** [comment]
> I find its position quite annoying since it usually blocks the hamburger menu or some other widget

**Comment by manuelma** [comment]
Also, a setting to disable it everywhere?

About reminding users of undo/redo. The window title gets a [*] appended when the window is dirty. That also should be interpreted by the informed user as an evidence about the possibility of undo?

**Comment by PekkaSavolainen** [comment]
I would not miss the 'undo' button in the notification if it would disappear some day...

**Comment by jkiviluo** [comment]
I like that you can turn the messages off. I think the messages are nice for the new users to get an understanding how Toolbox operates.

**Comment by jkiviluo** [comment]
Is it also so that the dictionary where the name that is being changed is, is updated during the writing process? Couldn't it updated only once the focus leaves the text box?

**Comment by manuelma** [comment]
> Is it also so that the dictionary where the name that is being changed is, is updated during the writing process? Couldn't it be updated only once the focus leaves the text box?

How do you mean?

**Comment by jkiviluo** [comment]
What I mean is that the undo message happens when I'm still writing. Why would it do that? Why not just make the message only once the text change is finished (focus moves away from the the text box that was edited).

**Comment by manuelma** [comment]
Ok, I get it now. It doesn't happen for all line edits, but for some of them (like name and description). I will try to fix that too.

**Comment by PekkaSavolainen** [comment]
Yeah, the name LineEdit (maybe others too) in the exporter spec editor uses the TextEdited signal which fires up the notification every time the user enters a new letter. I'm not sure why it was used here but maybe there is a reason.

**Comment by manuelma** [comment]
It's because often the user enters the name but never leaves the text edit, which means we can't rely on `editingFinished`. So we use `textEdited` together with a timer (so the notification is not fired *every time*, but only ever 100 ms which in practice boils down to almost the same). But I have an idea how to make this better.

**Comment by PekkaSavolainen** [comment]
> It's because often the user enters the name but never leaves the text edit, which means we can't rely on editingFinished

I handled this problem in Gimlet by thinking what the user does next even if the command line edit still has the focus, If the user presses the execute button, the execute button should take the focus. This way the editingFinished signal will be emitted.

**Comment by manuelma** [comment]
Ok, but what if the user stays in the line edit after changing the name? As a user, I think I would expect the change to be acknowledged.

**Comment by jkiviluo** [comment]
I think I expect that I need to move the focus away in order to 'register' my change. Pressing the next button should also do that automatically, so I don't see a real problem here?

**Comment by manuelma** [comment]
Ok, maybe I was making my life harder for nothing. Then we'll just connect to `editingFinished` and `returnPressed`, which trigger when the user leaves the line edit or presses return while in it. And we'll forget about the `textEdited` plus timer approach.

**Comment by jkiviluo** [comment]
@manuelma I think this is all good and can be closed?
