### ISSUE TITLE
Importer: new Excel sheet shown incorrectly

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1309]
When you have an existing data connection to an Excel file in importer and then add a new sheet there, then the importer does not show the mapping specification for the new sheet correctly. It does not include rows for 'Object names' and 'Object metadata' - there is just 'Object class names'. If you add parameter type to this mapping, those rows are added, but 'Object names' and 'Object metadata' remain invisible.

**Comment by jkiviluo** [comment]
I can work around this by switching item type to relationship class and then back to object class.

I tried also editing the importer spec, which was missing those 'Object names' and metadata entries, but surprisingly that did not help.

**Comment by manuelma** [comment]
@soininen let me know if you prefer I take this one (@jkiviluo assigned you but I think we can override his authority)

**Comment by manuelma** [comment]
Actually I just assigned myself as it's a pretty dumb mistake I made. Will fix it now.

**Comment by jkiviluo** [comment]
Seems to work. Close?
