### ISSUE TITLE
Bug in Tool available resources list

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1310]
1. Make a DAG with two Data Connections `DC1` & `DC2`, connected to a Tool `T`. 
2. Provide one file from `DC1` called `a.txt` to `T`
3. Provide another file from `DC2` called `b.txt` to `T`
4. In `T` properties `a.txt` and `b.txt` are now shown in Available resources list
5. Remove connection `DC2`->`T`
6. Available resources list in `T` properties is now empty

Expected behavior:
`a.txt` should still be listed in available resources list.

To get to expected behavior, user needs to remove and replace the `DC1`->`T` connection.

Happens with other project items as well but these should be the minimum steps to reproduce.

**Comment by soininen** [comment]
Looks like some repercussions from the refactoring I did earlier this week.

**Comment by soininen** [comment]
Funny, I didn't catch such a simple bug in my own testing. @PekkaSavolainen can you check that the bug is gone now?

**Comment by PekkaSavolainen** [comment]
It's fixed now. Thanks.

**Comment by PekkaSavolainen** [comment]
Added a test for this so we'll hopefully catch it the next time.
