### ISSUE TITLE
Importer is confused about data connection 

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1311]
When I change an Excel file in the data connection of the TradeRES project, the source file in the following importer is automatically switched to blaablaa.tmp. It does not revert back to the original Excel when I close Excel. I have to do that manually.

ADDITION: If I close the project and re-open it, I get the correct original source file in the importer.

If I try this in the Minimil_for_issues project, it does not reproduce (it looks just the same to me).

**Comment by jkiviluo** [comment]
TradeRES project has been updated. It should be portable now and it still has still problem. https://github.com/TradeRES/TradeRES

**Comment by soininen** [comment]
@jkiviluo I tried to reproduce the problem here but failed to do so. Perhaps I didn't follow the right steps. Can you be more specific: where/how do you see this .tmp file exactly? You can give me a Teams call if you think it is better to demo this online.

**Comment by jkiviluo** [comment]
It seems to be a transient issue. It happened to me also with the Minimal_for_issues, but now it's not showing up in TradeRES project.
