### ISSUE TITLE
Duplicated specification entries in project.json

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1312]
@jkiviluo has a `project.json` which had duplicate entries to the same specification file. This caused Toolbox to load the same specification multiple times which in turn lead other problems.

I have yet to find how we end up duplicating specifications in Toolbox. It may also be a remnant of some already fixed bug in the above `project.json`. However, Toolbox should not contain specification duplicates in general.

**Comment by PekkaSavolainen** [comment]
I've never seen duplicated specifications in project.json either but if somebody can find a way to reproduce this, I'm definitely interested.

**Comment by soininen** [comment]
Closing this one since we do not know how to reproduce it and there has not been more reports on corrupted project.json files. We do have some issues with duplicate specifications, though, see #1394.
