### ISSUE TITLE
Database editor broken when following the installation instructions

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1314]
Database editor does not work properly and hangs totally when opened a second time with the current selection of packages that come with `python -m pip install -r requirements.txt`. Here is what I did:

1. Clear my current (perfectly working) miniconda environment
2. Follow the installation instructions in `README.md` except for the git installation step, because I already have the repository cloned
3. Start Toolbox with `python -m spinetoolbox`
4. New project, add Data Store, create new Spine db, open database editor
5. Close the editor
6. Reopen editor --- the editor window opens but stays blank and is unresponsive

**Comment by soininen** [comment]
This hangs:

```python
db_map = DiffDatabaseMapping(<Spine database URL>)
db_map.query(db_map.relationship_parameter_value_sq).all()
```

**Comment by manuelma** [comment]
Nice, thanks for looking at this @soininen 

To understand, does this only happen when you follow the specific set of steps in the issue description? Or it can happen any time?

**Comment by soininen** [comment]
I think the 'specific steps' is to just install a fresh conda environment as per our README.md. After that, `relationship_parameter_value_sq` in `DiffDatabaseMapping` seems to hangs. I am guessing it is a certain mixture of dependency versions that is causing this.

We should get this fixed ASAP because it might prevent every new user from using Toolbox.

**Comment by manuelma** [comment]
can you share your conda env?

**Comment by manuelma** [comment]
I think the best way to do this is

conda list --explicit > spec-file.txt

**Comment by soininen** [comment]
[spec-file.txt](https://github.com/Spine-project/Spine-Toolbox/files/6181968/spec-file.txt)

Interestingly, when installing in a new conda environment the requirements of `spinedb_api` only, the code snippet above works just fine.

**Comment by soininen** [comment]
Even more interestingly, I just pulled all our four projects, created a fresh conda environment and now the issue is gone.

**Comment by PekkaSavolainen** [comment]
> While other queries I've tried work, this particular one hangs:

> from spinedb_api import DiffDatabaseMapping
> db_map = DiffDatabaseMapping(<Spine database URL>)
> db_map.query(db_map.relationship_parameter_value_sq).all()

> Note that the same query using DatabaseMapping works fine.

Do we have a unit test for this on spinedb_api or on Toolbox? If so, the Github action runner should catch this because it creates a new environment from scratch on every commit.

**Comment by soininen** [comment]
> Do we have a unit test for this on spinedb_api or on Toolbox?

We don't actually test exactly this particular aspect of `spinedb_api`.

**Comment by soininen** [comment]
It seems that the issue is gone now if I create a fresh conda environment for Toolbox. Downgrading packages to the versions in the broken conda environment does not bring the issue back. It remains a mystery what peculiar configuration in mine and one user's system caused this but hopefully we won't see it again.
