### ISSUE TITLE
Unable to add Additional Program Files through GUI, "not in working directory"

### ISSUE THREAD

**Issue by jimhommes** [Spine-project/Spine-Toolbox#1315]
It's not possible for me to add Additional Program Files in a Tool-box. It will give me the error "dummyfile.py not in working directory", while it is. To recreate:

1. Create new project
2. Create two dummy files in working directory
3. Create Tool-box
4. Create specification, select first dummy file under main program and try to select dummy file 2 under additional program files

I've fixed it for now by manually editing the json file of the specification and reloading the project, so just wanted to let you know. It also doesn't work for me when I try to create a new additional file. (it will output it in the working directory and then say it's not in the working directory)

**Comment by manuelma** [comment]
Thanks for this. I couldn't reproduce the error in latest master. Here is what I did

1. Select 'Create new Tool specification'
2. Click the button to select existing main program file. Select any file from the dialog.
3. Click the button to add additional program files. Select a file *in the same directory* as the previous one.
4. No error.

Toolbox only complains when the additional program files are *above* the main program file in the hierarchy. The *working directory* has nothing to do here.

Maybe you can share the manually fixed specification file (that toolbox wouldn't allow you to produce), to understand better.

**Comment by jimhommes** [comment]
That's weird, I've pulled once more and still same result. The second file is indeed in the same folder as the main program file (also the directory "Main program directory" on the lower right in the Tool Specification).

I've fixed it now by adding an entry to "includes" in the json file:
```
"includes": [
        "dummyfile1.py"
    ],
```
is now
```
"includes": [
        "dummyfile1.py",
	"dummyfile2.py"
    ],
```

To be precise, is there a button "Create new Tool specification"? A bit more specific:
1. I've dragged and dropped a tool box
2. I've right clicked the tool box and selected "New specification"
3. Try to add files like you described

**Comment by manuelma** [comment]
Thanks @jimhommes 

Yeah, we're doing the same thing getting different results. Which platform are you on? Windows?

**Comment by PekkaSavolainen** [comment]
I can confirm there's something funny going on here. What I did

1. Create Tool
2. From Tool Context menu -> New specification
3. Give the spec some name
4. Click button `Create new main program file` and make 'dummyfile.py' into project directory
5. Click button `Create new additional program file` and make `dummyfile2.py`
6. `Program file(s) 'dummyfile2.py' not in main directory` appears to status bar and it's not added to the Additional Program files list.

**Comment by jimhommes** [comment]
I'm on Windows 10 64-bit and using Python 3.7.9. It might be good to note that I'm running Spine and the Project files on a different drive.

**Comment by manuelma** [comment]
Thanks! I suspect it has something to do with windows treatment of paths. i will fix it now.

**Comment by manuelma** [comment]
Might work better in latest toolbox master. Please give it a try whenever you get the chance?

**Comment by jimhommes** [comment]
Works over here, thanks!
