### ISSUE TITLE
Confusing 'Save project before exiting' dialog when Saving project as

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1316]
1. Have an open project in Toolbox
2. Make pending changes to the project, e.g. move a project icon on the Design view
3. Select File->Save as
4. Choose a new project folder
5. Get greeeted by a rather confusing dialog:

![exit project](https://user-images.githubusercontent.com/19147159/112109251-ffb20700-8bb9-11eb-8f73-7caf864b36cb.png)

**Expected behavior**

Toolbox saves the project to the new location without signs that it in fact closed the previous project.

**Comment by PekkaSavolainen** [comment]
Commit 67c6fd3 should fix this. There was also another bug that if there were unsaved changes and user did Save project as..., the changes were discarded. Now it saves the project first and then makes a duplicate of it. Ideally it would only save the changes to the duplicated project but I could not figure out how to do that without considerable refactoring so I made a new issue about this (#1351).

**Comment by soininen** [comment]
The confusing dialog is now gone. Nice work, @PekkaSavolainen!
