### ISSUE TITLE
Importer bugs with pivoted data

### ISSUE THREAD

**Issue by Tasqu** [Spine-project/Spine-Toolbox#1318]
I've been running into a number of issues when trying to import pivoted data using the `Importer`. Essentially, I have parameter values for a relationship with 3 object classes, where the objects for one of the object classes is in the header. Here's a dummy toolbox project I made to highlight the issues:
[pivot_data_import_error_demo.zip](https://github.com/Spine-project/Spine-Toolbox/files/6188107/pivot_data_import_error_demo.zip)

1. `Importer 1` gets the furthest by mapping each `object class` separately before trying to import the relationship data. However, for some reason, it seems to try and import the parameter values for `object_class_3`, instead of of the relationship.

2. `Importer_2` highlights how the `import objects` option in the importer doesn't seem to be working at the moment. Trying to import the objects along with the relationship mapping doesn't work.

3. `Importer_3` shows that the `column header` option when mapping the data doesn't seem to work either. When using this option in the mappings, it seems to get converted to `header` for most cases if the mapping is reopened. Trying to run the importer gets stuck with a massive traceback:
```
Traceback (most recent call last):
  File "c:\data\spine\spine-items\spine_items\importer\mvcmodels\mapping_specification_model.py", line 553, in data
    return self.get_map_reference_display(m, name)
  File "c:\data\spine\spine-items\spine_items\importer\mvcmodels\mapping_specification_model.py", line 528, in get_map_reference_display
    return mapping.value + 1
TypeError: can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "c:\data\spine\spine-items\spine_items\importer\mvcmodels\mapping_specification_model.py", line 553, in data
    return self.get_map_reference_display(m, name)
  File "c:\data\spine\spine-items\spine_items\importer\mvcmodels\mapping_specification_model.py", line 528, in get_map_reference_display
    return mapping.value + 1
TypeError: can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "c:\data\spine\spine-items\spine_items\importer\mvcmodels\mapping_specification_model.py", line 553, in data
    return self.get_map_reference_display(m, name)
  File "c:\data\spine\spine-items\spine_items\importer\mvcmodels\mapping_specification_model.py", line 528, in get_map_reference_display
    return mapping.value + 1

...
```

4. The data preview in the importer also occasionally shows weird output when using the `column header` mapping option, but I don't know how to replicate it reliably.

5. I've also occasionally run into an annoying issue, where the types of the ignored columns are automatically changed to `float` when defining parameter mappings, but don't know how to replicate this reliably.

**Comment by manuelma** [comment]
Hi @Tasqu 

thanks for this and sorry for the troubles. I'm looking at the example project now.

**Comment by Tasqu** [comment]
@manuelma NP, I finally managed to create an example to reproduce some issues I've kept running into that I could share. Just FYI, this example isn't related to any of my old imports breaking, this is just me trying to import some new data into my project.

**Comment by manuelma** [comment]
Hi @Tasqu 

Number 1 should be fixed in latest spinedb_api master, can you pull and check?

Number 2 was fixed, but you need to manually uncheck/recheck the import_objects option to make it work! Sorry!

I'm now looking at number 3. Just one question, you say that `column_header` gets converted to `header`. Does that happen in the example project you attached?
I see this traceback
```
Traceback (most recent call last):
  File "/home/manuelma/Codes/spine/items/spine_items/importer/mvcmodels/mapping_specification_model.py", line 554, in data
    return self.get_map_reference_display(m, name)
  File "/home/manuelma/Codes/spine/items/spine_items/importer/mvcmodels/mapping_specification_model.py", line 529, in get_map_reference_display
    return mapping.value + 1
```
Is this what I should fix?

**Comment by Tasqu** [comment]
> I'm now looking at number 3. Just one question, you say that column_header gets converted to header. Does that happen in the example project you attached?
I see this traceback

@manuelma I believe it should. If you close and re-open the import editor, at least for me, the mappings got automatically changed in the editor. I didn't take a look what actually happens to the .json, though.

**Comment by Tasqu** [comment]
Basically this:
![image](https://user-images.githubusercontent.com/77660814/112149184-61d53100-8be7-11eb-9e53-2b22753b467f.png)
Gets converted into this:
![image](https://user-images.githubusercontent.com/77660814/112149281-787b8800-8be7-11eb-8db6-a94f579c342e.png)
If I close and re-open the import editor.

**Comment by Tasqu** [comment]
Which is a problem for the more complicated mapping, at least:
![image](https://user-images.githubusercontent.com/77660814/112149505-baa4c980-8be7-11eb-91c0-a331d6236680.png)
as there are now two `Headers` and I have no idea what the importer is trying to do:
![image](https://user-images.githubusercontent.com/77660814/112149591-d27c4d80-8be7-11eb-92fe-ea01386691ee.png)

**Comment by Tasqu** [comment]
@manuelma Importers 1 & 2 now work for me as well. I'll have to try importing some of my actual data next, but I have a pretty full schedule this week so I'm not sure when I can get back to this 😄

**Comment by manuelma** [comment]
I just pushed some commits that seem to help fixing all issues here....

**Comment by Tasqu** [comment]
@manuelma seems to work on my end as well. I'm closing this issue *(for now, at least)*, but I'll be back if I run into any more issues when trying to import some of my actual data.

**Comment by manuelma** [comment]
Thanks @Tasqu, yeah, please do, it's really helping a lot...
