### ISSUE TITLE
Importer: filter with regex

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1323]
Importer mapping specification could have a possibility to filter using regex. This would require a new column in the mapping specification column that would be active for those rows where it makes sense.

**Comment by manuelma** [comment]
This is a pretty good idea but we have so many issues on importer that maybe this one can take lower priority? Or is it really desirable?

**Comment by jkiviluo** [comment]
Yes, it can have a lower priority.

**Comment by jkiviluo** [comment]
@soininen This is done, right?

**Comment by soininen** [comment]
Yes, it's done. I missed the fact that we had an issue for it here.
