### ISSUE TITLE
Importer: column data types have a life of their own

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1327]
Column data types change in rather unpredictable manner. Probably something to do with automatic detection of the data type. It maybe gets into trouble when there are empty rows in the data before the actual data starts.

One example where it breaks regularly is that when you change alternative name in the mappings, the data types change back. But it really happens all the time under different circumstances (and data types don't always stick after pressing ok)

The example below should demonstrate (ts_cf is a good example).

[FlexTool2.zip](https://github.com/Spine-project/Spine-Toolbox/files/6197834/FlexTool2.zip)

Maybe the data types should be automatically detected only when a new table is detected and then there would be a button for 'autodetection of data types' so that the user can control when it happens. Not sure... When it works, it's great.

I assigned to @soininen, but could also be @manuelma

**Comment by manuelma** [comment]
What should we do here? Are there any detailed steps I can follow to see the issue clearly? Otherwise I can of course poke around until I see something weird, but that can be very subjective I guess...

**Comment by jkiviluo** [comment]
1. Open minimal_for_issues
2. Open the importer
3. Select Sheet1
4. Change data type for third column from float to string
5. Add e.g. alternative name for the mapping spec
6. Watch how the data type changes back to float
In this case that may be intended behaviour, but I've been having situations where I don't want it to change (it makes a wrong guess). That's why I'd like to make that guess a choice.

**Comment by manuelma** [comment]
Let's keep working on this in #1419...?
