### ISSUE TITLE
Visually uncaught issue and db initialization issue

### ISSUE THREAD

**Issue by tltoni** [Spine-project/Spine-Toolbox#1328]
The below video uses the following spine project example:
https://github.com/Spine-project/reduce-model-demo

The video illustrates two issues:

1. The GUI shows visually that everything is ok, however, there are errors. The errors should affect the visual layout, for example, by changing the green tick to some other color yellow or red.

2. The first time the project is executed it fails. In order to make the example execute as intended, we can open spine dbs original and reduced (not completely sure that this specific action made the necessary change). Now we can execute the project normally. (Perhpas, there is an db initialization issue of some kind.). Hence, the example should execute successfully with the first execution attempt.

https://screencast-o-matic.com/watch/creZF1VVrEF

The password to see the video is:
spinesupport

Reporter
Toni Lastusilta (VTT)

**Comment by PekkaSavolainen** [comment]
@tltoni 

About 1:

Importer `datapkg_to_spine` has the `Cancel import on error` unchecked. If you check this box

![issue_1328_cancel_import_on_error](https://user-images.githubusercontent.com/43600314/112642978-854ce580-8e4c-11eb-89c9-585a13c2a32d.png)

The Importer will stop executing the DAG if the Importer fails. If this is unchecked and importing data to a db fails, It will happily execute the next item in the DAG and mark the Importer as a success (green tick). I think you are right that it should be marked with a yellow tick instead. At the moment it's very confusing.

**Comment by PekkaSavolainen** [comment]
I could not reproduce 2. Maybe it has been fixed already, so please try again. If you can reproduce it, please provide the steps here.

**Comment by PekkaSavolainen** [comment]
About 2. You are right about it. There is some initialization step missing in Data Stores when a project is shared.

**Comment by PekkaSavolainen** [comment]
Done. Executing an Importer (or an Exporter) should now show a new icon (instead of the green tick) on Design View when there were errors.
