### ISSUE TITLE
Spine upgrade tool tries to launch from Python folder after upgrade

### ISSUE THREAD

**Issue by jimhommes** [Spine-project/Spine-Toolbox#1331]
If there has been an update for SpineToolbox at launch it will upgrade all dependencies and try to launch SpineToolbox. For me it gives the error

```
C:\Users\Jimho\AppData\Local\Programs\Python\Python37\python.exe: can't open file 'C:\Users\Jimho\AppData\Local\Programs\Python\Python37\Scripts\spinetoolbox': [Errno 2] No such file or directory
```

Afterwards you need to relaunch to launch SpineToolbox.
More of an FYI instead of a heavy bug report.

**Comment by PekkaSavolainen** [comment]
@jimhommes how did you install Spine Toolbox? Running `pip install -r requirements` should run setup.py, which creates `spinetoolbox.exe` into your ...\Python37\Scripts\ folder.

**Comment by jimhommes** [comment]
I have followed the instructions in the README, and I know that I have also run `pip install -r requirements` as part of that installation.

**Comment by jimhommes** [comment]
By opening Anaconda3, `activate spinetoolbox` and `spinetoolbox`

In practice I always go to the install directory first to pull latest version.

**Comment by PekkaSavolainen** [comment]
Ok, I confirm this.

```shell
(toolbox38) C:\>spinetoolbox

UPGRADING PROJECT ITEMS...

(Depending on your internet connection, this may take a few moments.)

Collecting git+https://github.com/Spine-project/spine-items.git@master
  Cloning https://github.com/Spine-project/spine-items.git (to revision master) to c:\users\ttepsa\appdata\local\temp\pip-req-build-63th6f0k
  Running command git clone -q https://github.com/Spine-project/spine-items.git 'C:\Users\ttepsa\AppData\Local\Temp\pip-req-build-63th6f0k'
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Saved c:\users\ttepsa\appdata\local\temp\tmpzh8blqpd\spine-items-0.6.20.zip
Successfully downloaded spine-items
Looking in links: c:\Users\ttepsa\AppData\Local\Temp\tmpzh8blqpd
Requirement already satisfied: spine_items in c:\users\ttepsa\.conda\envs\toolbox38\lib\site-packages (0.6.14)
Processing c:\users\ttepsa\appdata\local\temp\tmpzh8blqpd\spine-items-0.6.20.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: spine-items
  Building wheel for spine-items (PEP 517) ... done
  Created wheel for spine-items: filename=spine_items-0.6.20-py3-none-any.whl size=534864 sha256=9c19e410fa1a4051898e11e8a7a30d2932e362199bccd9460bbaa2bb1cedd0f0
  Stored in directory: c:\users\ttepsa\appdata\local\pip\cache\wheels\b0\80\ce\919ab3c64280906ac485ddce7c3a731d812a4259e100e908e3
Successfully built spine-items
Installing collected packages: spine-items
  Attempting uninstall: spine-items
    Found existing installation: spine-items 0.6.14
    Uninstalling spine-items-0.6.14:
      Successfully uninstalled spine-items-0.6.14
Successfully installed spine-items-0.6.20
C:\Users\ttepsa\.conda\envs\toolbox38\python.exe: can't open file 'C:\Users\ttepsa\.conda\envs\toolbox38\Scripts\spinetoolbox': [Errno 2] No such file or directory

(toolbox38) C:\>
```

**Comment by PekkaSavolainen** [comment]
The problem is this. In `main.py` we do

```
    try:
        subprocess.run([sys.executable, *sys.argv, "--skip-project-items-upgrade"], check=True)
    except subprocess.CalledProcessError as err:
        sys.exit(err.returncode)
 
```

When launching toolbox with `python -m spinetoolbox`
```
sys.executable:C:\Python38\python.exe
sys.argv:['C:\\Users\\ttepsa\\OneDrive - Teknologian Tutkimuskeskus VTT\\Documents\\GIT\\SPINETOOLBOX\\spinetoolbox\\__main__.py']
```

But when launching toolbox with spinetoolbox.exe

```
sys.executable:C:\Users\ttepsa\.conda\envs\toolbox38\python.exe
sys.argv:['C:\\Users\\ttepsa\\.conda\\envs\\toolbox38\\Scripts\\spinetoolbox']
```

I don't think it's worth trying to do anything about this. When using spinetoolbox.exe, spine_items **upgrade process is successful** even though the relaunch isn't. User's just need to **start spinetoolbox.exe again** and everything works again.

**Comment by manuelma** [comment]
What is `spinetoolbox.exe`?? When is that created? I had no idea... I only tested this with `python -m spinetoolbox` and it worked for me on windows... so...

**Comment by PekkaSavolainen** [comment]
I only recently discovered spinetoolbox.exe myself. It is created by our setup.py when installing the package. I believe it's the line `entry_points={"console_scripts": ["spinetoolbox=spinetoolbox.main:main"]},`

I would not miss it if it was removed though 🤔

**Comment by manuelma** [comment]
I don't get why `subprocess.run([sys.executable, *sys.argv, "--skip-project-items-upgrade"], check=True)` fails in that case. How come `...\Scripts\spinetoolbox` doesn't exist? How does this work? Or is it the python.exe that doesn't exist?

**Comment by PekkaSavolainen** [comment]
`...\Scripts\spinetoolbox` does not exist. `...\Scripts\spinetoolbox.exe` does exist (on Windows)

**Comment by manuelma** [comment]
Should this work: `subprocess.run([sys.executable, __file__, "--skip-project-items-upgrade"], check=True)`?

**Comment by manuelma** [comment]
That doesn't work, but this does

```
subprocess.run(
            [sys.executable, os.path.join(os.path.dirname(__file__), "__main__.py"), "--skip-project-items-upgrade"],
            check=True,
        )
```

**Comment by PekkaSavolainen** [comment]
I think that should work @manuelma

**Comment by manuelma** [comment]
It works on linux, can somebody try it on windows so we can apply it?

**Comment by PekkaSavolainen** [comment]
Works great in both cases here.

**Comment by PekkaSavolainen** [comment]
Should be working now @jimhommes. Please reopen if problem still persists.

**Comment by jimhommes** [comment]
Confirmed that it works
