### ISSUE TITLE
Exporter: object groups cannot be exported without objects

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1332]
I am trying to export a list of object groups. Doesn't work, because the objects are always there too. I guess there should be additional option parallel to 'hidden' and 'table name': 'omit' or 'eliminate' or 'leave out'

![image](https://user-images.githubusercontent.com/40472544/112468045-7abd1e00-8d70-11eb-9cc3-a5e8d50f5d8f.png)

EDIT: I see that there is that 'Group function'. However, it doesn't seem to affect anything. What is it supposed to do? I thought that if I select one or none in the group function, I would get rid of the objects and just have the object groups, but this does not happen.

**Comment by soininen** [comment]
I have a fix for this. Before I push the changes, however, I want to note that **the upcoming changes will break object group mappings in existing exporter specifications**. Before pulling, please delete object group mappings from existing specifications. They need to be recreated afterwards.

**Comment by soininen** [comment]
@jkiviluo Can you check if you can export object groups in the correct format? Note that the Objects and Object group rows in Mapping specification table have now switched places.

**Comment by manuelma** [comment]
Ideally Importer would follow the same pattern, to keep symmetry. If I understand correctly, ObjectGroupMapping is now the group, and ObjectGroupObjectMapping is the member?

**Comment by manuelma** [comment]
I just replaced some custom queries in `export_mapping.ObjectGroupMapping` and `export_mapping.ObjectGroupObjectMapping` by `db_map.ext_entity_group_sq`. Test keep passing, so I'm imagining @soininen must have missed the existance of `db_map.ext_entity_group_sq`? Otherwise please revert and apologies.

**Comment by soininen** [comment]
> you might have missed the existence of `ext_entity_group_sq`?

I noticed that query but still ended up writing those custom queries. I'm so unfamiliar with SQL that combining the query with `group_by` didn't cross my mind even though ironically I ended up using `group_by` in the custom queries. Thanks for simplifying the code after me! The tests should cover the basic use cases so if they pass you should be on the safe side.
