### ISSUE TITLE
Executable: Error message does not get passed to Toolbox

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1334]
We run executables in similar manner as you would run a bat-file in Windows (thanks @PekkaSavolainen). The challenge is that the executable may produce error messages in a way that does not get passed through. This happened to me with glpsol.exe (I did not have glpk_4_61.dll in the same directory). The error message in Toolbox was just a number, but when running glpsol from the command promt, it fired up a small windows that gave a textual error message.

Pekka has some ideas how to fix this, but unclear whether too much work for the reward.

**Comment by PekkaSavolainen** [comment]
Done.

![issue_1334_show_error_dialog_boxes](https://user-images.githubusercontent.com/43600314/115714201-86a3fc00-a37f-11eb-9fb2-3ef30d3ae84c.png)

If these error boxes become too intrusive, we can tinker with when to show them or maybe make this a Toolbox Setting.

P.s. My initial guess that these error boxes would not be shown when running executables from batch files was wrong.
