### ISSUE TITLE
Exporter: export list of parameter names

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1338]
I'm trying to output a non-duplicate list of parameter names for a relationship class. This does not seem to be supported. I can output parameter definitions by hiding everything else, but this results in duplicates when there are multiple entities with a value for that parameter (the typical situation).

Maybe the easiest way would be to add a possibility to import parameter type "definition". Currently you can import "value" of "default value". With "definition", the parameter values dimension would disappear from the mapping specification and it would not output duplicates.

**Comment by jkiviluo** [comment]
Maybe I had it wrong. It seems it actually removes duplicates. I just had an insufficient filter for the relationship class name. I should have had ^grid__node$ to remove the classes with grid__node__xx etc.

**Comment by soininen** [comment]
This should work already without explicit "definition" parameter type. Technically speaking, exporter completly ignores hidden 'tail' mappings, i.e. mappings at the bottom of the mapping table set as 'hidden' are dropped when exporting. If there are duplicates then we have a bug somewhere. If exporter seems to work as expected feel free to close this issue.
