### ISSUE TITLE
Exporter: choose what to export

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1339]
Currently exporter exports all mappings every time it's executed. It would be nice to have a check-box to choose what to export (and select all/none buttons). Importer has the check-boxes, but it is also missing select all/none buttons.

**Comment by soininen** [comment]
Nice idea! I somehow managed to overlook this feature while writing exporter's mappings list.

**Comment by soininen** [comment]
Implemented in Exporter. Hopefully the feature will prove useful. @manuelma do you want to tackle the select all/none aspect in Importer? I can also give it a try.

**Comment by jkiviluo** [comment]
Nice work. Seems to work!

**Comment by manuelma** [comment]
> @manuelma do you want to tackle the select all/none aspect in Importer? I can also give it a try.

No problem, I will do it.

**Comment by manuelma** [comment]
It's done. I will bump the version later as this is not critical.
