### ISSUE TITLE
Exporter: map entity class to header

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1340]
It would be nice to be able to map the entity class name to the header of the row/column where the entities of that entity class are deposited. 

This would require additional choice (currently 'Table name', 'Hidden', or a number). It can be added manually, but having it as a header would make it faster to do the mappings and it would update if the class name changes (which may be both good and bad). 

If the entity class is mapped to the header, then the header field of that entity should not be modifiable any more (grey out).

**Comment by soininen** [comment]
Would setting entity class as 'pivoted' help you here in any way?

**Comment by manuelma** [comment]
I'm not sure about this one, what happens if there's more than one object class in the db? which one should go in the header then? Do we need to concatenate somehow?

**Comment by jkiviluo** [comment]
> I'm not sure about this one, what happens if there's more than one object class in the db? which one should go in the header then? 

The object class name should become the header for the objects in that same object class. I don't see point in offering anything else - you can type manually in more complicated cases.

**Comment by soininen** [comment]
@jkiviluo can you give us an example what you're trying to achieve? If you're just exporting classes and entities, setting classes as pivoted will give you

```
class1 class2 class3
foo1   baz1   bar1
foo2          bar2
              bar3
```

which looks suspicuously like the class names are in the headers.

**Comment by jkiviluo** [comment]
That doesn't work as far as I can see. I get this:

```
              class1 
              class2 
              class3
foo1   baz1   bar1
foo2          bar2
              bar3
```

Furthermore, I'm also importing parameter definition names and parameter values. Sometimes also indexed parameters.

**Comment by jkiviluo** [comment]
An example: 
![image](https://user-images.githubusercontent.com/40472544/112828438-5dea5880-9098-11eb-9d5f-24cc3a5f5631.png)

**Comment by soininen** [comment]
> That doesn't work as far as I can see.

Strange. It used to work like that. I even wrote a unit test for it but now I cannot find even that anymore.

**Comment by soininen** [comment]
@manuelma is right, this would only work if there is a single object class (or whatever item becomes the header) in the table. What is the desired behavior if this is not the case? Should we just pick the first class, list its objects and leave it like that?

**Comment by manuelma** [comment]
I think @jkiviluo is thinking of the `RelationshipClassObjectClassMapping` only, which always yields the same element, the object class name, so it works. It could be that we only allow this one to go to the header. Btw, you may have noticed that I added `Position.header` to the `Position` enum to use it in importer, and might come in handy here.

**Comment by manuelma** [comment]
Actually, the way I implemented it in Importer is that when `position` is `Position.header`, then `value` becomes the index in the header. I don't know if that's awesome.

**Comment by soininen** [comment]
> I think @jkiviluo is thinking of the RelationshipClassObjectClassMapping only, which always yields the same element, the object class name, so it works. It could be that we only allow this one to go to the header.

That might indeed work. I'll go with restricting `Position.header` to where we can have only one such item.

> Btw, you may have noticed that I added Position.header to the Position enum to use it in importer, and might come in handy here.

I noticed. Nice to have it readily available!

**Comment by jkiviluo** [comment]
Just to clarify. In the snapshot above, I should be able to use 'add as header' in one or more of the three 'object classes' that the Mapping specification contains. If I do that for the first one, then it would give the object class name as a header for the first 'Objects'. If I do it for the 2nd, then that would go for the second 'Objects'. They are always related in that order (you should never want to give a header name from 1st 'object classes' to 3rd 'objects').

**Comment by manuelma** [comment]
You're right @jkiviluo , and that's also good for us because it means setting `position` equal to `Position.header` is enough, as the actual column number is given by the 'buddy' object mapping.

**Comment by soininen** [comment]
That is how it is now implemented in spinedb_api on my branch. Now, onto giving users access to the feature in the Specification editor.

**Comment by soininen** [comment]
I should know better than to write comments stating that "X has been implemented, now onto Y" here. Well, at least we now have a `find_my_buddy()` function in spinedb_api. Thank you @manuelma for the naming hint!

@jkiviluo can you try the feature out? Does it work as expected?

**Comment by jkiviluo** [comment]
Seems to work for columns. If you try to put the objects into rows (pivoted) - not so much. But that seems to be a bigger issue in the exporter.

**Comment by soininen** [comment]
Indeed, you get a Traceback. And then the actual pivot table is off-by-one column. I'll try to get those fixed.

**Comment by soininen** [comment]
Hopefully things work better now.

There seems to be a little 'buddy problem', though. Currently, it is hardcoded which items can be headers for which data, e.g. object classes can be headers for objects only. Are there use cases where we would like this to be configurable? Object class name as header for parameter definitions?

**Comment by jkiviluo** [comment]
I don't see a use case for that (at least not common use case). You can always write it manually, so I don't think it's needed.
