### ISSUE TITLE
Exporter: does not export headers only

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1341]
If a table does not have data to be exported, the exporter does not export headers either. These are needed, since tools reading the exported data often expect to see at least the header.

**Comment by soininen** [comment]
This turned out to be a bug in `spinedb_api` introduced with `Position.header` in `export_mapping`. Hopefully the headers appear again in otherwise emtpy tables.

**Comment by soininen** [comment]
> There is also a further issue. You could output parameter names even if there are no parameter values. That should probably be an option.

That setting already exists in the backend side and is turned on behind the scenes for parameter value lists. It hasn't been exposed to users yet since I wasn't sure about its general usefulness. It seems I need to add new checkboxes to the mapping table. And make it possible to turn the option off as it is currently a one-way setting in `spinedb_api` :)

**Comment by manuelma** [comment]
I think this needs to be a user choice. In the case of the basic export to excel, we'd prefer to skip the table altogether if no rows. Just writing the headers to a sheet and nothing more is not desirable. It also damages performance, every new sheet is expensive.

**Comment by jkiviluo** [comment]
Right, both are needed. It's also common need to have everything output even if there is no data. All that information provides structure for the next step (which may expect to get the structure from the data). It's also nice for the user to see what is possible (of course you can do that also in Spine DB, but still).

**Comment by soininen** [comment]
The above commits should fix header-only pivot tables and make such tables (e.g. still writing a header even if no data is available) optional. There is now a new checkbox in the specification editor to control the behavior. The option is turned off for the basic Excel export.

**Comment by soininen** [comment]
There is now also a separate issue for the 'ignorable' option: #1363
