### ISSUE TITLE
Exporter: filter using the dimensionality of classes and map indexes

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1352]
ParameterValueTypeMapping is not sufficient. We need three new choices in the exporter:
- output types [list choice: all, value, map, ...]  (All would be default. This could include string, integer, etc. if we have hold of them)
- in case of relationship class object: Below (or right of) _Number of Dimensions_: a choice of _Output data with less object dimensions_
- in case of parameter type Map: Below (or right of) _Parameter dimensions_: a choice of _Output data with less map dimensions"

Here is an example of data where I have two relationships with different dimensionality ("hauki" has 1 object class while "Baltic|hauki" has 2 object classes). Similarly there is parameters that are scalar, 2D or 3D. Most of the time I'd like to output only data from the highest dimensionality. It's more important to get the possibility to filter the parameter dimensions out, because it's easier to use filter with classes (they are less likely to change and mess up your exporter).
![image](https://user-images.githubusercontent.com/40472544/113500779-83101880-9529-11eb-9a2d-61217f4df79b.png)

I tried to see whether I could implement this, but this seems to go to the internals of both mapping specifications and DB queries (you need to add this information to the mapping specification and the have the queries interpret that correctly). So, I gave up.

**Comment by jkiviluo** [comment]
Initial discussion at: https://github.com/Spine-project/Spine-Toolbox/issues/1260#issuecomment-792569159

**Comment by manuelma** [comment]
The idea of `ParameterValueTypeMapping` is to yield the parameter value type as a string: "single_value", "time_series", "time_pattern", "array", "1d_map", "2d_map", ect.

We still need to make the `ParameterValueTypeMapping` appear in the exporter spec editor, but that's ok.

Then, if you only want maps of two dimensions, you could use a filter expression like "2d_map". If you want 2 and 4 dimensions, you use "2d_map|4d_map". That should work.

> a choice of _Output data with less map dimensions

I don't understand this, isn't the case that it always yields data with less map dimensions?

**Comment by manuelma** [comment]
To me it seems best to do all filtering in the Mapping specification table, using the filter column, and *never in the Mapping options* using additional checkboxes or similar widgets. The Mapping options would be reserved to select the 'structure' of your mapping, how many indexes or objects you want, etc. And then the actual 'contents' of the result would be manipulated in the Mapping specifications. What do you think?

**Comment by jkiviluo** [comment]
> ...What do you think?

Yes, I like your idea much better (make the `ParameterValueTypeMapping` appear in the exporter spec editor). I hadn't realize it differentiated between different map dimensions. However, we need to provide the user the information about those ValueType names: "array", "1d_map", etc. in the mapping editor. Maybe it's just a tooltip?

>  ...to provide a custom editor for the filter column...
This would also be great. We could also consider switching to something else. RegEx is otherwise great, but it's not good with `not` and other set operations, which can be useful here. No hurry with these...

**Comment by manuelma** [comment]
I think RegEx needs to stay in the backend at least, for performance.

**Comment by soininen** [comment]
It is now possible to export parameter value types and of course filter by them. The type names are currently not listed anywhere but you can peek them by setting the type's position to non-hidden in the Specification editor.

Please note that the value types are only available in new mappings. To utilize them you need to replace your old mappings with new ones.

**Comment by jkiviluo** [comment]
Things seem to work. I guess we shouldn't close the issue before we provide a bit more user guidance.

**Comment by soininen** [comment]
I implemented simple editors for the filter column. The one for the value types looks like this:

![re_editor](https://user-images.githubusercontent.com/19147159/114536980-54e1b580-9c5a-11eb-9311-a83c6ea51b5c.png)

The other editors have the line edit and the link but no hints. Hopefully this helps with the filter expressions until we get #1367 resolved.
