### ISSUE TITLE
Exporter: control the alignment of object classes when outputting relationships with different dimensionality

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1353]
If you look at the table below, you can notice that the 1D relationship class with `hauki` does not align correctly with the 2D relationship class with `Baltic|hauki`. We should first establish the position of each object class (it is available in the mapping due to the implicit order of object classes) and only then relate the writing of particular object class to that position. May require quite a bit of coding and not of high importance (probably not very common use case).

![image](https://user-images.githubusercontent.com/40472544/113501148-f450cb00-952b-11eb-8db1-d2f796d7989e.png)

**Comment by manuelma** [comment]
Another option would be to split that mappings into two: one only yields the 2D relationship, and the other yields the 1D relationship (using filters). In this way we can chose separately where to send each object dimension, so they could go to the same column.

Now, it would only be a matter of supporting writing the results of two different mappings into the same table, one after the other. I think that can be done easily, and could be triggered by having the same 'table name' in the two mappings.

**Comment by manuelma** [comment]
I modified the title slightly so we don't think this is a bug. It's not in my opinion, the exporter is doing what is intended to do. This is more like a feature request.

**Comment by jkiviluo** [comment]
Ok, I guess it can depend on the situation which output you want. But I would think that in most cases you want to keep object from the same object class aligned. So, I wouldn't mind if the fix is just to align them and not offer an option.

> Now, it would only be a matter of supporting writing the results of two different mappings into the same table, one after the other. I think that can be done easily, and could be triggered by having the same 'table name' in the two mappings.

I like this solution.

**Comment by manuelma** [comment]
> But I would think that in most cases you want to keep object from the same object class aligned

Ok, so at the moment one can only specify mapping position by 'relationship dimension'. You would like to specify mapping position by class name: "everything that's of class unit, send it to column 1, and everything that's of class node, send it to column 2". I guess that could be a mapping option, something like a checkbox that controls the behavior of the `RelationshipObjectMapping`. Although it doesn't seem easy to implement it within the current design, because it means that the `position` attribute is somewhat dependent on the contents. Maybe @soininen has an idea.

But maybe the easier solution is what I propose, leave it to the user to define two mappings and send them to the same output table (provided we implemented that last part).

We also would need to consider what happens if the same object class appears multiple times in a relationship class.

**Comment by soininen** [comment]
Supporting multiple mappings writing on the same table would give users more flexibility in general while at the same time resolving this issue. I think we should try that route first.

**Comment by jkiviluo** [comment]
> Supporting multiple mappings writing on the same table would give users more flexibility in general while at the same time resolving this issue. I think we should try that route first.

Yes. Sounds like we all like this best.

> We also would need to consider what happens if the same object class appears multiple times in a relationship class.

I think this is also handled by the ability to map to the same file. You can already re-order object classes, even when they are the same.

**Comment by manuelma** [comment]
> I think this is also handled by the ability to map to the same file.

**Comment by soininen** [comment]
Mappings now append to the same table and writing order can be modified in Exporter's specifiction editor.

**Comment by manuelma** [comment]
I think it would be marginally nicer if the users could define the order with drag and drop. My idea is to enable drag and drop only for the second column (write order). The user would drag the order indicator (e.g., "2nd") and drop it over the mapping that they want to write in the second place. With this, we could also remove the Write earlier/later buttons so as to optimize space. What do you think? I will give it a go now so we can see how it works.

**Comment by manuelma** [comment]
Commit 566a2e2ca2aa23aab7f20e6c2164247e1935f472 implements my idea. If you like it, I will go ahead and do corresponding modifications to the user guide.

**Comment by soininen** [comment]
Frankly speaking, drag and drop is not too nice when the list is sorted by the write order. In that state you would like to drag the mapping names instead of the numbers. I'm also unsure if users will discover that the single column is actually draggable. Can't we just move some of the buttons below the table if it is horizontal space that you're concerned with?

**Comment by manuelma** [comment]
It's not only horizontal space, I also find it "hard" to get the order right with the buttons, you need to press the buttons multiple times, select another index and press the buttons again. Drag and drop would be much more direct.

I completely missed the case where the table is sorted by write order. Maybe in that case we could switch to dragging mapping names instead as you suggest?

**Comment by soininen** [comment]
I'm starting to wonder if we should have a separate little 'write order editor' as cramming the alphabetic ordering and write ordering in the same table seems to cause usability problems. A popup list where you could drag and drop the mappings around. Could be too much, though.

Anyway, we could also try allowing dragging and dropping by the item names as you suggested. Maybe you're right with the buttons as they might become tiresime with large number of mappings.

**Comment by manuelma** [comment]
When the table is ordered by Write order, the buttons are actually nice. Hmmm I don't know, maybe we can stick with the buttons for now until we figure out the better design.

**Comment by jkiviluo** [comment]
The original issue here is solved. There is some discussion on how things should look, but it seems like it's ok as it is.
