### ISSUE TITLE
Create a datapackage on the fly while advertising CSV resources

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1354]
At the moment we rely on datapackage to define one mapping spec for several CSV files in the importer (otherwise we'd need one spec for each CSV, which can become unmanageable for large amounts). The datapackage is created in the DC that holds the CSV files, and then the DC is connected to the Importer to define the mapping spec.

- This doesn't work if my CSV files are from the output of a Tool. The horrible workaround consists in adding the CSVs into a DC manually, which breaks the (work)flow.
- But the flow is also sort of broken even in the ideal case where the CSVs are in the DC, because the user needs to press a button to create the datapackage.

The proposed solution is to 'create the datapackage in the link': We add a checkbox to the link properties UI, that says something like "Pack CSVs into datapackage". When checked, all the CSV files that are advertised through that link (both statically and dynamically) are replaced by a datapackage.json holding them CSVs.

**Comment by jkiviluo** [comment]
@manuelma I think this is fine. I've been using it without issues. Close?

**Comment by manuelma** [comment]
Yeah, it's good. I can't remember why I kept it open unfortunately. Maybe I was thinking about supporting datapackage in exporter, but we can create another issue about that when/if needed.
