### ISSUE TITLE
Cannot accept Toolbox settings: Finalizing Julia configuration is stuck in endless loop

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1360]
I think this is what I did:

- Changed something in Toolbox settings unrelated to kernels
- Clicked 'OK' but a dialog complained that my Julia installation didn't exist (maybe I had removed it)
- Cleared the path to `julia.exe`. The text got replaced by placeholder text that seems to point to an existing `julia.exe` (nice!)
- Cleared the Julia project text field too, just in case
- Clicked 'OK' again to get rid of the settings window
- Toolbox asked to install IJulia. Go for it.
- After successfull installation, clicked 'Close' on the Julia Kernel Specification Creator dialog
- Clicked 'OK' again to get rid of the settings window
- Julia Kernel Specification Creator appears again and installs (again successfully) IJulia kernel.

Now, I cannot exit the settings window using the 'OK' button since the Julia Kernel Specification Creator jumps in to stop me.

**Comment by manuelma** [comment]
> After successfull installation, clicked 'Close' on the Julia Kernel Specification Creator dialog

This should have also closed the Settings widget. I wonder why it's not the case...

**Comment by soininen** [comment]
> This should have also closed the Settings widget.

That would be the expected behavior, indeed.

**Comment by manuelma** [comment]
There might be a problem with `_get_julia_kernel_name_by_env()`

Can you please check in line 640 in `settings_widget.py` that the `julia_kernel` variable is set?

**Comment by soininen** [comment]
> Can you please check in line 640 in settings_widget.py that the julia_kernel variable is set?

It is set to an empty string.

**Comment by soininen** [comment]
My educated guess is that we are missing

```python
        if not julia_exe:
            self.ui.lineEdit_julia_path.placeholderText().strip()
```

after line 684 in `settings_widget.py`

**Comment by soininen** [comment]
Works for me, but what happens if I don't have Julia installed at all?

**Comment by manuelma** [comment]
In my case, when I clear the julia exe line edit, I don't get any placeholder text. I think that only works on windows.

I think if you don't have julia installed, the placeholder text is not set.

**Comment by manuelma** [comment]
I think I can take a deeper look to try to organize things a bit better. There's a lot of stuff about finding julia and python executables from PATH, that also try to handle at the same time the scenario where the app is frozen, some of which work only on windows, etc.

**Comment by PekkaSavolainen** [comment]
The placeholder text should be the Julia in your PATH if present.

**Comment by manuelma** [comment]
> The placeholder text should be the Julia in your PATH if present.

Also on linux? doesn't seem to be case for me...

**Comment by PekkaSavolainen** [comment]
How about we don't try to do the kernel installation automatically when clicking Ok? I was afraid something like this is going to happen. I suggest we just add a button in the Tool->Settings window that makes the kernel specs without the need to go to the kernel spec editor.

**Comment by manuelma** [comment]
> How about we don't try to do the kernel installation automatically when clicking Ok?

Let's keep it, but if it fails, we close the form anyways. The user should be aware at that point that there is a problem with their julia settings. The problem I was facing is that some users would accept "invalid settings", and then they were surprised when their tool failed. It was a poor user experience.

**Comment by PekkaSavolainen** [comment]
> Also on linux? doesn't seem to be case for me...

I used `os.get_exec_path()` to find the PATH in spine_engine.utils.helpers.py resolve_julia_executable_from_path() function. At least on Windows it returns my PATH. Don't why this is not the case on Linux.

**Comment by manuelma** [comment]
> I used os.get_exec_path() to find the PATH in spine_engine.utils.helpers.py resolve_julia_executable_from_path() function. At least on Windows it returns my PATH. Don't know why this is not the case on Linux.

yes, I saw it. It's a bit crazy but I like it. I will try to make it work on linux.

> resolve_python_executable_from_path() works only on Windows at the moment.

Yes, true. Is there any reason we make it that way?

**Comment by PekkaSavolainen** [comment]
> Yes, true. Is there any reason we make it that way?

No reason. It was just the last thing I wanted to get done for release 0.5. If you can make it cross-platform, I'd be very grateful.

**Comment by manuelma** [comment]
> If you can make it cross-platform, I'd be very grateful.

Sure, isn't just a matter or replacing `"python.exe"` with `PYTHON_EXECUTABLE`?

**Comment by PekkaSavolainen** [comment]
I think so 😄

**Comment by manuelma** [comment]
> I used os.get_exec_path() to find the PATH in spine_engine.utils.helpers.py resolve_julia_executable_from_path() function. At least on Windows it returns my PATH. Don't know why this is not the case on Linux.

it does return all the folders in PATH. But we then check `if "julia" in path.casefold():` where `path` is one of such directories. And that's never the case, that's why it doesn't work. What was the purpose of this check @PekkaSavolainen ? Can I just remove it? and the same goes for `resolve_python_executable_from_path()`, I don't think that check is good.

**Comment by manuelma** [comment]
Might work better in latest masters (toolbox, engine, items):

I did two things (or at least tried):
1. Correctly identify the kernel after installation, by translating the empty string into the python or julia from paths
2. Close the form anyways if the auto-installation fails.
3. Fix the functions that find python and julia from path, so they also work if the python or julia strings are not part of the directory name.

Please let me know if I missed something.
