### ISSUE TITLE
Exporter: expose 'ignorable' setting to users

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1363]
Export mappings' 'ignorable' flag should be settable in Exporter's specification editor as discussed in #1341.

- [ ] Enable unsetting the 'ignorable' flag. Currently, you can only set the flag in `ExportMapping.set_ignorable()`.
- [ ] Add a new column to mapping table in Exporter's specification. The column should contain checkboxes that control the flag.

**Comment by manuelma** [comment]
I know this is an old question, but I seem to always forget what's the meaning of this flag. In which cases do I need to use ignorable? Is there any word that could help me remind it better?

**Comment by manuelma** [comment]
I found this:

>If I remember correctly, it yields the mapping's data if it is available, otherwise it yields None and doesnt' update the state. For example, if a database has two object classes, A and B and only A has parameter P defined, then with mapping

ObjectClassMapping - ParameterDefinitionMapping(ignorable) - ObjectMapping

you would get

A P object1
...
A P objectN
B None object1
...
B None objectN

You get B and its objects written even though there is no parameters in B.

**Comment by soininen** [comment]
'ignorable' flag's purpose is indeed to allow mappings to yield incomplete rows. The use case that prompted for this issue was to enable exporting tables that have all classes and entities and their parameters *if* they have those defined.

I am all ears if anyone has a more descriptive name for the flag.

**Comment by soininen** [comment]
Done.
