### ISSUE TITLE
Executing a Data Store with a broken url is always successful

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1371]
Consider a Data Store that is pointing to an invalid url or to a database that has not been upgraded to the latest version. When this Data Store is executed, it reports that the execution has **succeeded**, even though it clearly fails.

<del>I think this problem should be fixed in data_store\executable_item.py execute() method.</del>

- [x] Make executing a Data Store with an invalid URL fail
- [x] Make executing a Data Store with an outdated db revision fail

**Comment by soininen** [comment]
The check should rather be in `resources_for_direct_predecessors()` because that may provide an invalid URL to the previous item which then tries tries to use it.

Better still, we could have items' internal states validated before we even start the execution.

**Comment by PekkaSavolainen** [comment]
Updated the description and ticked the first task. This is done via the new ready_to_execute() method in Data Stores ExecutableItem.

**Comment by PekkaSavolainen** [comment]
This is done. See also #1374.
