### ISSUE TITLE
Introduce ItemExecutionFinishState?

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1372]
The `execute()` methods in ExecutableItemBase and it's subclasses return a boolean to report back to the toolbox whether the execution succeeds or not. I propose that they return a state instead. Defined something like this

```
class ItemExecutionFinishState(Enum):
    SUCCESS = 1
    FAILURE = 2
    SKIPPED = 3
    STOPPED = 4

    def __str__(self):
        return str(self.name)
```

So, on success they return ItemExecutionFinishState.SUCCESS instead of True. This would help in distinguishing between whether an item execution was a success, failure, skipped, or user stopped (or something else maybe). I have the implementation almost ready but wanted to make sure that this is not a bad idea for some reason...

**Comment by manuelma** [comment]
We have `SpineEngineState` and `execution_permits` which somehow provide the same info. We need to avoid repetition and the necessity of synching too many states.

**Comment by PekkaSavolainen** [comment]
SpineEngineState is the execution state of the whole DAG, not individual items.

**Comment by manuelma** [comment]
execution_permits will tell you the SKIPPED situation of each project item.

I'm not opposed to `ItemExecutionFinishState` but it should replace everything it can replace, e.g., in SpineEngine, SpineEngineWorker, and so on, so we only have *one* state.

**Comment by PekkaSavolainen** [comment]
> execution_permits will tell you the SKIPPED situation of each project item.

True, they tell the engine which items to skip but then after skipping there's only a boolean reported back to toolbox and herein lies the problem; is skipped item a success or a failure?

**Comment by manuelma** [comment]
If the item is skipped then execute() is not called, is it? So I don't understand what skipped has to do in the ItemExecutionFinishState enum.

**Comment by manuelma** [comment]
Please checkout `spine_engine_worker.py`, see that `skipped` is sent with the `"exec_finished"` log message. I'm not opposed to refactor this somehow with what you propose, it's just that I don't want to have any repetition if possible.

**Comment by PekkaSavolainen** [comment]
Done. All ExecutableItems now return an ItemExecutionFinishState instead of a boolean.
