### ISSUE TITLE
Docs copyright statement

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1375]
The following copyright statement appears at the end of the docs (e.g. https://spine-toolbox.readthedocs.io/en/latest/index.html)

>© Copyright 2021, P. Savolainen, M. Marin, E. Rinne, P. Vennström, A. Soininen Revision 4957ef65.
Built with Sphinx using a theme provided by Read the Docs.

This may have been raised already, but just in case.

**Comment by PekkaSavolainen** [comment]
I can edit it. What should it be?

**Comment by manuelma** [comment]
Maybe "Copyright (C) 2017-2021 Spine project consortium"?

**Comment by PekkaSavolainen** [comment]
Should be this after readthedocs has rebuilt the user guide.

> © Copyright 2017-2021 Spine project consortium. 

`© Copyright` part is added by Sphinx automatically and we can just edit the string that follows.

**Comment by PekkaSavolainen** [comment]
Please reopen if needed.
