### ISSUE TITLE
RunTimeError when switching projects

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1379]
Seen this a couple of times when switching projects. Something to do with Exporter properties when there's more than one input Data Store possibly...

```
Traceback (most recent call last):
  File "C:\Users\ttepsa\OneDrive - Teknologian Tutkimuskeskus VTT\Documents\GIT\SPINETOOLBOX\spinetoolbox\widgets\project_item_drag.py", line 455, in _reset_specs
    self.removeAction(action)
RuntimeError: Internal C++ object (PySide2.QtWidgets.QWidgetAction) already deleted.
```

**Comment by soininen** [comment]
I tried to reproduce this but didn't encounter the exact same Traceback. However, once during many project switches I got the same RuntimeErrror but this time on line 290 in the same file. It seems we have some problem there but it is just very difficult to reproduce at least on my system. Maybe someone else has better luck?

**Comment by PekkaSavolainen** [comment]
The traceback usually means a missing `self.` in some variable but I'm not sure.

**Comment by manuelma** [comment]
> The traceback usually means a missing self. in some variable but I'm not sure

It feels like the opposite, an orphan `QAction` destroyed by Qt, that Python still believes it exists.

**Comment by soininen** [comment]
`ProjectItemSpecArray` takes ownership of `QWidgetActions` because they are added to it by calls to `addWidget()`, e.g. on line 470. When `ProjectItemSpeArray` gets deleted in C++ side it also deletes the actions. I believe this is what leads to these RuntimeErrors. Maybe @PekkaSavolainen is correct in that we don't extend `ProjectItemSpecArray`s lifetime long enough.

**Comment by manuelma** [comment]
Maybe we can set the parent in the `super().__init__()` call in `ProjectItemSpecArray` constructor?

**Comment by manuelma** [comment]
> Maybe @PekkaSavolainen is correct in that we don't extend ProjectItemSpecArrays lifetime long enough

I don't know how more we can extend it. We save all of them in a list in `MainToolBar`.. what am I missing?

**Comment by soininen** [comment]
I don't know either. I don't see any obvious places where things could go wrong. Looks like some delicate timing problem in any case.

**Comment by PekkaSavolainen** [comment]
I haven't seen this since April. Close?
