### ISSUE TITLE
Importer: edit specs without an input file

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1381]
I couldn't find an issue for this. Basically we would like to be able to create importer specs without having to provide a file.

**Comment by jkiviluo** [comment]
I suppose this is just when initially making the spec? For project and item portability, we need a file.

**Comment by manuelma** [comment]
I mean without the *input* file. The specification .json file is always needed to save and port the spec as you say, but the input is not necessarily needed to define the spec.

**Comment by jkiviluo** [comment]
Right, sorry. Yes, this is very important improvement. The user should have visibility what the importer can do and what the input file actually has. This means that when the input data is not available, user should still see what the importer could import.

**Comment by manuelma** [comment]
Something is in place at the moment. In the importer spec editor, under Source files, select "anon filename" from the combobox. Then you can create tables under Source tables and you'll see dummy data under the Source data.
