### ISSUE TITLE
Resources do not get properly updated when item is renamed

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1382]
Noticed this with a Data store and Exporter connected to a Tool.

- When renaming the Data store the db_url@<data store name> label in Tool's Available resources is not updated: both the label and the URL should change
- When renaming the Exporter an existing output file's URL is not updated

We use `updated_from` metadata field in resources to communicate changes during item renames. This is mostly manual work done by the project items. We could try to make this more transparent to the items or at least provide some support functions in `spine_engine`.

**Comment by soininen** [comment]
The above commits implement a new communication path for project items that allows items to 'replace' resources that have been previously advertised. It should fix the problems mentioned in the issue's description as well as a bunch of other related to item renaming such as connection filters loosing their settings if source DT is renamed.

**Comment by manuelma** [comment]
Tool command line arguments are not restored properly after above commits. `Tool._update_files_and_cmd_line_args` basically drops label arguments whose resources aren't available. As the project is incrementally loaded, this function is called every time a connection is made. And obviously, some arguments are then dropped as the connection that carries the corresponding resource is not there yet. I would like to fix this to get more acquainted with recent changes. The new resource replacement approach seems great.

**Comment by soininen** [comment]
> My plan is to modify project loading a bit, so resources aren't advertised until all connections have been restored.

I fixed the same issue in Exporter by making the item to remember previously connected databases. It had the nice side effect that you could disconnect and then reconnect a Data Store and didn't lose its output file in Exporter.

In any case, I agree we could improve project loading (and things like remove all items/close project) by updating the resources only after all items have been added/removed. The current incremental system is something I left there after the largish changes in how the DAG is updated I worked on a few months back.

**Comment by manuelma** [comment]
Thanks, I'm giving it a try now. I feel remembering stuff in the item is good, but has to be seen as an improvement. Essentially we need to advertise resources all at once at project loading, otherwise we'd always have to consider project loading as a particular case when reasoning about more interactive stuff...

**Comment by manuelma** [comment]
Something done. I didn't manage to do the single-shot resource advertising at project loading. It feels that the design for resource updating is more link oriented than item oriented. I didn't want to change that, although it might be more logical and perhaps we can do it in the future.

So I ended up implementing the missing resource tracking system you suggested @soininen. I like it. So now, if one disconnects the provider of a resource that's going into the tool arguments, we show an exclamation point notification about the missing resource. Let's see how this works, at least project loading is not affected anymore.
