### ISSUE TITLE
Exporter spec editor: set the fixed table name directly in the options?

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1383]
Currently, if one selects fixed table name, a new row is prepended to the mapping spec table, where one can set the fixed table name under the 'Mapping type' column. I don't like this too much, because the table name is certainly not the 'Mapping type'. 

Would it be better if we could set the fixed table name directly in a line edit next to the corresponding checkbox? like in the screenshot below:

![exporter](https://user-images.githubusercontent.com/11472756/115874831-94569180-a412-11eb-8ed6-052172d6f16f.png)

Thoughts? @soininen 

I will give it a shot, and push it in a single commit so we can easily revert it if I'm missing something.

**Comment by jkiviluo** [comment]
I think this makes more sense.

**Comment by manuelma** [comment]
Done. I think I was missing the fact that the implementation relies on having a `FixedValueMapping` as root, which would naturally go to the top of the table.  That would explain why @soininen adopted the previous approach, but for the UI it definitely makes more sense to do it the way it is after ffa8bbb. So I don't think we'd need to revert it.
