### ISSUE TITLE
Tool spec editor: Save specification and program files together

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1384]
At the moment we have the possibility to edit program files in the Tool spec editor. However, the program file and the specification file are saved separately. Each has its own menu entry and keyboard shortcut. That's a bit confusing and not very useful. I'm thinking it would be better if we merged these two actions into one action. So 'Save', or alternatively Ctrl+S, would save the spec file and all the modified program files. What do you think?

**Comment by soininen** [comment]
Makes a lot of sense.

**Comment by manuelma** [comment]
Thanks, I'll work on it. Shouldn't be too big of a change to get for 0.6

**Comment by manuelma** [comment]
Done by above commit. Seems to be working just fine.

I had to make one decision though: whether or not to merge the undo stack of the modified program files with the 'main' undo stack of the spec itself. I tried it out and after testing it a little bit, I decided it felt weird. So in the end, each program file has a separate undo stack, and separate from the spec's. 

If you think it's better to merge all undo stacks into one, I can do it and we can try it, it's fairly easy. So please just let me know.

**Comment by jkiviluo** [comment]
Great job!

I think it's better to have separate undo stacks.

**Comment by manuelma** [comment]
Thanks! let's close this and maybe open a new one about merging the stacks if ever needed.
