### ISSUE TITLE
User Guide update

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1386]
User Guide needs an update for release-0.6. Below is the current table of contents and a suggestion for a responsible person for each section/chapter. Please mark the section with a check mark after it's ready for review.

Contents:

- [x] [@PekkaSavolainen] Getting Started
- [x] [@manuelma] Tutorials
- [x] [@PekkaSavolainen] Setting up External Tools
- [ ] [@PekkaSavolainen]Main Window
- [x] [@soininen] Project Items
- [x] [@manuelma] Tool specification editor
- [x] [@soininen] Executing Projects
- [x] [@PekkaSavolainen] Settings
- [x] [@manuelma] Spine database editor
- [x] [@soininen] Plotting
- [x] [@soininen] Parameter value editor
- [ ] [@manuelma] Importing data (importer spec editor)
- [x] [@soininen] Exporting data (exporter spec editor)
- [ ] [@manuelma] Use datapackage option on links
- [x] [@PekkaSavolainen] Terminology
- [x] [@PekkaSavolainen] Dependencies
- [x] [@PekkaSavolainen] Contribution Guide for Spine Toolbox
- [x] [@soininen] Developer documentation

New sections:
- [x] @PekkaSavolainen How to set up SpineOpt.jl
- [x] @PekkaSavolainen Execution Modes
- [ ] @manuelma Parallel execution (maybe this should be part of *Executing projects* above, not sure)

**Comment by manuelma** [comment]
Maybe we can split "Importing and exporting data" into "Importer" and "Exporter", and take one each one? @soininen

**Comment by manuelma** [comment]
I've replaced "Spine datapackage editor" (now gone), by the new solution "Use datapackage option on links".

**Comment by PekkaSavolainen** [comment]
> Maybe we can split "Importing and exporting data" into "Importer" and "Exporter", and take one each one? @soininen

There's the *Project Items* chapter as well, maybe "Importer" and "Exporter" should go there..

**Comment by manuelma** [comment]
> There's the Project Items chapter as well, maybe "Importer" and "Exporter" should go there..

Sounds good, but for consistency we should have "Tool specification editor" also in that section.

**Comment by PekkaSavolainen** [comment]
Sure, maybe better to look at the chapter distribution after everything is up-to-date.

**Comment by soininen** [comment]
I kind of like the current organization where the Project items page contains short descriptions of each item and links to full descriptions. If we move all information to a single page it might become quite lot to stomach for readers.

**Comment by soininen** [comment]
If we end up restructuring the chapters we may want to consider merging Plotting and Parameter value editor chapters into Spine database editor.

**Comment by manuelma** [comment]
Parameter value editor is currently used in Importer spec editor too. It allows one to import a complex parameter value via a constant mapping. So maybe it's better if it has its own chapter.

Plotting could be in Spine DB editor, yes (unless for some reason we want to start plotting somewhere else?)

**Comment by soininen** [comment]
> Parameter value editor is currently used in Importer spec editor too.

Cool, I wasn't aware of that! Lets keep it in a separate chapter, then.

**Comment by PekkaSavolainen** [comment]
User Guide is now (almost) up-to-date, I'll bring the *.rst files from release-0.6 to master because that is our 'latest' now. Closing...
