### ISSUE TITLE
SpineOpt installation issues

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1387]
After getting feedback from @Mastomaki (Jussi) on SpineOpt documentation (including installation), I tried to install Spine Toolbox and SpineOpt on a clean machine. Spine Toolbox comes through nice, but Julia and SpineOpt are not working (on Windows at least). 

- Toolbox should automatically detect the Python kernel where the Toolbox runs and choose that as the kernel (
- After installing Julia, it would be nice to get an automatic Julia Kernel spec based on that Julia install. Now there is an additional step of creating that Kernel spec with bit obscure information requirements: name (what for? isn't this just julia?) and Project (what does that mean in this context? What this folder will be used for - just for SpineOpt?)
- Finally, Julia Console does not seem to find the Toolbox Python, which is now my Toolbox Python Kernel (after I selected it). As a consequence, it doesn't find Spine_DB_API. I can't make SpineOpt work.

**Comment by manuelma** [comment]
Thanks a very much for this issue. It looks there's a lot of misinformation around. We have failed to pass some important messages about SpineOpt usage.

> After installing Julia, it would be nice to get an automatic Julia Kernel spec

After installing julia, all one need to do is enter the path to that julia in settings->tools, select 'Execute on console", and accept the settings. No need to go to Kernel Editor. Accepting the settings creates the right kernel for that julia automatically.

(There is a point here about making Kernel Editor simpler, and ask only the important things. Name and project should be totally optional for Julia kernels.)

> Finally, Julia Console does not seem to find the Toolbox Python, which is now my Toolbox Python Kernel (after I selected it). As a consequence, it doesn't find Spine_DB_API. I can't make SpineOpt work.

SpineOpt doesn't need PyCall, so this point doesn't make a lot of sense. Can you describe more in detail how SpineOpt doesn't work? Which steps are you following, what are you getting back?

**Comment by Mastomaki** [comment]
Hello!

I have Julia 1.2 and 1.5 installed. At first only 1.2 was visible in the Settings->Tools->Julia. After running Kernel spec editor, version 1.5 also appeared in the listbox.

**Comment by PekkaSavolainen** [comment]
There's a new section now in User Guide on how to use SpineOpt.jl in Spine Toolbox (https://spine-toolbox.readthedocs.io/en/release-0.6/how_to_run_spineopt.html). Please read it.

**Comment by PekkaSavolainen** [comment]
Also see sections https://spine-toolbox.readthedocs.io/en/release-0.6/setting_up.html and https://spine-toolbox.readthedocs.io/en/release-0.6/execution_modes.html

If something does not work, please make a new issue with reproducible steps.
