### ISSUE TITLE
Remove boiler plate code for python and julia console

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1391]
Each item only needs at most one console at a time. However we have independent UI and API for Python and Julia consoles. This is not very scalable, so I think we should just have ONE console per item, that can be either Python or Julia depending on the particular case.

I will give it a try now.

**Comment by manuelma** [comment]
Done by above commits. I think this is better, but please let me know if you don't like it and I will revert it.

**Comment by PekkaSavolainen** [comment]
Haven't seen any problems related to this. Closing...
