### ISSUE TITLE
Don't check dependency versions at startup, users should upgrade after pull

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1392]
In slack, @jkiviluo @ererkka @soininen @PekkaSavolainen and myself agreed on that we won't be reminding users about upgrades anymore. They need to run `pip install -U ...` as instructed in the README every time after git pull.

I will make the changes in master to account for this.

CC @DillonJ

**Comment by manuelma** [comment]
To expand: the reason for this decision is that we developers need to do too many shenanigans to print those reminders. Basically we need to bump version numbers in one repo, and variables indicating the required version in another repo, almost constantly. This damages development, clutters our git history, and the payback is too low.

**Comment by DillonJ** [comment]
I'm not necessarily saying that this isn't the appropriate way forward, however it was *very* convenient getting the command that needed to be run to upgrade versions of spinedb_api and engine. Also, running `python -m pip install --upgrade -r requirements.txt` takes a while even when there are very few packages to upgrade... which is slightly annoying when you need to do it often. 

Could the tasks that need to be carried out be automated using a script perhaps?

**Comment by manuelma** [comment]
> it was very convenient getting the command that needed to be run to upgrade versions of spinedb_api and engine

Yes, we were spoiling you big time... You can have a batch script that just runs:

```
pip install --upgrade git+https://github.com/Spine-project/Spine-Database-API.git#egg=spinedb_api
pip install --upgrade git+https://github.com/Spine-project/spine-engine.git#egg=spine_engine
pip install --upgrade git+https://github.com/Spine-project/spine-items.git#egg=spine_items
```

...and run it every time after `git pull`. Should be fast.

**Comment by PekkaSavolainen** [comment]
See #1453 and README.md for updated instructions on how to upgrade requirements if you're running Spine Toolbox using the source codes from Git directly.
