### ISSUE TITLE
Tool box with Python code not finishing and Jupyter console not showing

### ISSUE THREAD

**Issue by jimhommes** [Spine-project/Spine-Toolbox#1393]
After latest pull I'm unable to execute my project. What happens is that when the first Tool block is executed, which contains Python code, the project hangs. The icon animation is working and suggests that it's doing something, but it doesn't continue. When pressing the 'Stop process' button the console says 'Stopping process...' but has no effect. After pressing again it says 'No process to stop' (or in that sense).

I tried to recreate this in a new project, where I tried to execute one block with Python code with only a print statement. Now the execution log states that the execution was successful, but Spine does not show the Jupyter console where the print statement would be shown. 

So, to recreate:

1. Create new project
2. Create Tool Block
3. Inside the specification: name the specification, select Python and create a new Python file
4. Insert Python code like `print("test")` and save through the save file button (note: this was really hidden and confusing since `ctrl+s` saves the tool specification, not the code)
5. Execute project

**Comment by manuelma** [comment]
At the moment we're asking users to do all steps here for upgrading: https://github.com/Spine-project/Spine-Toolbox#upgrading

So if you just pulled the latest master and didn't run `python -m pip install --upgrade -r requirements.txt` after that, you might be getting a lot of errors.

Can you confirm that this is not the case? And if it is, can you check if running `python -m pip install --upgrade -r requirements.txt` fixes all the problem?

**Comment by manuelma** [comment]
Please check https://github.com/Spine-project/Spine-Toolbox/issues/1392 where we discuss this decision.

**Comment by jimhommes** [comment]
Ah thanks, that clears it up. I missed that discussion. After the upgrades I am indeed getting multiple errors (runtime), do you think a reinstall is in order?

**Comment by jimhommes** [comment]
After a quick reinstall (and install as per instructions), I'm getting this error when trying to launch:
```Traceback (most recent call last):
  File "C:\Users\Jimho\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Jimho\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Dropbox\workspace\Spine-Toolbox\spinetoolbox\__main__.py", line 22, in <module>
    return_code = main()
  File "E:\Dropbox\workspace\Spine-Toolbox\spinetoolbox\main.py", line 62, in main
    window = ToolboxUI()
  File "E:\Dropbox\workspace\Spine-Toolbox\spinetoolbox\ui_main.py", line 188, in __init__
    self.parse_project_item_modules()
  File "E:\Dropbox\workspace\Spine-Toolbox\spinetoolbox\ui_main.py", line 303, in parse_project_item_modules
    self._item_categories, self.item_factories = load_project_items()
  File "E:\Dropbox\workspace\Spine-Toolbox\spinetoolbox\load_project_items.py", line 51, in load_project_items
    module_material = _find_module_material(module)
  File "E:\Dropbox\workspace\Spine-Toolbox\spinetoolbox\load_project_items.py", line 65, in _find_module_material
    submodule = __import__(modname, fromlist="dummy")
  File "C:\Users\Jimho\AppData\Local\Programs\Python\Python37\lib\site-packages\spine_items\gimlet\executable_item.py", line 27, in <module>
    from spine_engine.execution_managers.process_execution_manager import ProcessExecutionManager
ModuleNotFoundError: No module named 'spine_engine.execution_managers.process_execution_manager'; 'spine_engine.execution_managers' is not a package```

I've also manually tried to install/upgrade spine_engine (spinedb_api and spine_items too, for that matter) but unfortunately no effect.

**Comment by manuelma** [comment]
https://github.com/Spine-project/spine-engine/blob/master/spine_engine/execution_managers/process_execution_manager.py

There's the not found module in spine_engine's master branch... So I don't know what's wrong...

**Comment by jimhommes** [comment]
Uninstalling the modules and reinstalling through `python -m pip install -r requirements.txt` did the trick. Thanks for your help!

**Comment by manuelma** [comment]
Nice! Sorry for the trouble!
