### ISSUE TITLE
Plugins and specification name clashes

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1394]
Currently, we do not guard against name clashes between project's specifications and specifications that come with plugins. Specification names need to be unique since we identify them by the name only. There seems to be three cases we need to cover:

1. A project that is being loaded contains specifications with the same name as existing plugin specifications. We could temporarily rename project's specifications and issue warnings to user so they can take action.
2. A plugin that is being installed contains specifications with the same name as existing specifications in currently open project. We could cancel the installation process and issue a warning.
3. A plugin that is being installed contains specifications with the same name as existing plugin specifications. We could cancel the installation process and issue a warning.

**Comment by manuelma** [comment]
> since we identify them by the name only

how about identifying them by plugin name + spec name instead? Does that help? that means we need to validate name uniqueness within each plugin, as well as plugin name uniqueness, which may be easier...

**Comment by soininen** [comment]
> how about identifying them by plugin name + spec name instead?

I was thinking the same but it is not a trivial change because then all specification supporting project items need to take the plugin name into account. We'd need to show the plugin name in all widgets for clarity, too. It may still be a nice option, however.

Maybe we could look into disabling plugins that have clashing names as well.

**Comment by manuelma** [comment]
Good point. Unrelated, I think we need to stop name clashes already in the plugin registry repo.

**Comment by soininen** [comment]
Implemented by the above commits (and probably some others lost to other issues)

1. If a specification plugin already exists, project doesn't load its own plugin.
2. If project contains a specification that is being installed as a plugin, project will continue to use its own specification and the plugin's specification button will be disabled
3. We'll deal with this in plugin registry repo as @manuelma commented above.
