### ISSUE TITLE
Parameter value math in Data Transformer

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1395]
Discussed at Virtual 2021 meeting.

There is a need to apply computations to parameter values when they are queried from the database. Use cases include unit conversions (e.g. to support different model generators), scaling and aggregation. We could implement this by adding a math manipulator to `spinedb_api` and a corresponding interface to Data Transformer.

Initially we should support a predefined set of operations and their combinations:
- negation
- multiplication
- reciprocal
- aggregation for containers: sum, mean, min, max.

Negation, multiplication etc. should apply to individual elements in containers.

**Comment by soininen** [comment]
Implemented.

**Comment by manuelma** [comment]
Only spine_items was affected?

**Comment by soininen** [comment]
> Only spine_items was affected?

spinedb_api and Toolbox too.

**Comment by manuelma** [comment]
Can you describe the changes concerning `from_database` and `to_database`? I need to resolve some conflicts related to lifting the type property from the json.

**Comment by soininen** [comment]
> Can you describe the changes concerning from_database and to_database?

There is now a new filter/manipulator which inserts a special prefix to parameter's JSON when querying the value. `from_database()` checks for this prefix, and if it exists

1. cuts the prefix from the JSON
2. parses the value as before
3. calls `parameter_value._transform()` that applies the value transformation contained in the prefix

There are no changes to `to_database()`.

Let me know if you need more information.

**Comment by manuelma** [comment]
Thanks very much! That's very clever, I like it.

I'm working on making the `value` column in the database of type BLOB which means some adaptations to those two functions. But there shouldn't be any problems.

We'd need to discuss a bit of strategy I think. Because the BLOB for the moment will just hold the encoded JSON, but my idea is to move away from the JSON and use a nice binary format in some near future. So the parameter value coming from the db will be a BLOB, and then prefixing the DT operation might requiring some delicacy. But I think we should be ok, what do you think?

**Comment by soininen** [comment]
> But I think we should be ok, what do you think?

If we can modify the blob in the query like we do now with JSON then I think we're fine. However, it may be that SqlAlchemy refuses the string concatenation operation if the value column's type is BLOB. You should be able check it pretty easily if you run the manipulator's unit tests if you have already switched to BLOB. If that is the case, then we need to rethink the manipulator.

**Comment by manuelma** [comment]
Ok I will check.

Also I think there's an error in master? `from_database` is calling `transform` but the function is called `_transform`?

**Comment by soininen** [comment]
> Also I think there's an error in master?

Huh? On line 161 I have this in my `master`:

```python
        return _transform(value, transform_instructions)
```

**Comment by manuelma** [comment]
Ok cool, sorry my bad.

**Comment by manuelma** [comment]
What's the intended way of using this functionality? It looks like the client needs to query and then call `from_database()` with the `value` field of the result. If that's the case, I think it's more sane to add a new artificial column to the filtered query, that just contains the `instructions` string. Then we can provide `transform()` as another API end-point, that receives the value and the instructions and returns the new value.

What do you think?

**Comment by manuelma** [comment]
> I intended this to work completely transparently as our other filters/manipulators

I think I'm missing something. In your mind, how does a user make use of the functionality in their tool? Are they supposed to always call `from_database()` with the value? How does it work for non-python tools?

**Comment by soininen** [comment]
Good to know that the manipulator still works with BLOBs. I know the solution is not ideal and it would indeed be nice if we could apply the transformations directly to the values during queries. In any case, users that don't have access to `from_database()` still need to parse the values in one way or another. Perhaps it is not too much to ask them to take the transformation prefix into account while doing so.

**Comment by manuelma** [comment]
Yeah, I think you're right, it's not a very big deal.

Another option to do any arbitrary operations at "querying-time" is to use temporary tables to hold transformed values. Basically, we do the transformations in python at the moment of applying the filter. We insert the results into a temp table, and then join to that table in the replacement query. That enables arbitrary transformations for a certain price of course. I think we can try that after I merge my changes about the type thing.

For information, `from_database()` will take a second argument that is the value type, and `to_database()` will return a tuple of (db_value, type). So we have this: `x == from_database(*to_database(x))`

**Comment by soininen** [comment]
One nice thing with the `from_database()` implementation is that the transformations are evaluated lazily, i.e. the calculations are done only when the value is actually needed. Calculating the transformations when the filter is applied may result in unnecessary work but I don't know if that is really an issue. I guess we can live with it. It seems that all our options have some trade-offs.

**Comment by manuelma** [comment]
I think the main difference here is the multiplier (symbol) doesn't live in the db, but in the DT's spec. Other than that it feels like exactly the same.

**Comment by manuelma** [comment]
I also think (@soininen please correct me if I'm wrong) that at the moment the operation is defined at parameter-definition level, not parameter-value. So basically you can't transform the `capacity` value for a certain `unit` and not for the others.

**Comment by soininen** [comment]
The initial use case was unit conversion for this feature and I thought it makes more sense to apply it on class level. It should be possible to extend the technique to entity level if needed.
