### ISSUE TITLE
Prompt toolbox user from engine and wait for answer

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1396]
This is a feature I have in mind since some time ago, mainly to enable database upgrade mid-run. It sometimes happens that you run SpineOpt with an output db that doesn't have the right version. The process fails at the end and the user loses their run. Same goes for importer.

I want to prompt the user in real time in all those cases. Do you want to upgrade the database? I think we can easily extend our engine-toolbox communication system to enable this. Will give it a try.

**Comment by soininen** [comment]
Just for completness sake, all project items that interact with databases may encounter an outdated database. This includes Tools, Views and Exporters, at least.

**Comment by manuelma** [comment]
I will implement something that all project items can use. It's probably a logger message that is able to wait synchronously on the answer.

**Comment by PekkaSavolainen** [comment]
Another option here is to use the ready_to_execute() method in data store's executable_item to check if the db is outdated. ready_to_execute() is ran in backwards execution mode and if it returns False, it can be used to prompt the user that something is wrong in the DAG and not run it at all if outdated db revisions are found.

**Comment by manuelma** [comment]
That's another possibility. I think it's ok to do it that way too, but I definitely prefer to prompt the user if they want to upgrade, rather than just cancelling the workflow right away.

**Comment by PekkaSavolainen** [comment]
But if you want to do the upgrade mid-execution, then it should do it automatically without a prompt. Think of a use case when user leaves the execution running for the whole night after leaving the office. I think the user is going to be pissed if in the morning he/she finds that there's a prompt that requires an Ok button click midway through the execution.

**Comment by manuelma** [comment]
Are you suggesting that we upgrade without asking the user? That's a possibility, but we should be consistent and also do it when opening the db editor for example. Otherwise the user wouldn't know what to expect?

**Comment by soininen** [comment]
Automatic updates during execution could be a setting.

**Comment by manuelma** [comment]
I think we can prompt users as part of `ready_to_execute()`, so it will happen at the beginning of execution. Let's go with that and see what happens.

**Comment by manuelma** [comment]
> ready_to_execute() is ran in backwards execution mode

Is it? I think it's only run in forward exec mode?? @PekkaSavolainen

**Comment by manuelma** [comment]
So I tried prompting in `ready_to_execute()`, but that doesn't work for dbs being advertised backwards.

Then I moved `ready_to_execute()` to the backward sweep and that worked, but it was kinda awkward because it was unclear where the prompt was coming from. So I ended up prompting in `execute()` directly. I'm happy with it so I will close now.

**Comment by PekkaSavolainen** [comment]
Hope you put the ready_to_execute() back to forward execution. I erroneously said in a previous comment that ready_to_execute() is run when doing backwards execution but this was a mistake. Putting the ready_to_execute() to backwards execution breaks selected execution

**Comment by manuelma** [comment]
Yes, I didn't touch it.

**Comment by PekkaSavolainen** [comment]
@manuelma Has this feature been removed? I don't see any message box when executing Data Stores with outdated db's.

**Comment by manuelma** [comment]
I also noticed. I didn't remove it so it's probably broken. I can take a look later today. If you have/find more information that can be helpful.

**Comment by PekkaSavolainen** [comment]
It's interesting, from the user's point-of-view it seems like there is no change to how it worked previously. You just need to upgrade the sqlite Db's manually like before.

**Comment by manuelma** [comment]
@PekkaSavolainen do you have happen to have an old DB that needs updating lying around?
