### ISSUE TITLE
SpineOpt plugin install broken

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1400]
Looks like the 'Plugin' tool spec model update is broken when installing Plugins.

This happens when Installing SpineOpt Plugin and then trying to make a Tool by dragging and dropping `Run SpineOpt` from the plugin toolbar into Design View.

![SpineOpt_plugin_install_broken](https://user-images.githubusercontent.com/43600314/117413862-25535f80-af1f-11eb-9d24-858936cc090c.png)

As can be seen, the dropdown menu is empty. After restart it works, but not immediately after the SpineOpt plugin has been installed.

**Comment by PekkaSavolainen** [comment]
@soininen, you want to do this as well, while looking into #1399?

**Comment by soininen** [comment]
I'm planning on refactoring the plugin system a bit anyhow. I think can work on this as well.

**Comment by manuelma** [comment]
What do you have in mind @soininen ?

**Comment by soininen** [comment]
I'm thinking about moving project specification loading and management stuff to `SpineToolboxProject` which I think is more suitable place for such project specific stuff than `ToolboxUI`. `ToolboxUI` would still manage the specifications that come with plugins and forwards those to the project when it is loaded. Project would then be responsible on managing clashes between its own and plugins' specifications.

**Comment by manuelma** [comment]
Sounds good. I think it's good then that you @soininen handle #1399 as well, if you don't mind, and fix/clean the plugin system too.

**Comment by soininen** [comment]
Yes, I'm hoping to get a holistic solution to all these issues on the same go.

**Comment by PekkaSavolainen** [comment]
This is fixed. Please make a new issue about the plugin refactoring if needed.
