### ISSUE TITLE
Database editor occasionally doesn't open properly.

### ISSUE THREAD

**Issue by Tasqu** [Spine-project/Spine-Toolbox#1401]
Sometimes when trying to open a new database editor via either double-clicking a datastore object or pressing the `Open editor...` button in the `Data Store Properties` tab, the database editor doesn't open and the following traceback pops up:
```
Traceback (most recent call last):
  File "c:\data\spine\spine-items\spine_items\data_store\data_store.py", line 364, in open_url_in_spine_db_editor
    self._toolbox.db_mngr.open_db_editor(db_url_codenames)
  File "c:\data\spine\spine-toolbox\spinetoolbox\spine_db_manager.py", line 1760, in open_db_editor
    multi_db_editor = next(self.get_all_multi_spine_db_editors(), None)
  File "c:\data\spine\spine-toolbox\spinetoolbox\spine_db_manager.py", line 1729, in get_all_multi_spine_db_editors
    widget = QWidget.find(window.winId())
AttributeError: 'PySide2.QtWidgets.QWidgetItem' object has no attribute 'winId'2
```
This doesn't seem to happen when first opening a database editor on a new Toolbox session, but after opening and closing the DB editor a few times I sometimes run into this issue.

This issue can be bypassed by using `File -> New DB Editor` to force the DB editor open, and then opening the desired database via the editor, but its still a minor inconvenience.

**Comment by manuelma** [comment]
This is totally fixable, I will work on it.

**Comment by jkiviluo** [comment]
@manuelma I wonder if this bug has been crushed?

**Comment by manuelma** [comment]
Yeah, @soininen add a check for this to `_get_all_muti_spine_db_editors` or something.
