### ISSUE TITLE
Exporter filtering breaks when not outputting parameter values

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1404]
When outputting parameter values:

![image](https://user-images.githubusercontent.com/40472544/117815184-e3ebe880-b26d-11eb-818b-1f2d64c3b4bf.png)

When not outputting parameter values:

![image](https://user-images.githubusercontent.com/40472544/117815382-1564b400-b26e-11eb-9454-ae417fd8073f.png)

**Comment by soininen** [comment]
This should be fixed now. Hopefully I didn't break any existing export mappings as the changes were somewhat intrusive. @jkiviluo can you confirm filtering works now as expected?

**Comment by jkiviluo** [comment]
Yes, all seems to be fine. Great work!
