### ISSUE TITLE
Exporter is failing to rename Mappings

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1406]
When renaming a mapping, the exporter seems to be keen on renaming the last mapping in the mappings list even if you are renaming an earlier entry in the list. This may start to happen only once you have several entries (like 10+). The ordering does not work when more than 10 names (10 is before 2 in the alphabetic). It can also crash Toolbox quite easily when doing this. Traceback:

```
Traceback (most recent call last):
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\exporter\mvcmodels\preview_tree_model.py", line 127, in parent
    row = self._mapping_names.index(mapping_name)
ValueError: b'2currentChanged(QModelIndex,QModelIndex)' is not in list
Traceback (most recent call last):
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\exporter\mvcmodels\preview_tree_model.py", line 127, in parent
    row = self._mapping_names.index(mapping_name)
ValueError: b'2currentChanged(QModelIndex,QModelIndex)' is not in list
```

**Comment by soininen** [comment]
Specification editor window should now rename the correct mapping. I'll be looking into the other issues next.

**Comment by soininen** [comment]
Sorting should now work better. I haven't been able to reproduce the Traceback. Perhaps it has been fixed by the previous commits or perhaps I haven't been trying hard enough.

**Comment by jkiviluo** [comment]
Great. I can confirm a successful rename of 20 mappings that were pending a renaming.
