### ISSUE TITLE
Tool specification: filename change not saved

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1409]
If I change the filename (F2) in Input_output files, that doesn't update the tool specification status to indicate that something has changed and when I close the specification editor, then the new filename hasn't been changed.

Also 'Program files' names cannot be changed. Maybe that's ok.

**Comment by soininen** [comment]
The above commit should fix the issue and the little typo in the dock widget's title ('Input _output files' -> "Input & Output files').

**Comment by jkiviluo** [comment]
Great, seems to work!
