### ISSUE TITLE
Items move too easy

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1413]
Not sure if others feel the same the way, but I'm all the time re-arranging the icons in the Design view by accident, because when I try to select them, they move very easily. That makes the project to be 'changed' and it feels bad. 

Would it be possible to require e.g. a bit longer left mouse button duration before the move starts?

**Comment by soininen** [comment]
As a workaround, you can undo the move making the project 'clean' again.

**Comment by PekkaSavolainen** [comment]
@jkiviluo may be describing an actual bug that I've seen. Happens when messing around with parallel execution. The project item icons in Design View jump to different places just by selecting them and it becomes close to impossible to do anything without restarting the application. Is this the case or are your mouse clicks too 'heavy' by default?

**Comment by jkiviluo** [comment]
I haven't seen that bug, so I guess my clicks are too heavy. Although in order to not do this, I think you need to be really careful with your mouse that it doesn't move when you click. So, maybe it depends on your mouse settings too.

**Comment by PekkaSavolainen** [comment]
There's a one-liner that resolves this. In project_item_icon.py:

```python
    def mouseReleaseEvent(self, event):
        for icon in self.icon_group:
            icon.current_pos = icon.scenePos()
        # pylint: disable=undefined-variable
        if (self.current_pos - self.previous_pos).manhattanLength() > qApp.startDragDistance():
            self._toolbox.undo_stack.push(MoveIconCommand(self, self._toolbox.project()))
            event.ignore()  # NEW LINE
        super().mouseReleaseEvent(event)
```

This way it only makes the project dirty if items are moved more than 10 pixels. Should I commit?

**Comment by PekkaSavolainen** [comment]
Done.
