### ISSUE TITLE
Execution log: follow the progress

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1414]
When I'm at the end of the execution log and the tool executes, I'd like the execution log to follow the execution output. Now it remains behind and I need to go scrolling in order to see the end result of the execution (when building a model, that's typically the error message you want to see).

**Comment by jkiviluo** [comment]
And if I'm not scrolled to the end of the execution log, then it should stay in place (because I might be reading that spot).

**Comment by PekkaSavolainen** [comment]
Done for both Event Log and Execution Item logs. In my tests it works exactly as requested but if there's something I missed, please reopen.
