### ISSUE TITLE
New specification cannot be named if the editor is dirty

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1418]
We update specification's name tab only when the editor's clean status changes making it impossible to save a new specification in some cases.

Steps to reproduce:

1. Start editing a new specification. Modify anything else than the specification's name. Any specification type will do.
2. Give name to the specification.
3. Notice that the tab's name is not changed.

**Comment by soininen** [comment]
Looks like I was too quick to open this issue. Data transformer for sure is broken since it doesn't fully use the undo stack and will be fixed under another issue. The other specification edi,ors, on the other hand. seem to work as expected.

**Comment by manuelma** [comment]
I remember not testing DT spec editor extensively last time I refactored. Please let me know if you need any help with this, because I also remember not writing too many docstrings for the new SpecificationEditorBase class (or whatever I named it).
