### ISSUE TITLE
Possibility to set index titles in case of a map value

### ISSUE THREAD

**Issue by jimhommes** [Spine-project/Spine-Toolbox#1421]
When importing a "map" value, I have an index which represents a year. However, at the moment there is no title that suggests this from the database editor side. 

Is there a way of importing a column title with this map? 

Here is a screenshot provided by my Photoshop skills:
![python_2021-05-31_18-04-29-050_8l2ozVIO1l](https://user-images.githubusercontent.com/5991344/120219111-fdfc6380-c23a-11eb-866a-0c0724affbcd.jpg)

**Comment by soininen** [comment]
If I uderstood correctly what you're trying to achieve here, then no, Map doesn't currently support naming its indexes. We'd like to have the feature though, see Spine-project/Spine-Database-API#96.

**Comment by jimhommes** [comment]
Ah sorry, I hadn't looked for an issue over at the Spine Database Github. That does describe what I desire.

**Comment by jkiviluo** [comment]
I'm closing the issue.
