### ISSUE TITLE
Manually entering a number for "map dimensions" not working correctly

### ISSUE THREAD

**Issue by jimhommes** [Spine-project/Spine-Toolbox#1424]
In an import definition it's possible to set the amount of dimension for a Map value. This works by selecting the number and pressing up or down to change the value, or by pressing the arrows. 

When entering a value by typing it out, it doesn't work. Say it's at 1 dimension, and I enter 10 and press enter, it does a +1 twice.

**Comment by manuelma** [comment]
Thanks! Same happens for the relationship dimension spinbox. It either goes one up or one down. I will change it now so it can 'jump' arbitrarily.

**Comment by manuelma** [comment]
I think the above commit resolves this. Please reopen if not the case.
