### ISSUE TITLE
Importer Preview when working with large Excel sheets 

### ISSUE THREAD

**Issue by jimhommes** [Spine-project/Spine-Toolbox#1426]
When working with large Excel sheets, the preview of the importer attempts to show everything halting the software for a while. Would it be possible for the preview to only load a segment of this data? That should be sufficient to create the import definition.

**Comment by manuelma** [comment]
I can look into this.

**Comment by eriharriso** [comment]
I have another notion/problem related to importing large Excel sheets.

It seems the importer shows up to 99-100 columns per sheet: trying to move towards higher column numbers in the importer previewer just brings the user back to column 1.

I tried unsuccessfully to import relationship class parameters from a higher column number (#134) to an sqlite database: while there were no reported errors, the relationship class pivot table was not then visible in the data store editor and I couldn't access the info. I would need to import data from column numbers up to ~300-400: is this or could it be made possible without editing the original Excel files?

**Comment by manuelma** [comment]
@eriharriso feels like a different issue to me? Am I missing something?

If not, can you please create another issue with the same description?

**Comment by eriharriso** [comment]
> @eriharriso feels like a different issue to me? Am I missing something?
> 
> If not, can you please create another issue with the same description?

Probably you are not, I created another issue.

**Comment by manuelma** [comment]
Thanks very much @eriharriso

**Comment by manuelma** [comment]
Something done here. Feels faster, so I will close and please reopen if not satisfactory.
