### ISSUE TITLE
Do not open a console when executing Tools

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1430]
In a frozen Windows application, every time a user executes a Python, a Gams, or a Julia Tool (subprocess mode), or anything with Gimlet, a console opens up momentarily and then disappears. 

The problem is a lot worse when execution happens in the Jupyter (Python or Julia) Consoles. A new console is opened for each executed Tool and these do not disappear. Also, some of these consoles remain open even after the app is closed. This is very inconvenient and makes the frozen application almost unusable.

But have no fear, a couple of commits will be pushed shortly.

**Comment by PekkaSavolainen** [comment]
Done. The fix will be in 0.6.0-final.2 installation bundle (available soon).

All the consoles are now gone except in one case. When running a Julia Tool, there is a console flash for some unknown reason. It does not happen when running a Julia script with a Gimlet so this is quite odd. If anybody knows the reason, I am interested in hearing about it.

**Comment by PekkaSavolainen** [comment]
final.2 now available (https://github.com/Spine-project/Spine-Toolbox/releases/tag/0.6.0-final.2). Please reopen if needed.

**Comment by manuelma** [comment]
This change breaks persistent process interruption on windows. Apparently the CREATE_NEW_PROCESS_GROUP flag doesn't play well with sending the CTRL_C_EVENT signal?
I will try to fix this now.

**Comment by manuelma** [comment]
I might have fixed this, @DillonJ please give it a try whenever you get the chance?

I will try to write a test for this, but in the meantime, I suggest we check all the functionality manually before messing with it. It seems very difficult to anticipate all the consequences of `creationflags` on Windows.

**Comment by DillonJ** [comment]
Hi @manuelma 

Thanks for this. I confirm that the toolbox "stop execution" button now has the expected result with julia tools (SpineOpt in my case). I also confirm that the interrupt console context menu item works as expected.

The only issue I have now is that restarting the execution after it has been interrupted doesn't work and each of the consoles need to be restarted. I'm not sure if this is a problem or not, but in any case, here is the TB when trying to restart SpineOpt after an interrupt:

```
julia> # Running 'julia run_spineopt.jl http://127.0.0.1:61688 http://127.0.0.1:61689'
2-element Vector{String}:
"http://127.0.0.1:61688"
"http://127.0.0.1:61689"
Running SpineOpt for http://127.0.0.1:61688...
ERROR: LoadError: MethodError: no method matching _process_server_answer(::Int64, ::Dict{String, Any})
Closest candidates are:
_process_server_answer(!Matched::String, ::Any) at C:\Workspace\Spine\SpineInterface.jl\src\util.jl:417
_process_server_answer(!Matched::Nothing, ::Any) at C:\Workspace\Spine\SpineInterface.jl\src\util.jl:418
_process_server_answer(::Any) at C:\Workspace\Spine\SpineInterface.jl\src\util.jl:415
Stacktrace:
[1] _process_server_answer(answer::Dict{String, Any})
@ SpineInterface C:\Workspace\Spine\SpineInterface.jl\src\util.jl:416
[2] _run_server_request(server_uri::URIs.URI, request::String, args::String)
@ SpineInterface C:\Workspace\Spine\SpineInterface.jl\src\util.jl:412
[3] #_run_request#43
@ C:\Workspace\Spine\SpineInterface.jl\src\util.jl:543 [inlined]
[4] run_request(url::String, request::String, args::String; upgrade::Bool)
@ SpineInterface C:\Workspace\Spine\SpineInterface.jl\src\api.jl:864
[5] run_request
@ C:\Workspace\Spine\SpineInterface.jl\src\api.jl:862 [inlined]
[6] find_version(url::String)
@ SpineOpt C:\Workspace\Spine\SpineOpt.jl\src\data_structure\migration.jl:78
[7] run_spineopt(url_in::String, url_out::String; upgrade::Bool, mip_solver::MathOptInterface.OptimizerWithAttributes, lp_solver::MathOptInterface.OptimizerWithAttributes, cleanup::Bool, add_user_variables::Function, add_constraints::Function, update_constraints::Function, log_level::Int64, optimize::Bool, use_direct_model::Bool)
@ SpineOpt C:\Workspace\Spine\SpineOpt.jl\src\run_spineopt.jl:91
[8] top-level scope
@ C:\Users\jodyd\.spinetoolbox\plugins\SpineOpt\specifications\Tool\run_spineopt.jl:5
[9] include(fname::String)
@ Base.MainInclude .\client.jl:444
[10] top-level scope
@ none:1
in expression starting at C:\Users\jodyd\.spinetoolbox\plugins\SpineOpt\specifications\Tool\run_spineopt.jl:5


```

**Comment by DillonJ** [comment]
Actually, restarting the consoles is not enough in the case of SpineOpt - each time I try to run after an iterruption, I get the above, even after restarting the consoles... it looks the the socket server needs to be restarted also?

**Comment by DillonJ** [comment]
Actually, never mind, it's just because I didn't have the latest Spine Interface
