### ISSUE TITLE
Value editor does not accept Null

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1436]
If a column in the value editor has only Null values, the column stays empty. After leaving the value editor, it thinks there is one less dimensions and that column (dimension) is removed. So, it's not there anymore when re-opening the value editor. Maybe the Null value should be indicated similar to True and False.

**Comment by soininen** [comment]
Maps didn't even accept null values, now they do. Hopefully the editor works with nulls better, too.
