### ISSUE TITLE
Changing parameter value list name does not work

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1437]
When trying to change the parameter value list using the DB Editor "parameter value list" tab, the name does not change. Trying to change a parameter that uses that parameter value list will result in an error after this unsuccesful name change attempt.

It would be great if there was referential integrity from the value list names to the parameter value table.

**Comment by manuelma** [comment]
Thank you for this, I will fix it asap.

**Comment by manuelma** [comment]
Works after above commit, please reopen if I missed something.
