### ISSUE TITLE
Option to duplicate a specification

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1440]
Historically we enabled this by changing the spec name in the editor: this would create a new spec with the current settings. However recently we have inadvertently removed this feature, which I think it's a good thing because it wasn't too intuitive.

We need though a way to create a spec from an existing one and I'm thinking a 'Duplicate' action in the spec editor's menu can do the job. Will try something now.

**Comment by manuelma** [comment]
I think this is working. Anybody has tested it?

**Comment by PekkaSavolainen** [comment]
At least Julia and Python spec duplication works great. Ok to close by me.
