### ISSUE TITLE
Python console is stuck to the work dir it was created

### ISSUE THREAD

**Issue by ererkka** [Spine-project/Spine-Toolbox#1441]
### Steps to reproduce
1. Create a Python Tool with ‘Execute in Work directory’ selected. (Can be just a Hello world thing.)
2. Execute the item
2. Check current working dir of the Python Console with `import os; os.getcwd()`
3. Open the work dir and delete it’s contents (the script should be copied there)
3. Re-run same item, should fail.
4. Check working dir again, should be same as before and not changed to the new one

My Python Console output:

```python
>>> # Running 'python hello.py'
Hello!
>>> import os
>>> os.getcwd()
'C:\\Users\\ERERKKA\\AppData\\Local\\Temp\\hello__71e2423baa804bfeba6c8ab454f84649__toolbox'
>>> os.listdir()
['hello.py']
>>> os.remove('hello.py')
>>> os.listdir()
[]
>>> # Running 'python hello.py'
FileNotFoundError: [Errno 2] No such file or directory: 'hello.py'
File "<stdin>", line 1, in <module>
Traceback (most recent call last):
>>> os.getcwd()
'C:\\Users\\ERERKKA\\AppData\\Local\\Temp\\hello__71e2423baa804bfeba6c8ab454f84649__toolbox'
>>> os.listdir()
[]
>>> 
```

### Expected behaviour

Current working dir of the console would change to the new temporary work dir created by the app.

**Comment by ererkka** [comment]
Maybe this is related to the fact that the Python interpreter is somehow persistent.

**Comment by PekkaSavolainen** [comment]
A 'change work directory' command was missing on the Python persistent console side. Hopefully commit 85686e2 resolves this. Thanks for reporting.

**Comment by PekkaSavolainen** [comment]
I was a bit too quick to pull the trigger. Should be done now after commit bbb2aa8.

**Comment by ererkka** [comment]
Works! Thank you Pekka!

```
>>> # Running 'python hello.py'
Hello, I’m at C:\Users\ERERKKA\AppData\Local\Temp\hello__21a10505e5bd4b209115f2bd303db4dc__toolbox
>>> # Running 'python hello.py'
Hello, I’m at C:\Users\ERERKKA\AppData\Local\Temp\hello__c9fc4a811d3f486cba4d286a3c29d142__toolbox
>>> # Running 'python hello.py'
Hello, I’m at C:\Users\ERERKKA\AppData\Local\Temp\hello__3109bc3a4d374b90b6086a2d077cdd80__toolbox
>>> # Running 'python hello.py'
Hello, I’m at C:\Users\ERERKKA\AppData\Local\Temp\hello__6d871353fff74acfa47ea8cc0348d853__toolbox
>>> 
```
