### ISSUE TITLE
Tool specification editor is slow to respond

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1445]
The tool specification editor is for unknown reason very slow to respond. I believe it gets slower the more there are input and output files. FlexTool3 is an example project where the FlexTool3 tool is really slow (it has lots of input files). https://gitlab.vtt.fi/FlexTool/flextool3

**Comment by soininen** [comment]
How does 'slow to respond' manifest? I pulled the FlexTool3 project, opened both Tools' spec editors and didn't notice anything out of ordinary.

**Comment by jkiviluo** [comment]
Weird. For me it takes seconds to change focus when I e.g. left click between an input file and main program file. Or try to minimize the tool specification editor or try to do almost anything.

**Comment by soininen** [comment]
Does this happen immediately after you've opened Toolbox (start spinetoolbox, open project, open specification editor)?

**Comment by jkiviluo** [comment]
Not there anymore. Probably something was wrong with my setup. Sorry for the trouble.
