### ISSUE TITLE
Design view doesn't appear anymore

### ISSUE THREAD

**Issue by ymizero** [Spine-project/Spine-Toolbox#1447]
When I open a project, the "Design View" of the project doesn't appear anymore, even when trying to make it appear using the "Restore Dock Widgets" of the "View" section. 

I also tried to uninstall and re-install Spine Toolbox completely, but this didn't change anything and I still can't see the "Design View" of any of my projects.

You can see on the screenshot down below that Spine opens the project, even execute it but the "Design View" doesn't appear on the screen.

Does someone have an idea on how to fix this ? 

![image](https://user-images.githubusercontent.com/86708377/125430853-bf276a12-f7ac-4913-87fb-75af1e93e38d.png)

**Comment by soininen** [comment]
How did the Desing view disappear in the first place?

Unfortunately, the Restore Dock Widgets action seems to work here so I cannot reproduce this. Perhaps resetting window settings by deleting the SpineProject folder from Windows' registry using Registry editor helps?

**Comment by PekkaSavolainen** [comment]
I could not reproduce this either. I closed the Design View (x button in the top-right corner), quit the app and restarted, then clicked on View -> Dock widgets ->Restore Dock Widgets menu item and the Design View reappeared.

Design View item was in fact missing from the View->Dock widgets menu, (as can been seen from the pic in the issue description) so I added it there. Please reopen if this issue still persists.

**Comment by soininen** [comment]
> Design View item was in fact missing from the View->Dock widgets menu, (as can been seen from the pic in the issue description) so I added it there. Please reopen if this issue still persists.

Nice catch! I somehow mixed 'Project' menu item with Design view and missed the fact that Design view didn't have an entry in Dock widgets.
