### ISSUE TITLE
PATH issue - Standard Python Installation 

### ISSUE THREAD

**Issue by marcjamali** [Spine-project/Spine-Toolbox#1448]
Hello, 

While installing SpineToolbox using the recommended Standard Python Installation
At the step of "python -m pipx ensurepath", although the console shows "Success" and shows that the PATH environment variable has been updated  with 2 new paths, I had to add those 2 paths myself manually to go on with the installation process.  If not, even after rebooting the PC, pipx was not recognized in the command prompt.

Thanks anyway, SpineToolbox works and the installation process is way easier than before.

**Comment by PekkaSavolainen** [comment]
Hi @marcjamali. Are you using a Windows Store Python? You may have ran into this problem https://github.com/ofek/userpath/issues/25.

Thanks for the feedback.
