### ISSUE TITLE
Spine DB Editor Incorrect UI behaviour when deleting multiple relationships

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1449]
Steps to reproduce:

 - Open any db with a relationship class that has more than 1 member. I tested 3 members.
 - Select all the relationships
 - Choose "remove" from context menu

Expected behaviour: All relationships are removed and they disappear from the UI

Actual behaviour: One relationship disappears completely and only the relationship name for the other two is removed with the icons remaining. Committing, closing the DB and reopening confirms that the relationships are actually removed.

**Comment by DillonJ** [comment]
Reverting to commit b911535 ("Merge branch 'master' into lazy_db_editor", 2021-07-13) solves the issue for me

I guess this is related to #1451

**Comment by manuelma** [comment]
I can't reproduce this in latest master. Below is a screencast that shows how it works correctly in my system. What am I missing?


https://user-images.githubusercontent.com/11472756/126638986-c1302c60-7178-4072-bb49-352c0ca44d38.mp4

**Comment by manuelma** [comment]
Superseded by #1453
