### ISSUE TITLE
Problem with Toolbox update workflow

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1450]
Just pulled the latest toolbox and tried running and am getting the following traceback:

```
D:\workspace\Spine\Spinetoolbox>python spinetoolbox.py
Traceback (most recent call last):
  File "spinetoolbox.py", line 22, in <module>
    from spinetoolbox.main import main
  File "D:\workspace\Spine\Spinetoolbox\spinetoolbox\main.py", line 37, in <module>
    from .ui_main import ToolboxUI
  File "D:\workspace\Spine\Spinetoolbox\spinetoolbox\ui_main.py", line 52, in <module>
    from .widgets.settings_widget import SettingsWidget
  File "D:\workspace\Spine\Spinetoolbox\spinetoolbox\widgets\settings_widget.py", line 23, in <module>
    from spine_engine.utils.helpers import (
ImportError: cannot import name 'resolve_conda_executable' from 'spine_engine.utils.helpers' (C:\Program Files\Python\Python37\lib\site-packages\spine_engine\utils\helpers.py)
```
I'm suspecting this is due to https://github.com/Spine-project/Spine-Toolbox/commit/814db5a0191a0c017afecf371e263d0439562e37#diff-fe59b31c1f02b6b59e6177941639954846fcde7f966dd6cb4c19f6447e08e79e

I don't use Conda - I have a single Python installation and use it only for Spine Toolbox - I'm wondering do we want to at least allow this use case or not?

**Comment by DillonJ** [comment]
So, I tried this on another machine and as long as Anaconda is installed it works, even if you are not using it - but if you don't have Anaconda on your machine, I believe it is broken.

I we want to stick with this approach, we would need to signal that Anaconda is a prerequisite. My preference, though, would be for it to be optional.

**Comment by DillonJ** [comment]
Follow up is that I am still getting the above traceback with Anaconda installed (but not used to launch toolboox). This is working on my other machine and I can see what is different between the two

**Comment by DillonJ** [comment]
Ok, so to get this working, I needed to uninstall and reinstall spine-engine and spinedb-api... 

For clarity, it wasn't enough in my case to pull latest master and run pip install --upgrade -r requirements.txt

**Comment by manuelma** [comment]
#1453

**Comment by PekkaSavolainen** [comment]
Yes, I did something in #1453 about this. Let's continue there if needed.
