### ISSUE TITLE
Clicking on expand arrow in DB Editor treeview crashes toolbox

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1451]
Steps to reproduce:
 - Contact me on Slack for db
 - Open DB in DB editor
 - Click on the expand arrow of the temporal_block class

Toolbox should then crash

**Comment by DillonJ** [comment]
Reverting to commit b9115355 ("Merge branch 'master' into lazy_db_editor", 2021-07-13) solves the issue for me

**Comment by manuelma** [comment]
I can't reproduce this, check screencast below:


https://user-images.githubusercontent.com/11472756/126639068-9543b762-6c68-49d7-95c3-994f709e20a7.mp4

**Comment by manuelma** [comment]
Superseded by https://github.com/Spine-project/Spine-Toolbox/issues/1453
