### ISSUE TITLE
Spine DB Editor unpredictable behavior - loading, filtering, values not showing

### ISSUE THREAD

**Issue by jimhommes** [Spine-project/Spine-Toolbox#1455]
I'm assuming that after I pulled 69ec09d360e83d9b446238269cdc0b2e113e2469 I'm now experiencing very unpredictable behavior in regards to the Spine DB Editor and frankly it's unusable. It's possible that this is caused by large amounts of data and would like to discuss. When I view a small amount of data it acts as normal, but I believe this has something to do with pre-loading the information.

I have already tried reinstalling the Python dependencies and spine_items etc. as that has caused some grievances before. 

So in summary:
- Filtering by clicking on objects or object classes barely works. In some cases it does not show any values, or it shows the values "on top" of values of other classes. It can work with the workaround at the end of this list.
- The object tree does not load alphabetically anymore. I need to refresh the DB first for it to do so.
- Loading time in the beginning seems very long.
- A work around that works for my medium sized SpineDB is to select root in the object tree, and filter on 'object_class_name' and begin typing a string. If I do this, this seems to force a loading of all values (it does not show all object classes at first, but does so at the end), if this is done then it's possible to filter using the object tree. However, this workaround takes too long for my very large SpineDB to be practical.

Thanks for any help!

**Comment by manuelma** [comment]
Hi @jimhommes

Thanks very much and sorry for the troubles. The Db editor went through a large refactoring where I basically tried to make it more usable for large datasets, by increasing lazyness. I am sorry to hear this had the opposite effect instead. I am in holidays now so unable to work on this, but will fix all this as soon as I am back in three weeks from now.

**Comment by manuelma** [comment]
I was aware of the issues about ordering and filtering, but hearing that loading time seems longer than before is very surprising. Can you expand on that? We'd need some benchmarking to confirm... But then again, I won't be able to work on this for the next three weeks.

**Comment by jimhommes** [comment]
Hi @manuelma, no problem and thanks for getting back to me. With the loading time I'm referring to my workaround - the advantage is that it seems usable and responsive almost immediately, but it takes more time to select the filter and wait for all classes to be shown, while before I could immediately click on the class/object and proceed.

**Comment by manuelma** [comment]
Thanks @jimhommes
> but it takes more time to select the filter and wait for all classes to be shown
You mean to be shown in the parameter table views, right? Not the entity tree view.

**Comment by jimhommes** [comment]
No indeed, the entity tree shows all classes and objects immediately. It takes time for the classes to load as parameters under the object_class_name filter.

**Comment by DillonJ** [comment]
I am finding this also. Generally speaking, the behaviour when selecting an item in the tree is completely unpredictable. I agree that it's not very usable at present.

Graph view is behaving very unpredictably also. Clicking on the same stuff gives different results.

Also, my issue #1454 - empty relationships aren't greyed out

**Comment by manuelma** [comment]
I will fix all this as soon as I am back.

**Comment by manuelma** [comment]
The unpredictability comes from the lazy loading. We need to activate fetching from the graph and from the parameter tables. It would help if you could detail more what do you mean by unpredictable exactly, what do you do, what do you expect and what happens instead.

**Comment by manuelma** [comment]
Can you @DillonJ or @jimhommes provide with concrete examples of problems? Do you have a database and some clear steps to produce unsatisfactory results? I am talking in particular of the entity graph showing wrong graphs, or the parameter tables being populated with incomplete information. Remember the guidelines of bug reporting in our README ;)

**Comment by manuelma** [comment]
I think the situation has improved. You may want to check out latest master to see if you still find any problems. If you do, again, please provide repeatable steps to help debugging.

**Comment by jkiviluo** [comment]
I think this is fine now. Closing.
