### ISSUE TITLE
Test if pywin32 can be upgraded to v301

### ISSUE THREAD

**Issue by ererkka** [Spine-project/Spine-Toolbox#1457]
See security alert https://github.com/Spine-project/Spine-Toolbox/security/dependabot/requirements.txt/pywin32/open

See also #1230

**Comment by PekkaSavolainen** [comment]
No such luck. Same problem as with pywin32 v300. See https://github.com/Spine-project/Spine-Toolbox/issues/1230#issuecomment-807058397.

**Comment by ererkka** [comment]
How did you test? 

I tried in a fresh Conda Python 3.8 env `pip install spinetoolbox` which installs latest pywin32 v301. Starting `spinetoolbox` works just fine. Also `python -c "import win32api"` works with no errors.

**Comment by ererkka** [comment]
I have not tried on the official Python 3.8 as I don’t have that.

**Comment by PekkaSavolainen** [comment]
Tested this with sources from git `pip install --upgrade requirements.txt`.

```shell
(toolbox38) C:\>python
Python 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import win32api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing win32api: The specified module could not be found.
>>>

**Comment by PekkaSavolainen** [comment]
Something's not right here.

```
(base) C:\>conda create -n pypi_toolbox38 python=3.8
(base) C:\>conda activate pypi_toolbox38
(pypi_toolbox38) C:\>pip install spinetoolbox

(pypi_toolbox38) C:\>python
Python 3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import win32api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing win32api: The specified module could not be found.
>>> exit()
```

@ererkka What is your PATH in `test_env`?

**Comment by PekkaSavolainen** [comment]
I had two minicondas on my system. I uninstalled both and removed all envs and conda related directories and files I could find. I also cleaned up my PATH so even my pure python was not there anymore. Then I installed the latest miniconda3 which comes with python 3.9. Then I did the same on a brand new miniconda3

```
(base) C:\>conda create -n pip_toolbox38 python=3.8
(base) C:\>conda activate pip_toolbox38
(pip_toolbox38) C:\>pip install spinetoolbox
...
(pip_toolbox38) C:\>python -c "import win32api; print(win32api);"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: DLL load failed while importing win32api: The specified module could not be found.

(pip_toolbox38) C:\>
```

No luck.

`import win32api` after `pip install spinetoolbox` in a Python 3.7 Conda environment works without problems.

**Comment by PekkaSavolainen** [comment]
After fixing #1230. pywin301 works just fine.

It turned out that `import win32api` worked on @ererkka's system because the required DLLs were leaking into the `test_env` from the `base` environment.
