### ISSUE TITLE
Cannot enter new parameter value list values

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1459]
The 'parameter value list' tab allows to add new parameter value lists and to enter the first value to the list, but the second value doesn't stick.

**Comment by soininen** [comment]
I have a fix for this but unfortunately discovered some further issues with DB editor's tree view which need to get fixed before I can merge the changes to `master`.

**Comment by manuelma** [comment]
> I have a fix for this but unfortunately discovered some further issues with DB editor's tree view which need to get fixed before I can merge the changes to `master`.

It would be a good idea to describe those issues here before fixing. We have very few tests and I fear that we might break things easily.

**Comment by soininen** [comment]
While fixing the parameter value list bug I noticed that object group contents don't appear in the tree view when creating a new group in DB editor. The group object has that little 'expand tree' arrow but there are no child items. `ObjectTreeModel.add_entity_groups().` actually raises an `AttributeError` which is accidentally caught in `SpineDBSignaller._call_in_listeners()` which apparently shadowed the bug when it was originally introduced.

**Comment by soininen** [comment]
The above commits should fix the issues with parameter value lists and object groups. Next, I'll try to implement some unit tests so we don't break this stuff again.

**Comment by soininen** [comment]
Unit tests implemented. I believe we are done here.

**Comment by manuelma** [comment]
The original issue was actually a spinedb_api issue. We were calling DatabaseMappingBase.query where we weren't supposed to. This was the reason why import_data failed with a complain about db_maps being used in the wrong thread. We don't need to do import_data in the worker thread, because all the data is already in the cache, which lives in the main thread.
