### ISSUE TITLE
"Nothing to update" when updating object name

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1461]
When I update object name from the edit object context menu item, Toolbox gives a warning that 'nothing to update'. It's possible to suppress that message, but it shouldn't be there in the first place.

**Comment by manuelma** [comment]
Thanks, we could get rid of that message alright. I didn't understand at the beginning, I thought the message was being shown when you actually changed the object name. I now confirmed it is only shown when you press Ok *without* changing the object name. This is intended, and I feel like we can keep it that way. My preference would be to only enable the Ok button if/when the user changes the name.

**Comment by jkiviluo** [comment]
It was actually the former, but I don't see it anymore. Maybe I hadn't updated the reqs. S*it, sorry.

**Comment by manuelma** [comment]
Could have been accidentally fixed while doing something else.
