### ISSUE TITLE
Editor windows more independent

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1463]
Currently editor windows are slaves to the main Toolbox window. This means that when editor window is active, then the main Toolbox window gets promoted in the stack of windows on the desktop. To me this often leads to situations where I need to try to hide the main Toolbox window away so that it doesn't block e.g. database editor that I'm trying to use side-by-side with an editor.

So, I propose to make the editor windows bit more independent. However, I think they should still close with the main Toolbox window (with prompts asking to save changes if needed).

**Comment by soininen** [comment]
Done.
