### ISSUE TITLE
Traceback when removing value from parameter value list

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1465]
1. Open DB editor with an empty database
2. Add a parameter value list
3. Add a value to the list
4. Remove the value

At step 4 my debugger catches the following Traceback:
```
Traceback (most recent call last):
  File "toolbox\spinetoolbox\mvcmodels\minimal_tree_model.py", line 287, in data
    return item.data(index.column(), role)
  File "toolbox\spinetoolbox\spine_db_editor\mvcmodels\parameter_value_list_model.py", line 84, in data
    return self.name
  File "toolbox\spinetoolbox\spine_db_editor\mvcmodels\parameter_value_list_model.py", line 63, in name
    return self.db_mngr.get_item(self.db_map, "parameter_value_list", self.id)["name"]
KeyError: 'name'
```

**Comment by soininen** [comment]
The above commit should fix this and another issue related to parameter value list removal. The second issue was that sometimes Database editor's UI needed an update while the list was already removed but parameter list tree view's items were not yet updated to reflect the situation. We now show `<removed>` for such items in the view.

**Comment by manuelma** [comment]
Nice one, thanks @soininen 

I'm presuming that <removed> is only shown in some transient state?

**Comment by manuelma** [comment]
Nice one, thanks @soininen 

I'm presuming that <removed> is only shown in some transient state?

**Comment by soininen** [comment]
> I'm presuming that is only shown in some transient state?

Yes. You might see `<removed>` for a short time after choosing to remove the items. Then they will be gone.
