### ISSUE TITLE
Random Traceback when closing Database editor and rolling back changes

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1486]
Looks like there is a race condition when closing the Database editor and discarding changes. I believe what happens is:

1. In `SpineDBManager.unregister_listener()` we call `SpineDBWorker.rollback_session()` if user chooses to throw away the changes
2. Worker starts to process `SpineDBWorker._rollback_session()` in another thread
3. While worker is working, `SpineDBManager.unregister_listener()` calls `SpineDBManager.close_session()`
4. `SpineDBManager.close_session()` deletes the undo stacks
5. Meanwhile, in another thread, `SpineDBWorker._rollback_session()` tries to clear the already deleted undo stack. A Traceback follows:

```
Traceback (most recent call last):
  File "toolbox\spinetoolbox\spine_db_worker.py", line 237, in _rollback_session
    self._db_mngr.undo_stack[db_map].clear()
KeyError: <spinedb_api.diff_db_mapping.DiffDatabaseMapping object at 0x0000017303C8C6A0>
```

**Comment by manuelma** [comment]
Nice. Are there steps to reproduce this? I guess I need to do some changes and then close the form without committing, and depending on how threads advance with respect to each other, I might see the traceback?

**Comment by soininen** [comment]
> Are there steps to reproduce this

As you said, you need to make some changes, then close the editor without committing them and hope for the best. I don't know if you'll see that Traceback, though, because it originates from non-GUI thread unless you're doing something like debugging in PyCharm.

In any case, one possible solution is to not to delete the undo stacks in `SpineDBManager.close_session()` but make sure they get cleared by the worker as needed as seems to be the case already (check `SpineDBWorker._rollback_session()`).

**Comment by soininen** [comment]
I guess you can make this more reproducible by adding an artificial delay to the worker thread, e.g. `sleep(1)` so that the GUI thread has time to make its moves.

**Comment by soininen** [comment]
The above commit should fix the issue and a similar one when committing changes.
