### ISSUE TITLE
Traceback in Database editor when rolling back changes in scenario alternatives

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1489]
1. Make a new database, open Database editor
2. Add scenario to the database
3. Commit changes
4. Drag and drop the Base alternative to the new scenario
5. Rollback changes
6. Observe a Traceback:

```
Traceback (most recent call last):
  File "toolbox\spinetoolbox\mvcmodels\minimal_tree_model.py", line 302, in data
    return item.data(index.column(), role)
  File "toolbox\spinetoolbox\spine_db_editor\mvcmodels\alternative_scenario_item.py", line 133, in data
    active = "yes" if self.parent_item.item_data["active"] else "no"
KeyError: 'active'
```

This needs a more thorough investigation, but I think the GUI is trying to update the Alternatives and scenarios tree while the scenarios are still being updated. The `KeyError` stems from the fact that `ScenarioActiveItem`'s parent, i.e. the scenario item, has an empty `item_data` dict.

**Comment by manuelma** [comment]
I think this can be fixed by removing items from cache *after* everything else. This is the same as for parameter value lists where we need to handle key errors because the view wants to paint itself in the middle of the removal. But I think all that could be solved by removing items from cache as a very last thing.

**Comment by soininen** [comment]
Yes, something like that is needed in case. What I am thinking now after rollback has been issues is to:

1. Rebuild (reset) models but don't expand items that would need cache/database access.
2. Disable views so users cannot manually expand anything
3. Put DB worker to work
4. When rollback is done, expand the items as usual
5. Enable views

Does that sound plausible?

**Comment by soininen** [comment]
Or we can delete the cache in the GUI thread and emit `session_rolled_back` there after worker has finished.

**Comment by soininen** [comment]
The latter approach seems to work nicely. Maybe we go with that?

**Comment by manuelma** [comment]
Seems good, thank you @soininen

I would like to give all this a closer look at some point. Maybe we can rationalize it better. The concept is nice but it's been patched a few times. Maybe we can do that together at some point.

**Comment by soininen** [comment]
> I would like to give all this a closer look at some point.

Sounds good! We could perhaps organize a minireview around the topic if we find the time. Pity, that the last project meeting won't be face to face.

**Comment by manuelma** [comment]
Do we still need `<removed>` after this?

**Comment by soininen** [comment]
> Do we still need <removed> after this?

This change fixed stuff when rolling back. `<removed>` appears when removing items, so yes, we still need that.
