### ISSUE TITLE
Improve plotting via graph opacity

### ISSUE THREAD

**Issue by Tasqu** [Spine-project/Spine-Toolbox#1491]
Originally suggested by Rodrigo Garcia Nava during the Case study webinar:

The plots in Spine Toolbox could be made clearer about overlapping lines by making the plotted lines partially transparent. Don't know if this is possible using the python library used for plotting via Toolbox, but worth looking into.

**Comment by soininen** [comment]
Transparency is certainly possible. I've now made the lines somewhat transparent. Let me know if it looks good or not.

**Comment by Tasqu** [comment]
Good enough for me. The point was mostly to illustrate situations where two lines are overlapping, and to me this seems sufficient. Closing this issue.
