### ISSUE TITLE
Feature Request: Duplicate Item in Graph view

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1492]
We have duplicate item context menu item in the stacked view when right clicking on an object in the tree... it would be nice to have this also in graph view

**Comment by manuelma** [comment]
It's done now.

**Comment by DillonJ** [comment]
Nice! Thanks @manuelma

**Comment by manuelma** [comment]
Did you try it? It's kinda cool how all relationships get duplicated too and we *see* it immediately :D
