### ISSUE TITLE
Clicking on relationship in graph view could prefill class and object-name-list in relationship parameter pane

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1494]
When I click on a relationship that has a parameter value in graph view, it correctly shows in the relationship parameter pane, however, when I click on a relationship that has no parameter values specified, the correct relationship is not displayed in the relationship parameter pane. 

When selecting a relationship in graph view, I would be expecting the context of the relationship parameter pane to change to display the correct relationship class and have the object list pre-filled.

See following example where a unit__to_node is selected :

![image](https://user-images.githubusercontent.com/7080191/133060370-d1232194-e83b-4a48-9588-603b6a099bfa.png)

**Comment by manuelma** [comment]
Thanks! I replaced the label bug by feature because it doesn't look like something is not working - it's just not implemented.

I will also adjust the title to reflect this is a feature request.

**Comment by DillonJ** [comment]
> Thanks! I replaced the label bug by feature because it doesn't look like something is not working - it's just not implemented.
> 
> I will also adjust the title to reflect this is a feature request.

From the behaviour where it shows you parameter values when an object is selected, it felt like it was trying to be context sensitive, I think it's what a user would be expecting.

**Comment by manuelma** [comment]
We can make it happen.

**Comment by DillonJ** [comment]
Nice one @manuelma  I've used this multiple times already - it's a really nice feature and makes graph view a really nice way to enter data!

**Comment by manuelma** [comment]
Thank you @DillonJ and thank you for the nice feature request. Keep it coming!
