### ISSUE TITLE
Database editor Traceback when closing from Windows Taskbar

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1496]
I encountered this on Windows but it might happen on other systems as well:

1. Check Toolbox settings. Make sure that DB editor asks for confirmation before closing if there are uncommitted changes
2. Open DB editor
3. Make some changes but don't commit
4. Activate any other non-Toolbox window
5. Close DB editor from Taskbar
6. Observe a Traceback:

```
Traceback (most recent call last):
  File "toolbox\spinetoolbox\spine_db_editor\widgets\graph_view_mixin.py", line 504, in closeEvent
    super().closeEvent(event)
  File "toolbox\spinetoolbox\spine_db_editor\widgets\spine_db_editor.py", line 809, in closeEvent
    if not self.tear_down():
  File "toolbox\spinetoolbox\spine_db_editor\widgets\spine_db_editor.py", line 797, in tear_down
    if not self.db_mngr.unregister_listener(self, *self.db_maps):
  File "toolbox\spinetoolbox\spine_db_manager.py", line 525, in unregister_listener
    answer = self._prompt_to_commit_changes()
  File "toolbox\spinetoolbox\spine_db_manager.py", line 565, in _prompt_to_commit_changes
    msg.setWindowTitle(parent.windowTitle())
AttributeError: 'NoneType' object has no attribute 'windowTitle'
```

Looks like we cannot rely on the editor window being the active window here.

**Comment by soininen** [comment]
Fixed.

**Comment by manuelma** [comment]
I think there was a reason why these dialogs were in SpineDBManager. Can't remember exactly but maybe something related to viewing multiple dbs in the same DB editor. So the question is, does this change affect viewing multiple dbs in the same editor?

**Comment by soininen** [comment]
> does this change affect viewing multiple dbs in the same editor?

It is not obvious to me how the changes could have broken anything in that regard. I tested the changes with multiple databases and everything seemed to work alright unless I missed something.

On a side note, I don't think it is very good design to call GUI functions in such a low level facility as the DB manager. It should rather delegate user prompts back to the client code.

**Comment by manuelma** [comment]
Thanks @soininen I was just trying to figure out why on earth I did it that way, doesn't seem logical. But it's fine, thanks for the fix!
