### ISSUE TITLE
Possibility to add more databases to a tab in Database editor

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1510]
Database editor supports viewing and editing more than a single database in a tab. The feature is only available when using the View project item, however. The *Open...* action in the tab's menu could ask if the opened database should be added alongside the existing databases or there could be a separate menu entry for adding another database to the mix.

**Comment by manuelma** [comment]
They can also directly add the second url to the line edit in the toolbar prepended by a semicolon and press enter. But yeah, we should provide better ways.

**Comment by soininen** [comment]
> They can also directly add the second url to the line edit in the toolbar prepended by a semicolon and press enter.

Thanks, I didn't even know that was possible. We could add a tooltip for that otherwise the feature will stay hidden forevermore.

**Comment by manuelma** [comment]
I'm trying to figure out what's better:
- Separate action in the File section of the menu called "Add...", or 
- Additional dialog that pops after the user has selected a db file from "Open...", that provides the choice whether to open in a new tab or on top of the current view?

**Comment by soininen** [comment]
I'm trying to figure out the same :)

PyCharm uses the additional dialog approach which slightly confuses me but that is probably because the options are somewhat complex (use same window closing other projects, *attach* to same window, open in new window). In that case a dialog probably can explain the options better than separte menu entries. Do we want an 'Open in another tab' menu entry? If not, then I'd probably go with 'Add...' because then users know what is going to happen beforehand.

**Comment by manuelma** [comment]
Yeah that feels better indeed. Another thing that comes to mind is whether or not we want all or some of these dialogs to allow multiple file selection?

**Comment by soininen** [comment]
I feel we'll need more than just a file section or Open file dialog as I expected users to have databases in their network with user names, passwords etc.

**Comment by manuelma** [comment]
I did something here, is it good enough to close? It's basically the "Add..." menu entry we discussed.

**Comment by soininen** [comment]
It's good. Nice work!
