### ISSUE TITLE
Plot legend should show alternatives as well

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1511]
Toolbox tries to make plot legend entries unique by combining entitye class, entity, parameter name etc. We should include alternative in the list, too, because now values of same parameter but with different alternatives are indistinguishable.

**Comment by manuelma** [comment]
Yeah, we need to fix the `index_name()` implementation in different models I think?

**Comment by soininen** [comment]
Yes, looks like the `index_name()` methods need some attention here.

**Comment by soininen** [comment]
Done.
