### ISSUE TITLE
Feature/Discussion: Toolbox Data Validation Tool

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1514]
We need to develop a toolbox data validation tool. We has some ideas today:
 - Allow for some basic validation rules on top of existing value type checks in importer/exporter
 - Reuse importer/exporter code to implement a dedicated data validator tool
 - A simple python tool that can take validation rules specified in JSON format and apply it to a datastore

Are there other ideas I have forgotten here? @soininen @manuelma  @jkiviluo @PekkaSavolainen 

It would be really great if we could identify something simple and fast to implement within the final weeks

**Comment by DillonJ** [comment]
Discussed today - the idea would be to use Cerberus (https://docs.python-cerberus.org/en/stable/index.html) 
pydqc (https://github.com/SauceCat/pydqc)
Implement as a Tool item which checks a dataset
Toolbox example with some very simple dataset (DS with one object and some parameters)

**Comment by soininen** [comment]
I gave Cerberus a spin by writing a little test script and it seems to work quite nicely. The script validates object parameter values against user defined Cerberus schema and raises an exception if the validation fails. Using it as a Tool item in Toolbox is pretty straightforward. You can define stuff like "min" and "max" and "type" to validate in a schema file. Then provide that file and a database URL as command line arguments to the script and you're good to go.

Using Cerberus in the script was pretty easy. Validation schemas can be a bit more work but that's something we can improve later.

**Comment by manuelma** [comment]
Nice! I was thinking we could have a plugin where we provide 'random' specs, and this can be the first one? Is is a good idea? It feels that the plugin thing is a bit underused, but then again that's not a reason for just use it. What do you think?

**Comment by manuelma** [comment]
Otherwise we'd need to think of a way to make this tool available to users?

**Comment by DillonJ** [comment]
Very nice @soininen 

So I think this is related to @manuelma's point - it would be nice to have something in toolbox that is called "Data Validation Tool". It could be a plugin or a new workflow tool... or perhaps it could be a precanned tool specification that is available by default.

I'm not sure what the best is here?

**Comment by soininen** [comment]
I think a plugin is the way to go here. I believe it'd be a useful testbed for Cerberus and validation as a whole and doesn't require too much work. I can see this turned into a full blown project item at some point but developing one is quite time consuming and at least I'm not familiar enough with Cerberus to be confident that it supports all the features we may need.

So I think the next steps I'll take are:

- Make the script validate relationship parameter as well
- Improve the schema file. Currently, it is a JSON file that contains a raw Cerberus schema which can be quite a mouthful to set up manually
- Add a new repository Spine-project/ValidatorPlugin for this. If you guys think it'd be better to have some kind of UtilitiesPlugins collection repository instead, let me know
- Write a README.md for the repository which documents plugin's usage
- Add the plugin to PluginRegistry repo

**Comment by PekkaSavolainen** [comment]
Good plan @soininen but there is one piece missing. The new ValidatorPlugin requires the 'cerberus' package and this should be mentioned in the ValidatorPlugin's README.md. 

When we have #1499, we could have a requirements file in the ValidatorPlugin repo. Then, when the user installs the plugin, Spine Toolbox sniffs the requirements file and let's the user select an environment that contains the required package(s).

**Comment by soininen** [comment]
There is now a new plugin, **DataUtilities** available in Toolbox. The plugin installs a **Validator** Tool specification that can be used to validate object and relationship parameter values. See the [plugin's GitHub page](https://github.com/Spine-project/DataUtilitiesPlugin) for usage instructions or contact me if you need more information.

**Comment by jkiviluo** [comment]
We did bit of iteration with Antti. I think it works nicely. I'm closing this issue. Great work!

**Comment by DillonJ** [comment]
Nice one @soininen I just had a look and this is really great work. Kudos!
