### ISSUE TITLE
Filter by object class when fetching objects

### ISSUE THREAD

**Issue by ererkka** [Spine-project/Spine-Toolbox#1516]
Implement filtering by object class when fetching objects instead of fetching all all and putting others to cache. The current solution dates back to when there was no lazy loading of data.

**Comment by manuelma** [comment]
I think filtering by class_id might be too slow. True, it saves us one level of cache, but I feel we need to prioritize performance.

**Comment by ererkka** [comment]
Isn’t that also affecting performance if we fetch all the objects all the time?

**Comment by manuelma** [comment]
This is implemented now (829e54aa5aa2618a2368cb448cae684d2a4d47a8)
