### ISSUE TITLE
Have multiple projects open simultaneously?

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1531]
Currently one can open many spinetoolbox windows with different projects, but do we want to allow for opening different projects into tabs in the same toolbox window?

**Comment by jkiviluo** [comment]
I've thought that people generally work on a single project (putting Toolbox developers aside). At most they could have 2-3 projects and that's still doable with separate Toolbox instances. I wouldn't put a high priority on this even though I wouldn't mind seeing that.

**Comment by manuelma** [comment]
Yeah, I actually am just checking, not saying it's a good idea. It even sounds like a not so good idea.

**Comment by soininen** [comment]
I don't see this feature as very useful since we fully support having multiple Toolboxes open at once. Feels like little gain for the amount of extra code we'd need to develop and maintain and I'd rather spend that time improving inter-main-window-communication like copy pasting.

**Comment by ererkka** [comment]
Agree. For example my favourite editor Visual Studio Code has also the one project (= folder), one window approach. You can also create a so called workspace with many folders, but things get messy soon.
