### ISSUE TITLE
Unnecessary changes into project files

### ISSUE THREAD

**Issue by ghost** [Spine-project/Spine-Toolbox#1532]
Toolbox sometimes makes unnecessary changes into the project.json or other json formatted specs. Usually this involves changing the order of some files. See e.g. these diffs:

```diff
--- a/.spinetoolbox/project.json
+++ b/.spinetoolbox/project.json
@@ -358,13 +358,13 @@
             "specification": "Import_BB_base_sets",
             "cancel_on_error": false,
             "file_selection": [
-                [
-                    "Backbone_base_sets_to_gdx.lst",
-                    false
-                ],
                 [
                     "Backbone_base_sets.gdx",
                     true
+                ],
+                [
+                    "Backbone_base_sets_to_gdx.lst",
+                    false
                 ]
             ]
         },
```

```diff
--- a/Backbone_input_files/bb_base_sets.json
+++ b/Backbone_input_files/bb_base_sets.json
@@ -8,8 +8,8 @@
     "inputfiles": [],
     "inputfiles_opt": [],
     "outputfiles": [
-        "Backbone_base_sets_to_gdx.lst",
-        "Backbone_base_sets.gdx"
+        "Backbone_base_sets.gdx",
+        "Backbone_base_sets_to_gdx.lst"
     ],
     "cmdline_args": [],
     "execute_in_work": true,
```

The example project is here: https://github.com/TradeRES/TradeRES

This is annoying when the files are in version control. It also hides real changes.

## Expected
If there is no functional change, the project file and other specs should be intact.

**Comment by jkiviluo** [comment]
Here https://github.com/Spine-project/Spine-Toolbox/issues/1238 we suggest that project.json should be divided into git and ungit files.

**Comment by ererkka** [comment]
That is related, yes.

**Comment by PekkaSavolainen** [comment]
I probably have a solution for this. Check out branches `issue_1532_prevent_unnecessary_changes_in_project_files` from toolbox and `issue_1532_prevent_unnecessary_changes_to_project_files`. This should fix the problem for Importers but it needs to be tested and applied for other project items as well.

**Comment by manuelma** [comment]
What's the approach @PekkaSavolainen ? Can you describe it a little bit?

**Comment by soininen** [comment]
Instead of keeping and maintaining the 'original' item/specification dict in memory and sorting/comparing stuff, wouldn't it be simpler if we just sorted the output dict in `to_dict()` consistently before writing to disk?

**Comment by PekkaSavolainen** [comment]
> if we just always sorted the output dict in to_dict() consistently before writing to disk?

I guess we could always just sort the lists in alphabetical order or is there some other way?

But the only way I could reproduce what's in the issue description for Importer's 'file_selection' list was to change the order in which the connections were added. E.g. when there are 2 DC's (a and b) connected to an Importer (i), I removed the connections and then connected b->i and then a->i and then saved. Then I removed the connections and connected first a->i and then b->i. This is when the change in project.json happens. So, If we load and add the connections when opening a project in a consistent way, it would solve many of these issues. But how do we do that?

**Comment by soininen** [comment]
I believe it is enough to sort the (jump) connections by (source, destination) tuples before storing the list on disk.

**Comment by manuelma** [comment]
Sorting the project dict before writing should be enough, absolutely.

**Comment by ererkka** [comment]
The branch `issue_1532_prevent_unnecessary_changes_in_project_files` seems to solve at least some of the problems.

**Comment by PekkaSavolainen** [comment]
The branch only applies the fix to one specific list in project.json (file_selection list for Importers). The same approach needs to be applied for other lists too. I'm pretty sure it works but it may not be the best approach.

**Comment by manuelma** [comment]
What about @soininen 's suggestion of sorting the project dict before writing the json. To me it seems much simpler. Does the mentioned branch solves something that @soininen 's approach doesn't?

**Comment by ererkka** [comment]
In the new branch, file lists in tool spec files still change randomly (the new order is not alphabetical):

```diff
--- a/spineToolbox.json
+++ b/spineToolbox.json
@@ -12,10 +12,10 @@
     ],
     "description": "Backbone",
     "inputfiles": [
-        "input/1_options.gms",
         "input/timeAndSamples.inc",
-        "input/modelsInit.gms",
+        "input/1_options.gms",
         "input/scheduleInit.gms",
+        "input/modelsInit.gms",
         "input/inputData.gdx"
     ],
     "inputfiles_opt": [
```

**Comment by ererkka** [comment]
Is anyone working on this anymore?

**Comment by soininen** [comment]
Fixed.
