### ISSUE TITLE
Script output to Basic Console comes in undefined order

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1534]
Trying this unassuming Python script in a Python Tool that uses the Basic Console:

```python
for c in ("a", "b", "c"):
    print(c)
```

Expected output:
```
a
b
c
```

Possible output:
```
b
a
c
```

**Comment by manuelma** [comment]
Also affects the julia Basic console. We need to check our threading probably.

**Comment by soininen** [comment]
Rather looks like we write to the wrong row in the console widget...

**Comment by manuelma** [comment]
That would also make sense. But what is special about python console here?

**Comment by soininen** [comment]
When the language is set to Julia, the console seems to treat the text cursor in a different way but I need to investigate further.

**Comment by manuelma** [comment]
That's right, it's slightly different but if we're lucky then your fix may apply anyways...

**Comment by soininen** [comment]
Right, exactly same fix applied to Julia as well.
