### ISSUE TITLE
Get rid of Project page in settings?

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1536]
I propose we get rid of this page, it doesn't feel like settings at all. We already have File -> Rename project that we can repurpose as File -> Edit project metadata, and allow for editing the description also in there.

What do you think?

**Comment by jkiviluo** [comment]
I think you're right. Settings is not the right place for the project information. Would just 'Edit project' be enough? Metadata sounds bit meta (non-intuitive). Could also be 'Edit project settings'.

**Comment by manuelma** [comment]
I also don't like metadata. Another idea is to keep it as "rename project" and then surprise the user with the description.

**Comment by ererkka** [comment]
Having rename in two places (Settings.. -> Project and File --> Rename...) is duplicate and I think should be only in one place. I agree that project metadata is not intuitive at all. However, I don’t mind having the Project page where it is now, though. Creating a new dialogue seems more effort than benefit.

**Comment by manuelma** [comment]
> However, I don’t mind having the Project page where it is now, though. Creating a new dialogue seems more effort than benefit.

The new dialog is already there and the effort to add the description field is *really* low. At the same time, all the other settings pages are for adjusting behavior, whereas the project page on the other hand contains information. It feels out of place.

**Comment by PekkaSavolainen** [comment]
No strong opinions here. I won't be missing the Project page if it would disappear. Only 'concern' is that the Project page is the only place in Toolbox where you can see the project description...

**Comment by soininen** [comment]
I've always wanted to have a separate UI for project settings, but honestly, there is a lot of software out there that mix project (or analogous) settings with application settings in the same dialog seamlessly. I guess in the end I don't have a strong opinion on this.

**Comment by manuelma** [comment]
That's true @soininen 

But in our case, since we have the "Rename project" dialog anyways, I don't think we need to maintain it in two places. Although it's very low maintenance effort. I'm making a big deal of a small thing. But let me just go with my proposed change so it's done :D
