### ISSUE TITLE
Tool filter filter icon does not display immediately.

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1543]
When I apply a tool filter on an arrow from a datastore, the filter icon doesn't display until I restart toolbox with the filter applied.

Not a show stopper :-)

**Comment by DillonJ** [comment]
The reverse is also true, the icon doesn't go away when you remove the tool filter

**Comment by manuelma** [comment]
I fixed this I think. It requires latest engine, so pleae run upgrade_reqs.bat as needed.
