### ISSUE TITLE
Relationship member editing creates new relationship instead

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1544]
In graph view, if I right-click a relationship then choose edit and change one of the member objects, it creates a new relationship and keeps the old one. The expected behaviour would be to update the existing relationship and have all relationship parameters carry to that updated relationship (which should happen automatically if the original relationship is updated rather than newly created.

I only ran into this when I found a ton of extraneous relationships which I thought I had updated.

**Comment by soininen** [comment]
There is a unit test, `test_modify_relationships_objects()` that's supposed to test exactly this and the test is passing. So, maybe it is not testing exactly the right thing. Anyone fixing this issue might want to check the test too.

**Comment by manuelma** [comment]
Are you sure this is the case @DillonJ ? In my toolbox the behavior is the expected.

**Comment by DillonJ** [comment]
I will do more testing and revert

**Comment by DillonJ** [comment]
OK, I've tested and it seems to be working now... perhaps what I did was change the member for a relationship parameter value which had the effect of creating the new relationship because in this case it wouldn't have existed - and this would be the correct behaviour in this case.

Apologies, hopefully I didn't waste too much of anyone's time.

**Comment by manuelma** [comment]
Not at all! I discovered some issues too. For example, when one edits the relationship, the graph view isn't auto-updated to reflect the change. I will fix that now.
