### ISSUE TITLE
DB Editor values have double-colon delimiting when copy/pasted

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1545]
As per the title, when I copy data from pivot view (and from other places) to paste into excel, the pasted values are delimited by `::`

This feels non standard and a typical user would expect the values to paste directly into excel unmolested. 

Is this necessary? Should we change the behaviour?

**Comment by manuelma** [comment]
the :: is just the separator for the type and value. not for the columns. I need to fix that thing, the :: shouldn't come with the value.

**Comment by manuelma** [comment]
I got rid of the double colon in copied parameter values. You will need latest toolbox **and** spinedb_api for copy-paste to work nicely.
