### ISSUE TITLE
Get rid of inputfiles in Tool specifications?

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1547]
I think input files could be 'passed' as command line arguments, rather than hard-coded in the inputfiles key of the tool spec.

I mean, that's already possible of course, since all potential input files are visible in the Tool's Available resources, so they can be used to create command line arguments.

One advantage of the inputfiles key is that one can specify wildcards and folders I think. One disadvantage is that all references to the files need to be hard-coded in the script.

**Comment by jkiviluo** [comment]
But not all tools use arguments to access input data. They just expect a specific file/folder structure to be there.

**Comment by manuelma** [comment]
I guess that's the point of inputfiles then. So the idea is that the files are always called the same, but their contents may vary depending on the run?

**Comment by jkiviluo** [comment]
Yes. And we should be keep the folder structure relative to the executable folder (to keep it portable).
