### ISSUE TITLE
Support for appending to a table when exporting gdx

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1548]
Currently, GdxWriter doesn't support appending to an existing table due to a limitation in the GAMS library that handles the writing. Exporting data to Backbone, however, requires this feature. A workaround could be to store the tables into memory and write them to disk only when GdxWriter finishes.

Cc @ererkka

**Comment by ererkka** [comment]
Good idea to collect all data first and then write to the file. GDX does not support appending to existing symbols.

**Comment by soininen** [comment]
Gdx export should now support appending to table. Please, update `spinedb_api` to benefit from the feature.
