### ISSUE TITLE
Add support to select multiple relationships in DB editor Pivot view

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1550]
I only appreciated the full power and flexibility of pivot view while watching the live demos recently. I've been since using it a lot.

What would make it enormously more useful is to be able to select multiple relationship parameters. 

For example in a SpineOpt output DB, if I have selected `*__unit__node__direction` I will typically move `unit`, `node` and `direction` to the column headings and I will see all unit flows. If I wanted to add a `node_state` which is on `*__node` it seems like this would be very easy since I could just add it to the column heading also and the `unit` and `direction` fields would be empty.

The more general description of this as suggested by @manuelma is to make available for selection the union of all object classes that are present in the selected relationship classes.

I believe this would greatly increase the usefulness of the tool!

**Comment by jkiviluo** [comment]
Is this same as https://github.com/Spine-project/Spine-Toolbox/issues/935? Do you mean 'Add support for displaying entities from multiple classes in the pivot view'?

**Comment by DillonJ** [comment]
You're right, I'll post there istead
