### ISSUE TITLE
Allow for setting the relationship class icon

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1556]
And rotate the icon in graph whenever the relationship is 2D. The idea here is to be able to set eg an arrow icon for `unit__to_node` and have the arrow indicating the flow direction.

**Comment by DillonJ** [comment]
Very cool... nice work @manuelma 

![image](https://user-images.githubusercontent.com/7080191/135877978-2240a117-8109-49b4-9b50-b766ff80a56a.png)

**Comment by manuelma** [comment]
Thank you @DillonJ I was going to ask if you could try it! I think we can keep this open for a while to collect side-issues...
