### ISSUE TITLE
Pressing stop execution button not working well for Julia

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1557]
If I see that something is going wrong with a Julia tool and want to abandon it, and I press "stop execution", running the tool again won't work. The only way around it I have found is to restart toolbox entirely.

**Comment by manuelma** [comment]
I'm not sure exactly what you mean @DillonJ, it kinda works for me. I can stop a SpineOpt tool for example and then run it again. It works fine. Maybe it's a windows thing? I will give it a try on windows soon.

**Comment by DillonJ** [comment]
It might also be specific to SpineOpt, which is the Julia tool I'm working with

**Comment by manuelma** [comment]
I think this works better now. Will close.
