### ISSUE TITLE
Importer: refactor MappingSpecificationModel

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1558]
The way we throw `MappingSpecificationModel` instances around in Importer is a bit confusing and we never delete the models in C++ side which leads to (minor) memory leaks. As a preparation to implementing #1549, I'm planning to refactor Importer a bit:

- A single `MappingSpecificationModel` should be owned by `ImportMappings`
- Deal with instances of `ImportMapping`s instead of having a multitude of `MappingSpecificationModel`s around

**Comment by jkiviluo** [comment]
@soininen Should we close?

**Comment by manuelma** [comment]
Could this be the reason of https://github.com/Spine-project/Spine-Toolbox/issues/1625 ?

**Comment by soininen** [comment]
This ended up being such a huge change I'm not surprised if something got broken even with the extensive testing I tried to do.

**Comment by manuelma** [comment]
Yeah, I checked it a little bit and I have to say it's quite awesome, thank you for that! It was a total nightmare before. Anyways, I might have been able to resolve https://github.com/Spine-project/Spine-Toolbox/issues/1625 but maybe, whenever you get the chance, can you please take a look to make sure I patched in the right place...?
