### ISSUE TITLE
Debug in GAMSIDE, cannot open path

### ISSUE THREAD

**Issue by ererkka** [Spine-project/Spine-Toolbox#1562]
Clicking the link provided by a GAMS Tool item does not work. Execution log has the link:

    [05-10-2021 16:41:14] There was a compilation error [exit code:2]
    [05-10-2021 16:41:14] Click here to debug in GAMSIDE

Event log says:

    Unable to open file:///C:%5CDATA%5CTradeRES%5CTradeRES%5CBackbone%5Cbackbone_autocreated.gpr

Clearly something funny with the path.

**Comment by PekkaSavolainen** [comment]
Which OS?

**Comment by PekkaSavolainen** [comment]
Do the other links like `work directory` or `source directory` work in Execution Log?

**Comment by PekkaSavolainen** [comment]
Try again with latest spine-items please.

**Comment by ererkka** [comment]
I’m on Windows, there is no GAMSIDE for other platforms. Other links work fine (e.g. **results directory**)

BUT: I had not associated .gpr files with GAMSIDE, and after I did that opening the debugging works! 

However, the error message in the Event log in the file url form was a bit confusing with the slashes shown as ‘%5C’. I think it could be shown as a regular path instead. What do you think?

**Comment by PekkaSavolainen** [comment]
> BUT: I had not associated .gpr files with GAMSIDE, and after I did that opening the debugging works!

When I tested this, I had not associated .gpr files to anything either. On my system, Windows kindly opens the *How do you want to open this file* dialog when clicking on the **Click here to debug in GAMSIDE** link in Execution Log when removing the .gpr file association. I'm not sure why it did not open the dialog for you...
