### ISSUE TITLE
Database editor: row position updates and errors happen too soon

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1571]
When I'm adding a new parameter value row in the database editor, the row is validated when I move between the cells on that row (e.g. from parameter_name column to the alternative_name column). If that parameter uses a list, the editor will show an error indicating that I don't have a value from that list - but I didn't yet have a chance to add it. It's possible to suppress those errors, but that's of course not the solution since I want the error if I move out of the row when I haven't given a valid parameter value.

Similarly, the position of the row is updated once the parameter_name is selected and the user moves to the alternative_value cell. This is confusing - I want to first finish the row. The position should be updated only after I move out of the row. Or maybe it should be updated only after pressing a 'refresh button' or doing a commit (and also after re-opening the DB of course). I might want to add multiple rows and see what I'm adding and keep modifying them until I'm satisfied. It is confusing when those rows go somewhere else - I don't recognize anymore what I have done.

**Comment by jkiviluo** [comment]
>  shouldn't we reserve the label bug for stuff that's really a bug? 

Right, I understand that there is a difference between bugs that really break things and things that can be worked around. 

This included a 'bug' of the latter category: "the row is validated when I move between the cells on that row (e.g. from parameter_name column to the alternative_name column). If that parameter uses a list, the editor will show an error indicating that I don't have a value from that list - but I didn't yet have a chance to add it."  But it was possible to work around it, so I don't know. It's not a feature request either (although I guess I mixed some of that in the 2nd paragraph). Should there be some other category for these? We seem to have a label 'invalid', which I've never used, but could be useful. These kinds of 'bugs' are often relatively easy to fix and improve the user experience, so I'd like to see them fixed sooner than later (and thus a good label is important).

**Comment by manuelma** [comment]
I just changed so pressing refresh doesn't change the order. Only commit + refresh changes the order now. I think this makes the most sense.
