### ISSUE TITLE
Add menu option to tool_feature and to scenario_alternative

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1573]
Currently the only way to add new tool_features is by dragging from the feature to the tool. This may not be obvious to all users and we should also provide a context menu option to add a new tool_feature. Probably needs a dialog to choose from the features.

![image](https://user-images.githubusercontent.com/40472544/137074632-58a7c775-e5a3-4db0-8a9c-e895f02966aa.png)

Same goes for scenario_alternative as Antti noted below.

**Comment by soininen** [comment]
The Alternative/scenario tree is very similar to the Tool/feature tree. We should add same menu options there as well for consistency.
