### ISSUE TITLE
Renaming a tool item doesn't update the label in child Importer

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1589]
...and importer doesn't see the incoming resource anymore. I don't know if this ever worked or got broken at some point. Will provide steps to reproduce soon if needed.

**Comment by soininen** [comment]
Looks like Importer has not implemented the proper methods to follow predecessor renames.

**Comment by manuelma** [comment]
Thank you @soininen !

**Comment by soininen** [comment]
Commit Spine-project/spine-items@ac6ec43 should fix the issue. Looks like I messed the commit message though, so it is not linked here properly. Let me know if Importer reacts to Tool renaming properly now, @manuelma

**Comment by manuelma** [comment]
Thank you @soininen 

It works, except if I pack the CSV resources into datapackage.

So, create a tool that writes a couple of csv files, connect that to an importer, select Pack CSV resources in the link, and define a datapackage spec in the Importer. Run, see that it works.

Then rename the tool. In the importer, the name of the resource is still the one from the old tool name. If you double click on it to open the importer spec, you get the anonymous file thing. Then, if you run the importer, nothing is importer but no complains either. I don't know if you have time to look at this.

**Comment by soininen** [comment]
Thanks for testing the fix @manuelma! Looks like I forgot to try datapackages here. I can have another look at it at some point but it's not going to happen soon unless this is a critical bug for you.

**Comment by manuelma** [comment]
Not critical, thank you so much!

**Comment by soininen** [comment]
This has become such a fruitful source of renaming bugs! The above commits should crush them, though. Let me know if there is still something I missed.
