### ISSUE TITLE
Tool can't identify incoming resources from data connection after pull

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1590]
I have pulled latest toolbox and now the available resources in my tool have names like `<project>/data/xxx.csv`. The xxx.csv file comes from a DC. I was using the file as a command line argument, but now the tool complains that it cannot find the file. I need to manually fix the project myself. Was it impossible to do this for the user automatically? It's not the best user experience when updating the branch breaks your project, and results in extra work for you as a user. Or I am missing something?

**Comment by soininen** [comment]
This is due to implementing #1290. I'll look if we can make DCs' successor items update seamlessly. Apologies for the inconvenience!

**Comment by manuelma** [comment]
No worries! I'm thinking about general users, not myself - I am happy to fix my project manually to welcome these nice features.

**Comment by soininen** [comment]
Tools should now seamlessly adapt the new-style Data connection labels.

**Comment by manuelma** [comment]
I think this is fixed. Thank tou @soininen !
