### ISSUE TITLE
Importer filter behavior change proposal

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1592]
I have a dataset where one column indicates if the element is in service or not. I want to use the importer filter to only include rows where this value is one. I though that I would map this column to a parameter value, and then set a filter for the parameter value that matches only '1'. But when I run the importer, the row is still processed and the entity is imported, it just doesn't have the parameter value.

I think the filter could be more useful if the entire row was disregarded whenever any of the mapping components doesn't pass the filter. At the moment, the filter is processed independently for each component, so my thing doesn't work. What do you think?

**Comment by soininen** [comment]
I guess this change wouldn't break our use case, at least.

**Comment by manuelma** [comment]
Should I go for it if it doesn't break tests?

**Comment by soininen** [comment]
I think so. Perhaps you could consider adding a test for your use case so we won't break it accidentally in the future?

**Comment by manuelma** [comment]
Sure! Actually my change would break `test_filter_regular_expression_in_child_mapping_filters_parent_mappings_too`. If you look at this test, with the current design, it is importing object class 'B' even if the object 'r' doesn't pass the filter. With my change, object class 'B' wouldn't be imported which I think makes more sense?

So just adapting this test will indeed test my change. I will go for it and if in the future anybody feels against it, we will just add a new setting to control this behavior (hopefully we wouldn't need it).

**Comment by DillonJ** [comment]
I think I know what this use case is :-)

However, in this particular case I believe the real functionality you need is to be able to logically "switch out" the item - but you want to keep it in your model.

We have is_active and the tool filter... that accomplishes some of what you need.

I feel it would be nicer to develop this functionality instead - like tying it to visualisation.

**Comment by manuelma** [comment]
True @DillonJ. But still I think the user would expect that importer filters apply row-wise, rather than component-wise.

Regarding your suggestion, I was thinking that we could add some actions to the Spine DB editor to apply tool and scenario filters "in place" (which would be straight-forward to do thanks to @soininen 's work on the filter API), and that would accomplish my goal of excluding some entities from the graph view depending on the value of some method parameters. What do you think?

**Comment by manuelma** [comment]
The change is made, and no complains yet. I am closing, thank you for feedback!
