### ISSUE TITLE
Tool can't advertise latest results

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1595]
I have a project with a tool that I run a couple of weeks ago. Results where written to a directory called `da39a3ee5e6b4b0d3255bfef95601890afd80709`. Now I run it this morning and results where written directly to the output folder. I don't know what's going on here? Did the behavior change quickly during the past few weeks? Or am I missing something?

But the problem is my new results don't get advertised. The tool is stuck advertising results from the `da39a3ee5e6b4b0d3255bfef95601890afd80709` folder, because of how `spine_items.tool.utils.find_last_output_files` works (it seems).

**Comment by soininen** [comment]
I've been working on Tool output folder naming with regards to #1344. The changes to the output folders originate from there. Are you running filters with your Tool? If I remember correctly, the data goes to the hashed folders only in that case.

Anyway, I feel I didn't fully appreciate how `find_last_output_files()` deals with output data prior to the changes in #1344. I can try to remedy the situation. As a workaround, I think you should be able get the right results advertized by deleting the hashed folders.

**Comment by manuelma** [comment]
Thank you @soininen !

I indeed deleted the hashed folders and it went well.

**Comment by soininen** [comment]
There was actually a bug in `find_last_output_files` that prevented it from finding the latest files in this case. I think I got it fixed now.
