### ISSUE TITLE
Allow inserting and editing metadata in DB Editor

### ISSUE THREAD

**Issue by ghost** [Spine-project/Spine-Toolbox#1606]
Currently, the only way to add metadata to e.g. parameter values is through an import mapping. In some cases the dataset is created manually without using an Importer, and information about the data sources etc. should be somehow possible to enter as well. 

Also, DB Editor should allow editing existing metadata.

Related to #1603

**Comment by soininen** [comment]
Done. Lets discuss bugs/feature requests in new issues.
