### ISSUE TITLE
Slowness with Flextool 3 project 

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1609]
Opening the Flextool 3 project somehow takes very long. Also making some adjustments to the project take longer than one would expect. We should investigate what is causing the slowness.

**Comment by jkiviluo** [comment]
It stalls when I execute the exporter that has lots of csv files (it does the export fast, but after that it just keeps thinking).

**Comment by soininen** [comment]
I managed to bring the project loading time down from over 5s to less than 1s using the profiling module hinted in #1539.

I couldn't reproduce the stalling execution but there was a bug in `spinedb_api` that prevented the project from executing. It has now been fixed as well.

There is still a problem with 'Import_Flex3' Importer: the specification contains mappings for tables that are not produced by the predecessor 'Flextool3' Tool. This is an Importer issue, though and should be resolved under a separate issue.

**Comment by manuelma** [comment]
Just curious, why do we need to pickle DatapackageConnector?

**Comment by soininen** [comment]
> Just curious, why do we need to pickle DatapackageConnector?

This happens when Importer's executable item constructs `ReturningProcess`: the arguments, including the connector, are sent to the subprocess pickled. To get around pickling we could construct the connector in Importer's `ReturningProcess`, though.

**Comment by manuelma** [comment]
> > Just curious, why do we need to pickle DatapackageConnector?
> 
> Pickling happens when Importer's executable item constructs `ReturningProcess`: the arguments, including the connector, are sent to the subprocess pickled. To get around pickling we could construct the connector in Importer's `ReturningProcess`, though.

Thank you! So python pickles arguments to mp.Process automatically?

**Comment by soininen** [comment]
> So python pickles arguments to mp.Process automatically?

Yes. From [Python's docs](https://docs.python.org/3.8/library/multiprocessing.html#the-spawn-and-forkserver-start-methods):

```
More picklability

    Ensure that all arguments to Process.__init__() are picklable. Also, if you subclass Process then make sure that instances will be picklable when the Process.start method is called.
```

Most communication between processes pickles objects when using the `multiprocessing` module.

**Comment by soininen** [comment]
By the way, I just noticed that picklability might be required only on Windonws/MacOS sinche those two default to the `spawn` start method; in Linux the method is 'fork' by default.
