### ISSUE TITLE
Toolbox cannot handle parameter value lists in a MySQL database

### ISSUE THREAD

**Issue by ererkka** [Spine-project/Spine-Toolbox#1614]
Opening a MySQL database with parameter value lists produces the following traceback:

```
Traceback (most recent call last):
  File "...\SpineToolbox-master\spinetoolbox\spine_db_signaller.py", line 160, in receive_parameter_value_lists_added
    self._call_in_listeners("receive_parameter_value_lists_added", db_map_data)
  File "...\SpineToolbox-master\spinetoolbox\helpers.py", line 131, in new_function
    return func(*args, **kwargs)
  File "...\SpineToolbox-master\spinetoolbox\spine_db_signaller.py", line 306, in _call_in_listeners
    method({db_map: data})
  File "...\SpineToolbox-master\spinetoolbox\spine_db_editor\widgets\tree_view_mixin.py", line 270, in receive_parameter_value_lists_added
    self.parameter_value_list_model.add_parameter_value_lists(db_map_data)
  File "...\SpineToolbox-master\spinetoolbox\spine_db_editor\mvcmodels\parameter_value_list_model.py", line 30, in add_parameter_value_lists
    self._insert_items(db_item, items, ListItem)
  File "...\SpineToolbox-master\spinetoolbox\spine_db_editor\mvcmodels\tree_model_base.py", line 135, in _insert_items
    parent_item.insert_children_sorted(children_committed)
  File "...\SpineToolbox-master\spinetoolbox\spine_db_editor\mvcmodels\tree_item_utility.py", line 132, in insert_children_sorted
    if not super().insert_children(pos, chunk):
  File "...\SpineToolbox-master\spinetoolbox\mvcmodels\minimal_tree_model.py", line 147, in insert_children
    child.finalize()
  File "...\SpineToolbox-master\spinetoolbox\mvcmodels\minimal_tree_model.py", line 123, in finalize
    self._do_finalize()
  File "...\SpineToolbox-master\spinetoolbox\spine_db_editor\mvcmodels\parameter_value_list_item.py", line 82, in _do_finalize
    children = [ValueItem(self.id) for _ in self.value_list]
  File "...\SpineToolbox-master\spinetoolbox\spine_db_editor\mvcmodels\parameter_value_list_item.py", line 76, in value_list
    return self.db_mngr.get_parameter_value_list(self.db_map, self.id, role=Qt.EditRole)
  File "...\SpineToolbox-master\spinetoolbox\spine_db_manager.py", line 918, in get_parameter_value_list
    _split_and_parse_value_list(item)
  File "...\SpineToolbox-master\spinetoolbox\spine_db_manager.py", line 1997, in _split_and_parse_value_list
    item["split_value_list"] = item["value_list"].split(";")
TypeError: a bytes-like object is required, not 'str'
```

This is because `item['value_list'])` is a bytes object (`b'"down";"up"'` in my case) and should be split using another bytes object (`b";"`). In case of a SQLite db, `item['value_list'])` is a string.

**Comment by ererkka** [comment]
@soininen @manuelma any ideas?

**Comment by soininen** [comment]
The `value` column in `parameter_value_list` table has the `LargeBinary` type so I guess the exception is expected. We need to fix `spinedb_api`.

**Comment by soininen** [comment]
That was a bit of work but hopefully the issue has been solved now. Let me know if there are further problems with parameter value lists.

**Comment by ererkka** [comment]
Works without hiccups now, thanks a lot!

**Comment by manuelma** [comment]
This is a nice change and the unit tests are a huge addition, but I feel parameter_value_lists became too much of a special case code-wise. I fear a higher maintenance tax from now on, on a part of the code that it's already somewhat complex (and I'm to blame for that). Anyways, will try to think how it can be improved and use the new unit tests as cover. Thanks @soininen !

**Comment by soininen** [comment]
I totally agree with value lists being too much of a special case.

**Comment by manuelma** [comment]
I'm starting to think that collecting the list values outside of the query is not that nice. It feels like we messed up our design and now need to work around ourselves. We have the tools to do it any way we like, and the current solution is just not elegant in my humble opinion.

I'm thinking we could have solved this by homogeneizing the behaviour across the two dialects. For some reason SQLite was doing the concatenation as a string, whereas MySQL where doing it as bytes. We have `compile_group_concat_sqlite` and `compile_group_concat_mysql` in `helpers.py`, maybe those aren't working properly?

Could we consider reverting this into a branch for the time being, and see if we can fix it differently?

**Comment by ererkka** [comment]
Did you test on MySQL? As long as it works, and is good for the long run, I’m good, but let’s wait Antti’s response as well.

**Comment by manuelma** [comment]
> Did you test on MySQL?

I did, that simple change fixes the entire issue.

**Comment by manuelma** [comment]
I think the problem is our db structure. The `parameter_value_list` table is poorly designed, we should have an additional table only with the list values. At the moment it looks like this:

| id | name | value_index | value |
| --- | --- | --- | --- |
| 1 | booleans | 0 | true |
| 1 | booleans | 1 | false |

So as you see, two records (or as many values are in the list) have the same id, and the name needs to be replicated too -- the primary key is (id, value_index).

It looks like I designed this having in mind that I will group_concat the values, which in hindsight seems bad. In my opinion, @soininen was just fighting this poor decision, but a better solution (also in my opinion) is to use my patch and then wait for an opportunity to fix my design and only then use @soininen 's way. Maybe that opportunity will come when we decide to support complex values in lists?

**Comment by soininen** [comment]
I'm fine with reverting and going with casting if it works that easily. What I would like to salvage from the commits here are the improvements to unit tests, though. Are you working on this already @manuelma or should I do the honors?

We could consider adding a 'type' column to the value table ifwe end up changing the database tables. I know some users would like to have other values in the lists besides strings/floats/booleans.

**Comment by manuelma** [comment]
I already did exactly that, salvage the new tests and improvements to existing ones in both spinetoolbox and spinedb_api and apply my solution on top. I will merge them now into master. Thank you!

**Comment by manuelma** [comment]
We used to support complex values until we begin extracting the type from the value, then we dropped it. That's why we concatenate using `;` and not `,`, because semicolons are more difficult to find than commas in json strings.

**Comment by manuelma** [comment]
See https://github.com/Spine-project/Spine-Database-API/issues/151
