### ISSUE TITLE
Let jumps advertise their resource backwards

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1620]
I want to use the looping functionality, so I built this workflow

![Screenshot from 2021-12-03 17-21-14](https://user-images.githubusercontent.com/11472756/144637562-82d1a2ed-308d-4a18-b9ff-8d1563d3bb54.png)

The issue I'm having is I need Tool 1 to receive the url at Data Store 2 as a resource, so I want the 'jump' link to advertise their resource backward.

I can't do it by putting a normal link from to Tool 1 to Data Store 2 because that introduces a deadlock.
I don't want to do it by putting a normal link from Data Store 2 to Tool 1 either, because it's unintuitive (Data Store 2 is not an input to my tool, is more like an output), and because it introduces a precedence that I may not want.

To me, the intuitive thing would be that the jump link advertises resources from destination to source just as the normal link would do, and that would apply in the engine's backward sweep.

**Comment by jkiviluo** [comment]
Good catch. 

I started wondering (again) why do we cling to DAG. It does help to avoid infinite loops, but it also prevents things that can be natural to do. In your example, it could make sense to sometimes execute DS1, Tool1, DS2 but at other times DS2, DS1, Tool1.

I'm also confused by the 'execution' of data stores. We should rather execute the arrow between the data stores or then require that there is a tool between (which may just pass the whole DB but could also be a filter/transformer). There is a real issue there as well, since if you have multiple DS connected to a target DS, you cannot control what is executed. Should we open an issue about that?

**Comment by manuelma** [comment]
The workflow needs to be a dag with a start and a stop, otherwise it runs forever. If the start and stop need to vary across executions, we could think of a nice way for the user to set it up. At the moment they can add or remove links as needed, but maybe that's not ideal. A solution could be to provide an option to deactivate links temporarily for a certain execution.

Data store execution is a bit confusing indeed. We used to have the Combiner item that would be placed between two DSs, and when executed would merge one into the other. We decided to drop it and let DSs do the same job.

**Comment by soininen** [comment]
How does this work with self-jumps, i.e. jumps from an item back to itself? 
![repeater](https://user-images.githubusercontent.com/19147159/144972790-13254f3a-7b84-4e08-b88a-1552a4f1c9a3.png)


How about jumps from items that already advertise backward resources to the previous item?
![backward-jump](https://user-images.githubusercontent.com/19147159/144972805-cff54766-d5a6-4d0a-9ef5-eb9c0fce0b12.png)

**Comment by manuelma** [comment]
Nice one, I didn't about those cases.
I feel both cases are fine. In the second case there will be a complain about duplicate files eventually, that we can remove. Or you suggest we exclude those two possibilities?

**Comment by soininen** [comment]
> Or you suggest we exclude those two possibilities?

No, just wanted to make sure they work smoothly.

**Comment by DillonJ** [comment]
Does there need to be a distinction between resource links and workflow links?

A resource link wouldn't impose an order on executions but simply visually shows that a data resource is an input or output to some execution or tool and makes the resource available as an argument. It would be up to the user to ensure the executions would be happening at the right time.

**Comment by jkiviluo** [comment]
I like the idea of a resource link. It would be cleaner than a jump link for the purpose of just advertising resources. On the other hand, we have something that works now, so maybe not a high priority.

**Comment by manuelma** [comment]
The resource link doesn't work for items that need to be *executed* to produce their resources. I'm not convinced honestly, feels like it may be difficult to anticipate what will happen in complex situations.

On the other hand, I agree we should never use a jump link for the sole puprose of advertising resources. This issue however, is for the case when we do have a jump link, and we want to access the resource of the item after the jump, to help in progressing the iteration.

**Comment by manuelma** [comment]
Superseded by #1621
