### ISSUE TITLE
Source options aren't restored in Importer spec editor

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1625]
I have a feeling that this was working at some point, but now it seems broken. Will investigate and try to fix.

**Comment by manuelma** [comment]
Seems fixed by above commit. I didn't care to investigate much the new mechanics after https://github.com/Spine-project/Spine-Toolbox/issues/1558 but I hope I didn't do anything too bad.

**Comment by soininen** [comment]
The patch looks OK. It would be nice if the connector could be restored already in `ImportEditorWindow.start_ui()` but that would entail more refactoring and I'm not sure if it is really worth it at this point. Good work!
