### ISSUE TITLE
Option to purge DBs before running

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1633]
Re https://github.com/Spine-project/Spine-Database-API/issues/152

I think this is needed. I have a complex workflow that populates DBs upon execution and I constantly need to select and press New Spine DB on at least 3 DS before I can press play.

Here https://github.com/Spine-project/Spine-Database-API/issues/152 we discussed that Importers could have an option to purge target DBs before running, but I feel that's a bit complex since multiple Importers (and Mergers and Tools) might be writing to the same DB. I think a better place for this option is the Data Store itself, so we can select, for each Data Store, if the DB needs to be purged once before starting execution.

Will give it a try, what do you think?

**Comment by DillonJ** [comment]
I think this would be a great enhancement. I often want to purge my output db each a workflow is executed. However, perhaps there are hazards? E.g. you might turn it on once to purge your DBs because this is quite convenient rather than selecting New Spine DB on each DS... but then you might forget. Could we / should we warn users once on execution that DSs A, B, D and K will be purged?

**Comment by DillonJ** [comment]
On a side note - I like my icons in my datastores... purging output DBs gets rid of this. The only solution presently is to use the load template tool which I feel is a little awkward. When talking about purging DBs - can we have an option to "initialise" them also to the SpineOpt template?

**Comment by jkiviluo** [comment]
My initial feeling is that it would be more clear to have the purge happening from a tool that you execute separately from the DB. I have the same worry as Jody that one could easily execute a DB and purge it by accident. 

It could be a separate purge tool, if it feels too complicated in the Merger or Importer. The purge tool should then have the options to select what is purged (just like in the Data Store editor purge) - it would just remember those choices.

A purge tool could also be targeted to multiple DBs and making a fresh start that much more easy, but it's of course a detail here.

**Comment by manuelma** [comment]
Maybe you're right @jkiviluo maybe that's more intuitive. I will try to do it that way and see how it looks.

**Comment by manuelma** [comment]
> one could easily execute a DB and purge it by accident

**Comment by soininen** [comment]
Purging in Importer and Merger have been implemented some time ago. Closing this issue.
