### ISSUE TITLE
Relationship Icons not oriented correctly

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1637]
In https://github.com/Spine-project/Spine-Toolbox/commit/0be669873c7d29b5a41cbd1bbeab0b249c9708b7 the ability to set a relationship icon was implemented. We used this in SpineOpt to set arrow icons for the `unit__to_node`, `unit__from_node`, `connection__to_node` and `connection__from_node` relationships. It worked very nicely at the time - but recently something has gone wrong - either the wrong icons are being displayed, or more likely, the icons are not oriented correctly (180 degrees incorrectly) - i.e. they are pointing in the wrong direction in many cases.

See the below graph-view capture where I have selected only the `unit__to_node` class - so all Icons should be identical - but you see clearly some are pointing in the wrong direction.

![image](https://user-images.githubusercontent.com/7080191/149469114-b2da90a6-d182-4d1b-8c8c-920c3961eb59.png)

**Comment by manuelma** [comment]
Thank you @DillonJ nice catch. Should be fixed by above commit.
