### ISSUE TITLE
restore options of importer editor

### ISSUE THREAD

**Issue by IngridJSJ** [Spine-project/Spine-Toolbox#1649]
Hello Spine team, 
By mistake I closed the options of the Importer specification editor. 
And now I cannot restore the view to see  all the options. 
I have tried closing the project, pulling the latest spine, opening other projects and now in all projects I cannot view all the options. 
I can only see this
![image](https://user-images.githubusercontent.com/47012366/153398465-ee57a1e2-a809-461c-a49d-df0150cf8b16.png)
Could you please tell me how to restore the view of the editor?
Thank you!

**Comment by soininen** [comment]
Right-clicking on the title bar of any dock window in Importer specification editor will show you a context menu that lets you make the lost docks visible again. For example, right-click on the Mapping options title bar in the description's screenshot should work.

**Comment by IngridJSJ** [comment]
thank you very much for the quick and useful reply 👍
