### ISSUE TITLE
DB Editor Opens new DBs intitially with object class names invisible

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1652]
When opening a new DB, the width of the name column in the object and relationship trees is too small and displays only the object class icons and not the object class names.

This will be very confusing for new users as they will not likely know that they need to expand the column width to see the object class names which are otherwise hidden.

See here for example:

![image](https://user-images.githubusercontent.com/7080191/154519570-85b52bf4-e8f5-4918-8669-d66de98b0660.png)

Steps to reproduce:
 - Create new project
 - Add new sqlite datastore
 - Choose "new spine datastore"
 - Open datastore in DB Editor

You will see that the width of the name column in the object and relationship trees is too small to see the object class names.

If we subsequently inport the SpineOpt template, we have the same problem.

**Comment by manuelma** [comment]
The above commit should help, please reopen if not.

**Comment by jkiviluo** [comment]
Great! This has been a long-standing irritation, but never got around reporting it...

@manuelma I think you can close this (seems like you were thinking to do so).

**Comment by DillonJ** [comment]
This is actually still happening with me. I may have been too specific in the original issue description. I think it happens any time any DB is opened for the first time on a particular machine.

**Comment by manuelma** [comment]
I did something else here, seems to work better.
