### ISSUE TITLE
Warnings and Errors both appear in an alarming red colour in julia console

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1659]
Warnings appear in red in the julia console, as do errors - it's disconcerting for users (e.g. see https://github.com/Spine-project/SpineOpt.jl/issues/436). Is it possible to have warnings in a different colour. I know I asked this question before and I believe the reason is that warnings and errors both go to stderr and we don't have a way to distinguish between errors and warnings. Perhaps we could at least add a sentinel, or something, in our julia tools that would allow warnings and errors to be distinguished?

There must be some way around this?

**Comment by manuelma** [comment]
Latest master has good colors since about one week.

**Comment by DillonJ** [comment]
Really? Very nice!!!!

**Comment by manuelma** [comment]
Ok so at least we have an approach to handle this, even if it's not working well for some users, see #1660 

Let's close this and work on the specific issues.
