### ISSUE TITLE
Copy pasting of relationship parameter values in DB Editor not working correctly

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1663]
Here is the use case.

I have filtered the relationship parameter values by "fuel_cost" parameter:

![image](https://user-images.githubusercontent.com/7080191/158035881-8e2220fb-6905-4d9f-999b-850448ff9ca4.png)

I want to duplicate these values and assign them to a new alternative. So I select as follows and copy:

![image](https://user-images.githubusercontent.com/7080191/158035907-8ff99b41-8681-4e21-a5eb-2702ddc89f53.png)

Then I try pasting below but I get an error:

![image](https://user-images.githubusercontent.com/7080191/158035917-4e0e4509-7a80-4489-b2de-cfa47bcabf52.png)

It seems like the vertical bar is missing. I'm wondering if this isn't something that was done to making pasting into excel easier at the expense of breaking domestic copy/paste functionality. Ideally copy/paste should work both within DB editor and in excel

**Comment by DillonJ** [comment]
By the way, just wondering if we have tests for this kind of functionality?

**Comment by manuelma** [comment]
Fixed and tested in master now. Please reopen if the issue persists.
