### ISSUE TITLE
Purging DB and/or deleting data does not reduce file size

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1664]
To quickly purge an output database of its contents with the main objective of reducing its size, I deleted all the alternatives - which in db editor has the impact of deleting all the data, at least visually. However the file size is unaffected. I then tried using the purge option to delete everything (all boxes checked) but the filesize remained unchanged.

Do we need to alter how this all works behind the scenes and/or add a "compact database" option that deletes all unessesary stuff?

**Comment by manuelma** [comment]
Thank you. It seems to be an sqlite thing: https://stackoverflow.com/questions/2143800/change-sqlite-file-size-after-delete-from-table

Will see what can we do about it.

**Comment by manuelma** [comment]
That should be very easy, I can do it tomorrow. You could even run `vacuum` from any sqlite client btw.

**Comment by jkiviluo** [comment]
Nice catch.

The vacuum button is bit unresponsive though. A tooltip would be nice to explain what it does ('reclaim space occupied by deleted data'). Also a message somewhere indicating whether the vacuum was succesful or not. It could maybe even say the space taken before and after.

**Comment by manuelma** [comment]
Closing, please reopen if something missing.
