### ISSUE TITLE
Import map using python

### ISSUE THREAD

**Issue by IngridJSJ** [Spine-project/Spine-Toolbox#1670]
Dear Spinetoolbox team,
I would like to import a datamap programatically using python. 
So far I have imported data with a class that provided by you some time ago:
  https://github.com/TradeRES/toolbox-amiris-emlab/blob/main/EMLABPY/util/spinedb.py
      specifically the function 
        import_object_parameter_values(self, object_parameter_values) 
I have tried adding the values as a dictionary (  like this   {"key": "value"}   ) but it doesnt work. 
Could you share an example of how to add a dictionary as a value in a DB?

Thank you very much and best regards, 
Ingrid

**Comment by soininen** [comment]
What data does your dictionary contain? You cannot import 'a dictionary' as is; what you can import is time series, time patterns, arrays or maps. The most generic type is of those is map which resembles dictionary. You could import one with

```python
import_object_parameter_values(db_map, (("object_class", "object", "parameter", Map(["key1", "key2"], [2.3, 5.5])),))
```

See the `spinedb_api.parameter_value` module for more information on these 'indexed parameter values'.

**Comment by IngridJSJ** [comment]
Hello,
It works as you mentioned with Map from spinedb_api. 
Thank you very much!
