### ISSUE TITLE
Importer and exporter icons are too similar

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1672]
Kind of a minor issue, but sometimes I need to look twice to tell them apart. Will try to come up with something better.

**Comment by manuelma** [comment]
I tried something, basically changed the orientation of the arrow so it doesn't point in the same direction for both icons.

**Comment by soininen** [comment]
Nice! In fact, I've been having similar problems with the icons.

**Comment by jkiviluo** [comment]
Much better! How about the order in the ribbon? I think importer should come before exporter. This is really minor, but I notice it every time. :)

**Comment by manuelma** [comment]
> Much better! How about the order in the ribbon? I think importer should come before exporter. This is really minor, but I notice it every time. :)

I think you can rearrange icons in the ribbon with drag and drop, and the choice is remembered across toolbox sessions.
