### ISSUE TITLE
Exporter mappings cannot be copied or duplicated

### ISSUE THREAD

**Issue by Tasqu** [Spine-project/Spine-Toolbox#1688]
Occasionally, it would be practical to be able to duplicate or copy exporter mappings in the exporter specification editor, similar to what can be done in Importer.
![image](https://user-images.githubusercontent.com/77660814/161520770-6419efaa-4ecf-42f0-81e4-48955d8b0bb0.png)
There are no buttons that would allow to do any sort of copying, nor does `Ctrl + C` to `Ctrl + V` do anything.

**Comment by soininen** [comment]
The requested features are now available via a right-click context menu on the Mappings list.
