### ISSUE TITLE
Data connection loses file reference if file is changed and saved

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1691]
@DillonJ experienced this, is the title accurate?

**Comment by DillonJ** [comment]
I just replicated the issue now - it's ok if the file is open but if I make any change, as soon as I hit save in excel, the file rereference disappears and we get red excalmations on the tools.

**Comment by soininen** [comment]
There is this note in `QFileSystemWatcher` [documentation](https://doc.qt.io/qt-5/qfilesystemwatcher.html#fileChanged):

> As a safety measure, many applications save an open file by writing a new file and then deleting the old one. In your slot function, you can check watcher.files().contains(path). If it returns false, check whether the file still exists and then call addPath() to continue watching it.

If I had to guess, that's exactly what happens with Excel.

**Comment by jkiviluo** [comment]
I'm having this issue all the time with the FlexTool workflow. Bypassing the check for Excel could be ok, but it's of course bit hacky.
