### ISSUE TITLE
DB editor's parameter value table sometimes looses the empty row at the bottom of the table

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1693]
There are cases where the last empty row that is used to add new parameter values vanishes in the Object parameter value table. I assume the same happens in Relationship parameter value table as well. The issue is somewhat difficult to reproduce, but the following steps seem essential:

1. Select a specific object class from the tree
2. Select a specific alternative in the alternative tree
3. Try adding a parameter value that is *already* specified in another alternative, i.e. readding something that is already there. DB editor will complain: 'The value of parameter 'X' for entity 'Y' is already specified.
4. Try changing the alternative to something where the value has not been specified.
5. Sometimes the value row disappears from the table (as it should, I guess, since we're filtering by alternative). However, the empty last row disappears with the value row as well. This is a bug.

Noticed by @jkiviluo

**Comment by manuelma** [comment]
I've seen this.

**Comment by manuelma** [comment]
I find the culprit, will fix now.

**Comment by manuelma** [comment]
I think this is fixed. Please reopen if not.
