### ISSUE TITLE
Select new scenarios and tools for filtering by default?

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1695]
Currently, no scenario/tool is selected in link's filter by default. This means that all database data is just dumped to the downstream item. This breaks the model in case of e.g. FlexTool3. Ideally, users should be able to just execute the workflow without needing to remeber to set up the filter.

Would it make sense if link selected recently added scenarios/tools automatically?

**Comment by jkiviluo** [comment]
> Would it make sense if link selected recently added scenarios/tools automatically?

Sounds nice.

**Comment by soininen** [comment]
New scenarios/tools now get selected for filtering by default. Note that if you never selected any scenarios/tools for filtering in a project, all scenarios/tools will be selected when you next time open the project and you may need to manually deselect them. This is a limitation imposed by how we used to store filter information in `project.json` before.
