### ISSUE TITLE
Exporter: How to manage inconsistencies between Output file/label and Export format in spec?

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1696]
Another flaw I detected is if I enter something like exported.xlsx in Output file/label and then forget to select the Excel format in the specification and select, say, CSV instead, then the exporter will ignore the exported.xlsx I entered and write to an automatically named csv file. There would be a message in Event Log saying that exported.xlsx was written though, which didn't happen.

Have you notice this @soininen ?

**Comment by soininen** [comment]
I'm well aware of the flaw but never got to open an issue about it/fix it. I guess I have not been able to decide if the file format should be set in the specification editor or the properties tab.

- The mappings are output format agnostic so you could use the same specification to export to different file formats
- On the other hand, when the specification is used as plug-in, you probably want to fix the output format in the specification itself. E.g a Backbone plugin should always write .gdx files.

Now that we have a bit more real life use experience I feel I'm inclined to keep the file format in the specification editor.

So, we need to fix the lack of communication between the properties tab and the specification editor. The editor should default to the output format of the file extension set on the properties tab and there needs to be updates in both directions when the file format/extension changes.

**Comment by manuelma** [comment]
I think the Output file/label line edit in the Exporter properties UI should be *only* label, that is, the name the user wants to set for the resource representing the result.

Then, when the Exporter runs, we look at the export format from the spec and decide what to do:

1. If the Exporter will generate a *single* file, then we use the label to build the filename, e.g. {label}.{ext}, where ext depends on the format (xlsx, gdx, csv, json, sqlite)
2. If the Exporter will generate multiple files, then we just use the label to 'label' the file pack resource.

In this way we don't need to worry about coordination between properties UI and spec editor. What do you think?

**Comment by soininen** [comment]
> What do you think?

Sounds like a good plan!

**Comment by soininen** [comment]
Exporter now adds correct extensions to output labels as needed during execution.
