### ISSUE TITLE
Can't plot a mixture of indexed and other data

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1697]
Open db editor, select a Map and a TimeSeries parameter value in table view, right click, plot, get an error with the message above.

Select only the Map or the TimeSeries, right click, plot; select the other, right click, plot in window -> works :)

Any clue @soininen ?

**Comment by soininen** [comment]
Nice catch! Sounds like an oversight in plotting logic. Maps were added late in the mix after all.

**Comment by soininen** [comment]
This should be fixed now.
