### ISSUE TITLE
Support python 3.9 and 3.10

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1700]
Python is evolving, should we support latest versions? @PekkaSavolainen do you know/remember the reason why we don't support them?

**Comment by PekkaSavolainen** [comment]
The reason was that our dependencies did not support python 3.9 when I checked and 3.10 didn't exist. I'm sure that at least 3.9 is now supported but one needs to check and make sure.

**Comment by soininen** [comment]
We should add GitHub Actions jobs to run the tests on all supported Python versions. Currently, we have jobs for Python 3.7 and 3.8.

**Comment by PekkaSavolainen** [comment]
Looks like Python 3.9 works fine. I'll merge spinetoolbox and spine-items branches `python-39` to master in an hour or so.

**Comment by PekkaSavolainen** [comment]
We now support Python 3.9. Requirement files, unit test runners and readme.md have been updated. I'll test Python 3.10 next.

**Comment by PekkaSavolainen** [comment]
We now support Python 3.10! If you want to try it out, please install Microsoft Visual C++ 14.0 or greater on Windows. Get it with Microsoft C++ Build Tools: https://visualstudio.microsoft.com/visual-cpp-build-tools/. This new requirement is mentioned in README.md three times.
