### ISSUE TITLE
the tool continues running even after generating the expected results

### ISSUE THREAD

**Issue by zhaokov** [Spine-project/Spine-Toolbox#1702]
I created a project and set up a tool called (run_model) as the last step of the flowchart.  In this “run_model” tool, I basically ran a python file to create the results.   When I executed the project, the python code of the "run_model" tool successfully generated the results, but the whole process was stuck in this last step.   Below is the screen-shot of my problem.   As you can see, the results (including “Analysis is done” from the last print command) are displayed in the python console window and the output files are also created, but the tool hammer still continues moving.  Does any one know possible reasons ?  Thank you.

![image](https://user-images.githubusercontent.com/104167801/164591965-afe02197-cee6-4971-b5ba-6b82ecc9e1b2.png)

**Comment by manuelma** [comment]
Any messages from the command prompt where you run spinetoolbox from?

**Comment by zhaokov** [comment]
Thanks for your reply.   Below is the message in the command prompt window:

C:\Users\wzhao001\.local\pipx\venvs\spinetoolbox\lib\site-packages\dagster\core\execution\context\output.py:247: UserWarning: `OutputContext.get_run_scoped_output_identifier` is deprecated. Use `OutputContext.get_output_identifier` instead.
  warnings.warn(

Actually, in the screen-shot I attached in my question, I set up the first tool (called data-preprocess) in the same way as the "run_model" tool.  I was thinking why the first tool did not get stuck.  

Thanks again.

**Comment by manuelma** [comment]
Thank you, I was really hoping to see something more there (the warning is ok, that can't be it).

Anything special about your python tool code? Is there any chance you can share your project here so I can test it?

**Comment by zhaokov** [comment]
Here is my project.   You may need to re-set the file path to run the project.   Thank you very much!

[wz_try_3.zip](https://github.com/Spine-project/Spine-Toolbox/files/8543277/wz_try_3.zip)

**Comment by zhaokov** [comment]
Hi, did you get a chance to run the project?  Thank you.

**Comment by manuelma** [comment]
Sorry! I was busy with other things, but will try it out now.

**Comment by manuelma** [comment]
Very interesting project!
So I made a few changes and the project now runs: [wz_try_3_fixed.zip](https://github.com/Spine-project/Spine-Toolbox/files/8638277/wz_try_3_fixed.zip)
You may need to reenter the python executable path in the two tool specifications, sorry about that.
Please take a look at my modifications. I basically made it so you don't need to manually hardcode the paths to the input and output files in your tool code. Instead, we pass them as command line arguments. I did this by drag-and-dropping items from the Available resources list, into the Command line arguments list in the Tool properties.

![Screenshot from 2022-05-06 09-23-27](https://user-images.githubusercontent.com/11472756/167086196-2a39d9db-d75c-449a-a324-d7f03fdcf3cd.png)

I also removed the Data Connection between the two tools. The Data_preprocess tool generates the file final_input.xlsx and passes it directly to the Run_model tool. You can look at the event log to see what the two tools are doing, it should look something like this:
![Screenshot from 2022-05-06 09-25-46](https://user-images.githubusercontent.com/11472756/167086516-ae6b2d60-ef68-4940-bdd7-bc84d334b839.png)

In particular in this line, *** Archiving output files to [results directory] ***, you can click on [results directory] to open the directory in your file explorer and inspect the output files.

Please let me know if you manage to make it work on your end too? Sorry again for taking so long and thanks for trying these things out!
.

**Comment by zhaokov** [comment]
Thank you very much.  I will try your method and let you know the result on my side.  Thanks.

**Comment by zhaokov** [comment]
Hi, I am not able to open the project you fixed.  Below is the error message.  Do you have any thought?  Thank you again.

------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\wzhao001\.local\pipx\venvs\spinetoolbox\lib\site-packages\spinetoolbox\ui_main.py", line 483, in open_project
    return self.restore_project(load_dir)
  File "C:\Users\wzhao001\.local\pipx\venvs\spinetoolbox\lib\site-packages\spinetoolbox\ui_main.py", line 509, in restore_project
    success = self._project.load(self._item_specification_factories, self.item_factories)
  File "C:\Users\wzhao001\.local\pipx\venvs\spinetoolbox\lib\site-packages\spinetoolbox\project.py", line 224, in load
    project_info = ProjectUpgrader(self).upgrade(project_dict, self.project_dir)
  File "C:\Users\wzhao001\.local\pipx\venvs\spinetoolbox\lib\site-packages\spinetoolbox\project_upgrader.py", line 55, in upgrade
    self._toolbox.msg_warning.emit(
AttributeError: 'SpineToolboxProject' object has no attribute 'msg_warning'

**Comment by jkiviluo** [comment]
I guess this could be potentially fixed by pulling the latest version of Toolbox and it's dependencies. If you have installed using a conda environment in Windows, then you can just enter:

- git pull
- python bin\upgrade_spine_reqs.py

on the conda prompt when you are at Toolbox directory.

**Comment by manuelma** [comment]
Thank you @jkiviluo 

that's right @zhaokov that should fix it.

**Comment by zhaokov** [comment]
Thank you very much.  It works now.  Can I ask another question?  In this sample project, I need to add a scenario factor vector to adjust the price.  Below is the code for price adjusting:

#-------------------------
price_df_ini = pd.read_excel(flnm_in, sheet_name='price')

k = np.array([0.2, 0.4, 0.3]); #--- 1, 0.6, 0.5

price_df = price_df_ini;
price_df['Price'] = price_df['Price'] * k;
#-------------------------

I will create 100 different vectors between 0 and 1 to adjust the price, run the calculation for each, and get the average total cost of the 100 scenarios.  I can use a "For" loop to handle 100 different factor vectors.  However, I am very interested to use the function Spinetoolbox provides.  I see you mentioned scenario analysis in the documentation, but it seems a little more complex than I need.  

Here is my quick thought.  I can generate 100 files (say, csv files) to respectively contain the 100 factor vectors and name the files as 1.csv, 2.csv, ..., 100.csv.  This way, maybe I can indicate the file name ID (from 1 to 100) in a scenario table.  I want to know how Spinetoolbox sets up a scenario analysis procedure to handle the 100 calculations parallelly?  Is there a simple way to do my work?  I appreciate any help and suggestion from you.  Thank you again!

**Comment by jkiviluo** [comment]
I opened this other question as a support discussion: https://github.com/Spine-project/Spine-Toolbox/discussions/1710
