### ISSUE TITLE
Get data behind plot

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1703]
If the user is not happy with the plot's look and wants to redo it in e.g. excel, there could be a context menu option to access the data in a table that can be copied to clipboard.

**Comment by soininen** [comment]
I kind-of recommend using Exporter for that but I guess being able to manually access the data in the GUI is handy, too.

**Comment by manuelma** [comment]
This is done now. Let's see how it works, I agree Exporter is the better solution but this also plays well with the pinned value functionality in the view where plots are free to generate.

**Comment by soininen** [comment]
Yeah, Exporter could be an overkill if you just want to get data out of Toolbox quickly. Nice work!

**Comment by manuelma** [comment]
I will close, please reopen or open other issues for problems.
