### ISSUE TITLE
Importer imports arrays incorrectly when using alternatives

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1711]
When importing an array that should be filtered by alternatives (and put to separate db rows according to the alternative), the importer ignores the alternatives and just imports everything to the first alternative in the sheet to be imported. E.g.

alternative | solve | period
-- | -- | --
Base | y2020 | p2020
Base | y2020 | p2025
4solves | y2020 | p2020
4solves | y2020 | p2025
4solves | y2025 | p2025
4solves | y2025 | p2030

where the 'period' column is to be imported into an array - 'solves' are to be entities. This results in one entity only (y2020 for alternative Base) when it should also have y2020 for alternative 4solves.  The period array for Base/y2020 contains: p2020, p2025, p2020, p2025.

**Comment by soininen** [comment]
Should be fixed now. Please upgrade spinedb_api.
