### ISSUE TITLE
Importer and data package / csv file: pecularities with a header

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1730]
First, I think one should be able to not use header when importing a data package. I can have multiple header lines in my csv and header makes it confusing, since my first line must be 'header' (when using a data package) and I need to map the first line to object name 1 and the 2nd line needs to be 'source type' 'row' that maps to object name 2 (maybe we should get rid of header all together - unless there is some functionality that 'row' does not provide). 

Second, header (or maybe it's data package) assumes that the objects in the header row have to be unique. If the same object name is there twice (because it is a relationship with multiple dimensions that make it unique, it will be attached with a number: chp, chp1, chp2 etc.

My work-around is to write a dummy row that I won't use and use row mappings on the following rows instead. See figure. Would be nicer if this would work as expected. A step forward would be to enable the choice of 'has header' for data packages. Then the work-around would be more straightforward.

![image](https://user-images.githubusercontent.com/40472544/174824845-8c11218a-fdd1-4ea8-85d8-d86540a6871b.png)

**Comment by soininen** [comment]
Looks like forcing unique column headers is indeed a datapackage thing.

**Comment by jkiviluo** [comment]
Is there a good reason to comply with the data package in our importer? I mean it would be nice to have multi-row headers that would make sense.

**Comment by soininen** [comment]
There is now an option to disable headers in Importer when using datapackages.

**Comment by soininen** [comment]
Implemented Has header option for datapackages. This should fix the related issues.
