### ISSUE TITLE
Importer resource file selection

### ISSUE THREAD

**Issue by nnhjy** [Spine-project/Spine-Toolbox#1740]
With resource files received as below, the importer uses a specification for the upper `results.gdx` exclusively (set in `File path` of importer pannel). However, the importer imports only the `varLevels.gdx` whenever being executed. 
![1659620206068](https://user-images.githubusercontent.com/43530784/182860955-3cca346c-1760-4e16-a447-ee3eed91dcce.png)

Can we have a better way to handle this situation where resource files are grouped? 

I feel it would be more intuitive to either 1) import all resource files under the selected group or 2) enable selecting individual files under groups.

**Comment by soininen** [comment]
Fixed. Please open a feature request if we ever need the option to select individual files under groups.
