### ISSUE TITLE
Unable to make connection

### ISSUE THREAD

**Issue by ariane-millot** [Spine-project/Spine-Toolbox#1749]
Dear Spine Toolbox team,
I followed the tutorial getting started from here https://spine-toolbox.readthedocs.io/en/latest/getting_started.html#getting-started
However, at the end, I have the following error "Unable to make connection. Try landing the connection onto a valid connector button."
I am using conda 4.10.3.
Also I have a slightly different interface from the tutorial in case it might have an influence  
![image](https://user-images.githubusercontent.com/61950310/186227062-ca6b669f-27f9-4551-bc91-e72530101010.png)
Would you have an idea on how to solve this issue?
Kind regards,

**Comment by soininen** [comment]
You'll need to hit one of those three white boxes ("connector buttons") on an item's icon with the head of the arrow:

![kuva](https://user-images.githubusercontent.com/19147159/186333921-7a4ee3a5-a189-4c54-bced-68954de964e8.png)

Trying to connect the arrow to a random position on the icon will give you the error.

The item icons have changed and we have added new ones and removed others since the tutorial was written. The tutorial definitely needs an update.

**Comment by ariane-millot** [comment]
Thanks I've tried that as indicated in the getting started documentation, but it's precisely what I can't seem to do because I get this error. "Unable to make connection. Try landing the connection onto a valid connector button."
I've tried all white boxes although I assume there is no difference between them.

**Comment by PekkaSavolainen** [comment]
Hi @ariane-millot. Sorry but I cannot reproduce the problem. Are there any tracebacks or error messages in the console?

**Comment by soininen** [comment]
I haven't heard anyone encountering this problem before. Are you using Windows? Did you install Toolbox in the Conda environment?

**Comment by ariane-millot** [comment]
Yes Windows and I am using conda 4.10.3. To install spine tool box, I've followed the steps indicated here https://github.com/irena-flextool/flextool but I didn't have any error message when I installed it.

**Comment by PekkaSavolainen** [comment]
Sorry @ariane-millot but I meant the Conda console where you type `python -m spinetoolbox` to start the application. Any error messages there after you try to make the connection or otherwise?

**Comment by ariane-millot** [comment]
Oh sorry, no error message either, it only starts the spine toolbox interface.

**Comment by PekkaSavolainen** [comment]
Ok. I suggest you reinstall the application and see if that helps. If not, please insert the output of `conda list` here.

**Comment by ariane-millot** [comment]
ok so I did reinstall the application and the issue is now fixed! (I wonder why it didn't work the first time though as I did the exact same things). Many thanks anyway!
