### ISSUE TITLE
Expending node groups in large DB causes DB Editor to crash

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1758]
When attempting to expand node groups in the below zipped Spine DB, toolbox will crash.

Note, it will take some time before the node groups appear in the tree.

[powersystems_test.zip](https://github.com/Spine-project/Spine-Toolbox/files/9504875/powersystems_test.zip)

@manuelma and ideas?

**Comment by manuelma** [comment]
Thank you @DillonJ - this is fixed now. I think @mihlema reported it too long ago offline.
