### ISSUE TITLE
Cannot see console when executing Run SpineOpt

### ISSUE THREAD

**Issue by lilanger** [Spine-project/Spine-Toolbox#1760]
Hi Spine-Toolbox team,
when I execute "Run SpineOpt" the julia console does not open, when executing load template it works perfectly. Can I do anything to see the julia console and solver output? This would be essential for debugging. My colleague runs Spinetoolbox 0.6.5 and can select an "Execution" to show the console but I don't have that. 
I run the 0.6.13.dev0 with version, Julia 1.7.3, and Python 3.7.3 on Windows 10.

specs:
![grafik](https://user-images.githubusercontent.com/54096244/189621550-56454145-a3aa-4fbd-8515-71916898a666.png)
while running:
![grafik](https://user-images.githubusercontent.com/54096244/189621977-7a10eb57-0ebe-4683-af45-66ff7a0bfbfb.png)
after execution:
![grafik](https://user-images.githubusercontent.com/54096244/189625333-dfd57590-e65e-4b6c-9ed0-f5837d87ca92.png)
older toolbox version:
![grafik](https://user-images.githubusercontent.com/54096244/189626052-39e1f402-f250-4afa-9617-c0bcee6454b1.png)

**Comment by PekkaSavolainen** [comment]
Hi @lilanger. Could you please archive the Skive project into a zip file and attach it here if it's not too big and the data is not confidential. I'll take a look.

**Comment by lilanger** [comment]
Hi Pekka,
sure, I actually have the same problem with all projects. So I will attach a smaller model and my environment files.

Thanks for looking into it!

[SpineOptProject_III.zip](https://github.com/Spine-project/Spine-Toolbox/files/9555511/SpineOptProject_III.zip)
[SpineOptProject.zip](https://github.com/Spine-project/Spine-Toolbox/files/9555523/SpineOptProject.zip)

**Comment by PekkaSavolainen** [comment]
I installed Julia 1.7.3, Did the install steps in https://github.com/Spine-project/SpineOpt.jl#installation, opened the project and pressed Play. Seems to be working fine on my system. On your system, do you see the Julia Console of `Load Template 1` after executing that Tool? Are there any error messages there?

![issue_1760_spineopt_works](https://user-images.githubusercontent.com/43600314/189876010-9efdc5a7-c5c4-4876-815f-5661abb889b2.png)

**Comment by lilanger** [comment]
Load template works fine:
![grafik](https://user-images.githubusercontent.com/54096244/189880666-f74722f2-d46d-4151-bf2b-a2efb6d96194.png)
but if I run Tool1 the console window does not change:
![grafik](https://user-images.githubusercontent.com/54096244/189880832-6a7500d0-5105-4299-94da-aed51fa59a76.png)

**Comment by manuelma** [comment]
Maybe this helps, I don't know. It can be that the Executions panel is fully collapsed and invisible and you need to drag the invisible handle with your mouse to make it appear. Check the video below:

https://user-images.githubusercontent.com/11472756/189885703-5ada8413-0a59-4432-9a45-aa6fc56a009b.mp4

**Comment by lilanger** [comment]
Yes, that's it! 🤦Thanks a lot!

**Comment by manuelma** [comment]
We definitely need to fix that.
