### ISSUE TITLE
Parameter editor context menus missing copy and paste actions

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1762]
At least Map editor is missing copy and paste options in the right-click context menu although copy-pasting works using the usual keyboard shortcuts.

**Comment by soininen** [comment]
Fixed. Now all table view context menus (unless I missed any) should have proper copy and paste actions.

**Comment by soininen** [comment]
Looks like sharing the copy and paste actions of Database editor across the different tables wasn't a great idea: pasting stuff to any table now pastes it to all tables at once. The copy has the same problem.

**Comment by manuelma** [comment]
Also, actions are only enabled after the user brings the context menu.

**Comment by soininen** [comment]
Fixed a bunch of copy-paste related bugs. @manuelma thanks for the heads up on the context menu bug!
