### ISSUE TITLE
Merger fails to import tool feature methods into target database

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1772]
The error log shows something like this:

```
Could not import tool feature method '('FlexTool3', 'connection', 'is_active', [b'"yes"', None])': Invalid method for tool feature.
Could not import tool feature method '('FlexTool3', 'node', 'is_active', [b'"yes"', None])': Invalid method for tool feature.
Could not import tool feature method '('FlexTool3', 'unit', 'is_active', [b'"yes"', None])': Invalid method for tool feature.
```

Looks like we should handle `method` in `import_functions._get_tool_feature_methods_for_import()` in DB server compatible way.

**Comment by manuelma** [comment]
Interesting, why is the method None? Shouldn't if be True for the filter to work?

**Comment by manuelma** [comment]
oh sorry, the method is 'yes'. But is yes in the parameter value list associated with the 'is_active' parameters?

**Comment by soininen** [comment]
Problem is that the parameter value list contains `"yes"` but not `[b'"yes"', None]` so we won't find the method in the list. I guess the method needs some conditional parsing here.

**Comment by manuelma** [comment]
Ok I see it.

**Comment by manuelma** [comment]
You're right, it looks like we can't find the method in the value list around import_functions.py:568

**Comment by soininen** [comment]
Yes, that's the line indeed.

**Comment by manuelma** [comment]
Sure. Maybe a possibility is not to call `from_database` when building the `list_values` dictionary and then `unparse_value` the method before looking it up?

**Comment by soininen** [comment]
I think we need to conditionally call `method = from_database(method)` to keep backwards compatibility. I'd rather compare values as Python objects, not JSON strings as the strings can contain the same data but have different formatting.

**Comment by soininen** [comment]
Seems to work. I'll add some unit tests and push if this works OK.

**Comment by soininen** [comment]
Fixed.
