### ISSUE TITLE
Move purge before writting to the arrow?

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1774]
It feels like it could be more useful to put this setting in the arrow, so eg the same importer or merger could purge one of their output DBs and not the other. At the moment if an importer or merger has purge before writing active it does it to all the outputs without any possibility to control that.

**Comment by jkiviluo** [comment]
That's right. An option would be to include that in the settings, but it could get messy with many databases.

I sometimes remove arrows for convenience - it would then be good that the arrow remembers its settings when its restored. Right?

**Comment by soininen** [comment]
> I sometimes remove arrows for convenience - it would then be good that the arrow remembers its prior purge settings when its restored. Right?

I'd rather add a way to disable an arrow. I'm not so fond of the thought that we'd save settings of every single object removed from the project "just in case user puts it back".

**Comment by manuelma** [comment]
I just moved the purge settings to the arrow and opened https://github.com/Spine-project/Spine-Toolbox/issues/1776 to work on the arrow disabling thing.

Closing now, please reopen if not good.
