### ISSUE TITLE
Enforcing write order might need more concurrent processes than the CPU count

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1782]
Since we introduced write-ordering it may happen that many processes need to be open and waiting for others to checkout on a DB before being able to proceed. The default maximum number of concurrent processes is the CPU count though, which combined with the above can easily cause deadlocks. This can be solved by the user by increasing the maximum manually but I think we better have a setting to allow unlimited concurrent processes (as we have for the consoles).

**Comment by manuelma** [comment]
I have added that setting but I think that still, we need to be able to identify that a deadlock is going to happen because the user is allowing too few parallel processes. What we can do is, before putting a process to wait for some others, check if there's enough room for those other processes to start?

Or, we can wait for the dependencies before even starting the dependant process - but that means less parallelism. I think we should strive for maximizing concurrency and serializing only at the last minute, when processes are ready to write - as we do now.

**Comment by soininen** [comment]
How is this deadlock happening, exactly?

**Comment by manuelma** [comment]
Say there are two Importers that write to the same DB. Maximum number of processes is set to 1. Importer A is set to write *after* Importer B. During a particular execution, Importer A happens to start before Importer B. Since max processes is 1, no other process can start until Importer A completes. So Importer B is waiting for Importer A to do its writing, whares Importer A is waiting for Importer B to finish so it can start...

**Comment by manuelma** [comment]
I think the simplest solution is to release the semaphore when a process enters "waiting for others to write" mode, and then acquire it again when waiting is done. In this way, processes that are purely waiting do not take space in the process count.  Will try to do that now.

**Comment by manuelma** [comment]
So the above two commits attempt to do what we just discussed. Not the ReturningProcess class exposes a context manager object called `maybe_idle` that temporarily releases the one-shot process semaphore. In addition, the ReturningProcess instance itself is now passed to the target function so the `maybe_idle` can be used from there. It might not be the most seamless method to achieve our purpose but I believe it's good enough. We just need to remember that all `ReturningProcess` target functions (aka `do_work`) will receive the `ReturningProcess` instance as first argument.
