### ISSUE TITLE
Add templates for pull requests

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1822]
We should have templates for pull requests in all four repositories. Each repository should have a `.github/pull_request_template.md` file that contains the following:

```
(description of changes)

Fixes # (issue)

## Checklist before merging
- [ ] Documentation is up-to-date
- [ ] Release notes have been updated
- [ ] Unit tests have been added/updated accordingly
- [ ] Code has been formatted by black
- [ ] Unit tests pass
```

**Comment by manuelma** [comment]
I have added unit tests... if new functionality added? Otherwise (just refactoring) we don't need new tests, right?

**Comment by soininen** [comment]
> I have added unit tests... if new functionality added? Otherwise (just refactoring) we don't need new tests, right?

You should *always* add new tests except when
- tests covering the code exist

**and**

- no functional changes were introduced

Changing existing functionality or fixing bugs is a good reason for additional tests.

Further, our test coverage is pretty bad so there is a high change that even though you don't make functional changes, the code you touch is not actually unit tested at all. Take it as an opportunity to improve the coverage!

**Comment by soininen** [comment]
That being said, I did update the wording a bit.

**Comment by manuelma** [comment]
Ok, so refactoring of covered code doesn't need new tests - that's great!

**Comment by soininen** [comment]
I'll go with the template in the description. We can change the wording later if something is unclear. I'll also modify the template a bit for the other modules as e.g. release notes are currently included only in `Spine-Toolbox`.

**Comment by soininen** [comment]
Done.
