### ISSUE TITLE
Automatic placement of plot legend

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1857]
Currently, plot legend is drawn below the axes. This is fine unless there are lots of plots and the legend just doesn't fit in the plot window anymore. In this case it would make sense to move the legend on the right side of the axis.

**Comment by jkiviluo** [comment]
I think right side is a better default, since it's easier to read anyway (especially in stacked plots)

**Comment by soininen** [comment]
> I think right side is a better default, since it's easier to read anyway (especially in stacked plots)

I'm OK with this, though I suspect those users who PrintScr the plot window straight to their conference slides will want an option to move the legend around. It wastes quite a bit of space if there is only a few lines in the plot as our labels tend to be rather long.

**Comment by jkiviluo** [comment]
yes, capability to move around is useful.
