### ISSUE TITLE
Importers not executed in dedicated order

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1866]
For some reason workflow started executing importers out of order. I think it has been working before. The one in the bottom right should have gone first according to the order numbers in the arrows.

![image](https://user-images.githubusercontent.com/40472544/201641358-d948c201-4950-4868-b6c3-4558f139a6a1.png)

**Comment by manuelma** [comment]
The number in the arrows is just for writing to the db, not for starting execution. Messages in event log are printed as items start to execute, but when it's time to write, they are lined up according to the numbers in the arrow. You can check the commit history in your db file to check that writes happen in the right order?

**Comment by jkiviluo** [comment]
You're right. I'm closing this. I'm not certain it's a good idea to let them work in parallel always. There is much data being red and kept in memory that it chokes my laptop.
