### ISSUE TITLE
Plotting of multiple timeseries values appears to be broken

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1886]
When I plot an individual time series, it works fine, but when I select two time series parameter values together and try to plot them, I get some sort of constant average. Here is an example:

Timeseries A:

![image](https://user-images.githubusercontent.com/7080191/202721624-a8313066-e5d6-4ad7-ab5e-8c2d7a60add7.png)

Timeseries B:

![image](https://user-images.githubusercontent.com/7080191/202721757-8c4b7cc7-e8aa-4472-b438-29cbf936277f.png)

Timeseries A + B:

![image](https://user-images.githubusercontent.com/7080191/202721911-78a5323b-660b-45c0-a469-ffc88f6ee2a5.png)

**Comment by soininen** [comment]
The plots are actually fine - the variations in the data are just so diminutive that when plotted together the plots look like horizontal lines. What is actually the issue here is the strange y-axis scale in the single plots and the way it's annotation is hidden by the plot title.

**Comment by DillonJ** [comment]
Just to add that context menu item "show plot data" also seems to be broken - before it would give you a column for each series but now all series are listed in a single column

@soininen I pulled latest master with your more plot types commit from just now and I get the same behaviour

**Comment by soininen** [comment]
> I pulled latest master with your more plot types commit from just now and I get the same behaviour

That PR was unrelated and didn't change any functionality regarding plotting in Toolbox.

**Comment by soininen** [comment]
> But in my timeseries B, you can see the data varying between 62 and 54 which aren't even on the scale in the A + B plot (which should be showing a value varying between 62 and 54)

The y-axis is scaled by some strange exponential factor that is hidden behind the plot title so those numbers are really meaningless. You can see the real numbers and scale in the plot which contains both time series.

**Comment by DillonJ** [comment]
Ahh, I see it now. When I click on show plot data I see that the values are constant. Strange that there is such wind profile-like variation on a minute scale? Looks suspicious ! 

@soininen There is also the issue with the show plot data for multiple series. Before each series was a separate column, now they are all in the same column

**Comment by soininen** [comment]
I'll try to figure out if we can do something about those y-axes in this case. At least that scaling factor should not be hidden behind the plot title.

> There is also the issue with the show plot data for multiple series. Before each series was a separate column, now they are all in the same column

I'll have a look at this as well.

**Comment by soininen** [comment]
On my system the y scale label is always visible and never hidden behind the plot title:
![image](https://user-images.githubusercontent.com/19147159/203050365-fc11f11d-e00f-4543-8f7d-881917a1b9d5.png)

I guess this is something they've fixed in recent versions of matplotlib.
