### ISSUE TITLE
Importer sets Bool = 2 for repeated timeseries

### ISSUE THREAD

**Issue by josefkoell** [Spine-project/Spine-Toolbox#1902]
When importing time series with the box "Repeat Time Series" checked, errors occur when executing SpineOpt, because a Boolean = 2 is set for the time series, which is not possible. This boolean is inserted by the importer. The following error message is received:
ERROR: LoadError: unable to parse value of `demand` for `SWE`: InexactError: Bool(2)

**Comment by soininen** [comment]
This should now be fixed. Note, that you'll need to open the Importer's Specification editor, uncheck and recheck the Repeat time series check box and reimport the data to make the changes take effect.
