### ISSUE TITLE
Disable Paste/Duplicate and duplicate files for project items that don't support it

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1910]
All project items have the *Paste and duplicate files* and *Duplicate and duplicate files* context menu (mouse right-click on project item in Design View) actions but they have only been implemented for Data Stores and Data Connections at the moment. For other items, these actions do the same exact thing as *Paste* and *Duplicate* actions. We should either disable, hide or print a warning to Event Log when user tries to click on eg. Exporter's *Paste and duplicate files* or *Duplicate and duplicate files* actions.

**Comment by soininen** [comment]
I wonder if the duplicate files action is relevant for e.g. Exporter - the files in the item's directory are generated by executing the Exporter. This is different from Data connection whose files are actual static data. I think disabling the action makes more sense for items like Exporter that produce (semi-temporary) files dynamically.

**Comment by manuelma** [comment]
> We should either disable, hide or print a warning to Event Log

My preference is to disable impossible actions in general, rather than hiding them or enabling them with a warning.

**Comment by PekkaSavolainen** [comment]
Went with the disabled approach. It was a bit tricky but I think I got it. Closing via PR soon.
