### ISSUE TITLE
Option to disable automatic addition of new scenarios/tools to filters

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1914]
Currently, new scenarios/tools are automatically added to filters. This isn't always desirable so we could add an option to connection properties tab on how to handle new scenarios/tools: add or ignore.

**Comment by jkiviluo** [comment]
I think we should also have a separate option that forces at least one tool filter to be chosen and separately also at least one scenario to be chosen (https://github.com/irena-flextool/flextool/issues/37).

**Comment by soininen** [comment]
> I think we should also have a separate option that forces at least one tool filter to be chosen and separately also at least one scenario to be chosen

I'll see what can be done with it.
