### ISSUE TITLE
Data Interface impossible to remove from the Design view

### ISSUE THREAD

**Issue by mdandreadtu** [Spine-project/Spine-Toolbox#2]
Once the **Data Interface** is added in the **Design View** it can't be removed. If the item is right-clicked the menu doesn't appear and the terminal returns: "_2019-06-24 11:34:26 ERROR: Unknown item type:Data Interface_". 
I'm using julia 1.1.1 | Spine Toolbox v0.2.4 | spinedatabase_api v0.0.27 |Python 3.7.1 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10

**Comment by PekkaSavolainen** [comment]
Thanks for reporting. I'll fix this shortly.

**Comment by PekkaSavolainen** [comment]
By the way, you can remove **Data Interface** items (and any other items) now by selecting it in Design View and pressing **Delete** on you keyboard. It's just the context-menu for **Data Interface** items that is not implemented yet.

**Comment by PekkaSavolainen** [comment]
@mdandreadtu This is fixed in dev branch. **Data Interface** items now have a context-menu (i.e. mouse-right click menu) as well.

**Comment by mdandreadtu** [comment]
great, thanks! @PekkaSavolainen
